### ISSUE TITLE
Inactivated advisor organizations appear as children on a parent's organization page

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1031]
Should the inactivated child organization be displayed with an "Inactivated" tag or should the child organization not even be displayed?

**Comment by midmarch** [comment]
@VassilIordanov can you please check if something still needs to be done for this issue?

**Comment by dspCarlson** [comment]
@midmarch This issue has been fixed.  I am closing this issue.  Inactivated organizations are no longer displayed as suborganizations on a parent organization's page.
