### ISSUE TITLE
"Save person" Buttons Disabled When Editing Email Address

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#105]
When editing a person's email address, the "Save person" buttons (upper-right and lower right) become disabled.  There are three ways to re-create this bug:

1. If an existing email address is present, remove it.
2. If an existing email address is present, start backspacing from the end.  As the backspace approaches a period, the buttons will be disabled but will then be enabled after the period is deleted.  When backspacing comes to the @ symbol, the buttons stay disabled.
3. If an email address is not present, type a space or any character and the buttons will be disabled.

Reference item 69

**Comment by gjvoosten** [comment]
I believe this is "by design", i.e. the email field must contain a syntactically valid email address (of the form _user@domain_) or be empty.

**Comment by dspCarlson** [comment]
@gjvoosten I will review this tomorrow.

**Comment by dspCarlson** [comment]
@gjvoosten After further review this is by design per your observation before.  Data validation is conducted at the data field level and then again at the form level when the form is saved.  I believe this is the only field that validates at the data field level which makes it an anomaly.  I am closing the ticket.
