### ISSUE TITLE
Advanced search does not find principal's first name

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1053]
A user couldn't find a principal's record searching by first name.  I was able to replicate the bug.

Test 1
I used Advanced search (with the "People" parameter) and entered the last name.  The search results returned the principal's record.

Test 2
I used Advanced search (with the "People" parameter) and entered the first name.  The search results did not return the principal's record.  In fact, none of the 24 returned results contain the principal's name.  There are 74 principal records which have the first name as part of a principal's name.  The first name can also be used as a last name.

Test 3
I used the first name in a general search without any parameters and the same 24 principal records were returned at Test 2 (along with 3,929 engagement reports).

Test 4
I used Advanced search (with the "People" parameter and a "Role" = principal) and entered the first name.  The search results did not return the principal's record.  In fact, none of the 24 returned results contain the principal's name.  The same search results as Test 2.

I have sent the principal's full name to @VassilIordanov on the high side.

**Comment by maradragan** [comment]
Added to #1969
