### ISSUE TITLE
Standardize how principal names are inputted and how principal names are displayed

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1104]
Principal names vary.  For example, some principals litter have one name.  Other principals have a name followed by their father's name.  Allow the super users to enter principal names based on the name formation.

Here are the name permutations for principal names:

1. One name only
2. Given name(s) and surname(s)
3. Given name(s) and surname(s) "son of" <father's surname>
4. Given name(s) and surname(s) "son of" <father's given name(s) and father's surname(s)>

Could a data entry template be created that takes these four permutations into consideration?  Principal names are all over the place when it comes to the "son of" names.

**Comment by maradragan** [comment]
Added to #1972
