### ISSUE TITLE
Allow super users to mark commonly used tasks for their advisor organization

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1163]
The super user for each advisor organization should be able to associate tasks with an advisor organization.

Make it easier for advisors to select tasks for an engagement report based on:

1. The advisor organization's commander's guidance; the commander wants to focus on certain tasks.

2. What tasks have been historically chosen from the organization's advisor engagement reports

When a report author from the organization creates a report, the tasks would be displayed for easy selection.

**Comment by VassilIordanov** [comment]
let's discuss again after #1247, could be addressed by customizing #1326

**Comment by maradragan** [comment]
Added to #1964
