### ISSUE TITLE
Add notification banner message when network goes offline

### ISSUE THREAD

**Issue by evdhoudt** [NCI-Agency/anet#1164]
While working on ANET. When the network connection fails there is no indication that the server cannot be reached. It seems like ANET has stopped working properly. Some pages continue to be viewable, however searches and other async calls stop working. This causes frustration with ANET, while the errors are caused by network issues.

Additional point of frustration is when a user leaves ANET open in a browser overnight and we upgrade ANET at night. The user comes in the morning and attempts to use ANET without refreshing the browser which results in errors.

Also consider adding:
`onlineUsers` - returns the currently/recently logged users, last time of service use and ip address (or an approximation - i.e. the most recet 20 users)

**Proposed Solution**
Design an functionality that detects new versions and drops in connectivuty, indicates it to the user, and possibly prevents actions that result in data loss

**Comment by VassilIordanov** [comment]
As part of the handshake with the server, the client should also be aware if there is a new version of the client software / or a modified anet.yml deployed to the server

**Comment by VassilIordanov** [comment]
to be addressed after implementing #561
