### ISSUE TITLE
When creating an engagement report, increase the number of recent tasks displayed

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1165]
Increase the number of recent tasks when creating an engagement report.

Currently only the last three tasks selected are displayed in the "Recent Tasks" section.

Increase the number of recent tasks selected to 10.

**Comment by VassilIordanov** [comment]
to be reviewed after the new autosuggest is rolled out

**Comment by maradragan** [comment]
Closed by #1602
