### ISSUE TITLE
Report cannot be approved if an attendee's position is changed during the approval process

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1177]
On 13 December 2018, a report could not be approved because the assigned position of a principal attendee was changed during the approval process.

**Comment by gjvoosten** [comment]
See also #392

**Comment by VassilIordanov** [comment]
In my opinion, we should save the organization of the primary attendee at the time of submission (or ideally at the time of engagement, but not sure how to do that ;) ) and use that to determine which approval process to use. 
We should also use this to determine to which org the report belongs
