### ISSUE TITLE
The requirement owners will be the last approval step for every advisor organization

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1178]
The requirements owner will now review every report before it is released.

Is there any way to build this last step into ANET?  Or should I write a SQL script?

**Comment by VassilIordanov** [comment]
So, we need a script that:
- For each advisor org, creates a step with a specified name (if it does not already exist)
- To that step, adds a list of approvers. I assume that list is always the same for the purpose of this change? will it slightly differ from one org to another?

It is probably best to do this in SQL. If you write such a script, could you run it through @gjvoosten for a review? The policy is to peer review all code :)

**Comment by dspCarlson** [comment]
The requirements owners will now manually enter an approval step for the organizations they want to approve reports for.
