### ISSUE TITLE
Administrators Cannot Create Advisors

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#119]
GitHub #10 was the original reference.  Super users can no longer create advisors.  That's good.  Administrators can no longer create advisors.  That's bad.

Reference item 77

**Comment by VassilIordanov** [comment]
@dspCarlson I need help reproducing this one. I just created an advisor using my account on staging so it works for me.

**Comment by dspCarlson** [comment]
@VassilIordanov I too can create an advisor in staging.  But Craig and I cannot create advisors in production.  See email with graphic.  The advisor button is disabled.  The mouse-over is a red circle with a slanted line.

**Comment by VassilIordanov** [comment]
fixed (albeight accidentally) by 6bed7d5a46424268bf59eb793906ec2733543862
