### ISSUE TITLE
After reading report found with the Daily Rollup, the browser backspace key returns to the Daily Rollup instead of an organization/sub-organization chosen from the Daily Rollup

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1200]
1. User displays the Daily Rollup
2. User clicks on an organization bar chart in the Daily Rollup; multiple sub-organizations are displayed in the Daily Rollup
3. User click clicks on a sub-organization; sub-organization reports are displayed
4. User clicks on a "Read Report" button; an engagement report is displayed
5. User clicks on the browser's back key; the browser returns to Daily Rollup, not the sub-organization from the Daily Rollup

The requirements owners would like the browser to return to the last sub-organization/organization chosen from the Daily Rollup.

**Comment by VassilIordanov** [comment]
fixed in 2.1
