### ISSUE TITLE
Report Author Should Not be Listed as One of the Six Recent Attendees

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#124]
In regards to #47. The report author should not be listed as one of the six recent attendees.  The report author is automatically added as the the primary attendee when the report is created.

**Comment by gjvoosten** [comment]
@dspCarlson Would you also not want to see yourself listed if e.g. you're editing someone else's report?
(Because that's the same form and the same list of recent people.)

**Comment by dspCarlson** [comment]
@gjvoosten Not sure if we are talking about the same thing.  Editing a report to select a recent advisor attendee is not realistic.  If a report gets edited for a missing attendee, it will be a missing principal.  Reports get edited for content and grammar.  You want as many names of principals in the recent attendees list. Principals are the most difficult to find in the search box. See #48

**Comment by gjvoosten** [comment]
@dspCarlson Thanks for clarifying the way of working with reports. It's clear to me now that showing _oneself_ among the recent attendees is never useful.
