### ISSUE TITLE
Mandatory data fields for completed or cancelled engagements

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1243]
The requirements owners have decided the following 10 data fields should be required for a completed engagement:
1. Meeting goal
2. Engagement date
3. Location
4. Atmospherics (positive/neutral/negative)
5. Atmospherics details (only if the engagement is neutral or negative)
6. Attendee: at least one advisor attendee and at least one principal attendee
7. At least one task
8. Key outcomes
9. Next steps
10. Report text

This would leave the following four data fields optional for a completed engagement:
1. Tags
2. Atmospheric details (only when the engagement is positive)
3. Report sensitive information text
4. Authorization groups

For a cancelled engagment, required fields are:
1. Meeting goal
2. Engagement date
3. Location
4. Reason for cancellation
5. Attendee: at least one principal attendee
6. At least one task
7. Next steps

I believe currently the following six data fields are optional:
1. Location
2. Atmospherics details (only when the engagement is positive)
3. Task
4. Report text
5. Report sensitive information text
6. Authorization groups

**Comment by VassilIordanov** [comment]
We should do this in 2 steps.

Step 1: make location and at least one task mandatory (for past or future engagements). Preferably in candidate and candidate 2.1

Step 2: Make the engagement details mandatory in candidate-2.1

**Comment by dspCarlson** [comment]
@gjvoosten An additional mandatory field for cancelled engagements should be one of the six cancellation reasons.

**Comment by gjvoosten** [comment]
> @gjvoosten An additional mandatory field for cancelled engagements should be one of the six cancellation reasons.

That is already the case, and will not change. But I'll make it explicit in the description.
