### ISSUE TITLE
Do not display an advisor organization's longName/description when displaying tasks

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1244]
When displaying an individual task (e.g. ..../tasks/1234), the advisor organization's longName/description should not be displayed.

Only the advisor organization's shortName should be displayed.

**Comment by gjvoosten** [comment]
The link text for the responsible organization for a task is `{task.responsibleOrg.shortName} {task.responsibleOrg.longName} {task.responsibleOrg.identificationCode}`.
This should be just `{task.responsibleOrg.shortName}`, no other fields need to be shown.
