### ISSUE TITLE
Advanced search results do not include the text field

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1246]
A user is requesting the text field be added to the advanced search result for reports.

The text field is nvarchar(max) in SQL Server.  An Excel cell in a spreadsheet can only hold 32,767 bytes.

The user wants to know if the first 32,767 characters of the text data field can be included in the search results.

Currently there are 1,069 released reports (out of 83,220 released reports) where the text field exceeds 32,767 bytes.

**Comment by dspCarlson** [comment]
@VassilIordanov Currently the requestor briefs his leader every morning.  The leader wants to know about the engagements in the leader's advisor organization in the last 24 hours.  The leader sometimes has questions about engagements that the requestor can't answer without the information in the text data field.  Currently the requestor must go back to ANET to find the answers after briefing the leader (instead of being able to answer the leader's questions during the briefing).

**Comment by VassilIordanov** [comment]
Unfortunately it is not possible to have rich text in Excel. We could convert the content to plain text, but this almost never work well.
One possible alternative is to have a PDF export. Created issue #1325
