### ISSUE TITLE
Assign one or more advisor positions as responsible for task change management

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1247]
A task has one or more people that decide if a task is complete or still "open."  The person is also responsible for suggesting changes to the task description.  This person should be fielding all the questions and problems with their assigned tasks from report authors/advisors.

However, in reality, the requirements owners must initially field questions on individual tasks. The report authors should be able to directly contact the person(s) responsible for the task.

The person(s) responsible for the task(s) should also be able to know when a completed task is still being used.

**Comment by VassilIordanov** [comment]
I suggest:
- Add an association between positions and tasks (many-to-many). This is to indicate who is responsible for a task and can edit it.
- We want to keep associations between tasks and orgs ( ideally many-to-many). This is to indicate which tasks are likely to be used by that org.
- When a new task is created, associate it by default with the position of the author and the org of the author (both can be removable)
- When migrating db, associate superusers of orgs with the existing tasks of that org


Add a many-to-many relationship between

**Comment by maradragan** [comment]
From @VassilIordanov:
Initially, I was thinking that tasks should be assigned to positions – hence the ability to edit them. Another option is to remove the concept of super users and admins, but instead to give users the following permissions”
o   Permission to create/edit tasks of own org and its children
o   Permission to create/edit tasks of all orgs
o   Permission to create/edit own org (or org of my counterpart) and its children
o   Permission to create/edit all orgs
o   Permission to create/edit positions in own org (or org of my counterpart) and its children
o   Permission to create/edit positions in all orgs
o   Permission to create/edit people in org of my counterpart and its children
o   Permission to create/edit all people

Obviously the above is an intrusive change. What do you think? Maybe we can start small, by keeping the existing system and adding just the permission to edit tasks.

Personally, I am pretty sure I prefer to have tasks assigned to positions and not to introduce permissions. Thought are appreciated.

**Comment by maradragan** [comment]
From @VassilIordanov 
I believe the following will be sufficient:
- leave the current association of task to orgs as is
- add a many-to-many relation between positions and tasks
- add editors for it in both tasks and positions
- Allow only admins and people in positions which have a relation to a task to edit that task.
