### ISSUE TITLE
Change "All EFs / AOs" label on drop-down menu to "Advisor Organizations"

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1269]
The requirements owner is eliminating all references to EFs and PoAMs.

The drop down menu is located on the left-hand column of most ANET pages.

If "Advisor Organizations" is too long for a label maybe use "Advisor Orgs."  The acronym "AOs" is not a common acronym.

**Comment by gjvoosten** [comment]
@dspCarlson On the deployment side, this label is defined in `anet.yml` under `dictionary: fields: advisor: org: allOrgName: All EFs / AOs` so you can simply change that yourself.
We'd still need to update the developer's docs etc.

**Comment by gjvoosten** [comment]
*Advisor Organizations* seems to fit nicely in the navigation menu width, so no need to abbreviate it. I'm updating the docs.
