### ISSUE TITLE
Tooltips for report tags

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#127]
Tags have a description that should be used as a tooltip in any location where a tag is displayed.
In https://github.com/NCI-Agency/anet/issues/17 this is suggested:

> Tooltips should be displayed when clicked or (to support phone usage) or possibly also mouse-over events

**Comment by gjvoosten** [comment]
@dspCarlson Since tooltips for tags will show what's in the description field (currently empty), could you provide descriptions for the 12 default tags that you have now (in staging) so we can add them?

**Comment by dspCarlson** [comment]
@gjvoosten No problem.  I will do it tomorrow.

**Comment by dspCarlson** [comment]
[Key Words with Descriptions.txt](https://github.com/NCI-Agency/anet/files/1337021/Key.Words.with.Descriptions.txt)
@gjvoosten Per your request

**Comment by gjvoosten** [comment]
@dspCalrson Thanks, I've added the descriptions. Should you wish to update your local database with descriptions for the tags, you can use this SQL script.
[updateTags.txt](https://github.com/NCI-Agency/anet/files/1340047/updateTags.txt)

**Comment by dspCarlson** [comment]
@gjvoosten Was the tool tip ever implemented?  Once a tag is selected for a report, the description is not displayed as a tool tip anywhere the tag is displayed.

**Comment by gjvoosten** [comment]
@dspCarlson The tooltip is displayed only when you *click* on a tag.
