### ISSUE TITLE
Suggestions for report tags

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#128]
The suggestions shown for tags currently do a simple string match in the complete list of tags.
In https://github.com/NCI-Agency/anet/issues/17 this is suggested:

> Frequently used keywords to be suggested to user.

**Comment by VassilIordanov** [comment]
Suggestions (as in ANET suggestions like implemented for People, Places, etc) should come from two sources:
* Tags with a match in the entered text so far in other fields
* Frequently used tags by the user

**Comment by maradragan** [comment]
Added to #17
