### ISSUE TITLE
Relations between tags

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#129]
Tags are currently a flat list, but it should be possible to have relations between tags.
In https://github.com/NCI-Agency/anet/issues/17 this is suggested:

> Is-a relationship to other keyword(s). Is-a is a directional relationship

**Comment by dspCarlson** [comment]
@gjvoosten No all tags have a relationship with another tag.  But a lot of tags do have relationships.  For example: "Warfighting Functions" has six children, corruption has 12 children, Rule of Law has three children.  It would be great if the relationship between tags was implemented.

**Comment by maradragan** [comment]
Added to #17
