### ISSUE TITLE
Limit the Meeting goal, Key outcomes and Next steps data fields to 250 characters

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1299]
The requirements owner has noted that report authors are entering all their engagement information/details into these three fields even if the characters exceed 250 characters (for each data field).  The requirements owner wants report authors to use the "Report text" data field.

The database allows 2 GB (nvarchar(max) to be stored in each field.

The 250 character counter on each data field displays negative digits when 250 characters are exceeded.

**Comment by VassilIordanov** [comment]
Brad, I suggest to hard limit to 350 but still show the visual target of 250. The reason is to not cut people off while finishing a sentence. Would that work for you?

**Comment by dspCarlson** [comment]
@VassilIordanov The character limit and counter should be consistent.  250 characters when in reality it's 350 characters is too confusing for report authors.  Plus report authors copy and paste this data into this field.  250 characters or 350 characters, please make the character limit and character the same.

**Comment by VassilIordanov** [comment]
Ok, let's make the limit the same as the visual cue. Could we also have this limit configurable from anet.yml? it can be the same for all fields that have that limit.

**Comment by dspCarlson** [comment]
@VassilIordanov That's a great idea to make the limits configurable from anet.yml.
