### ISSUE TITLE
When creating a new advisor ANET profile, verify the end of tour date is not in the past

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1367]
A user create a profile on 12 February 2019 and set his end of tour date to 1 February 2019.

This rule does not apply when editing an existing advisor profile.

This rule does not apply to principals.

**Comment by VassilIordanov** [comment]
Requirement change: This rule should only apply when a person is entering his/her own info while onboarding. When someone (superuser or admin) is creating a Person, there are some cases when the EOT can be in the past - when recoding an engagement that has happened long ago.
I suggest:
When onboarding: EOT should be in the future
Anytime else - warning message

**Comment by VassilIordanov** [comment]
@evdhoudt could you take another look?

**Comment by evdhoudt** [comment]
@VassilIordanov picking it up today.
