### ISSUE TITLE
Add tags to Report UI parts 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#137]
Wherever reports are showed in a condensed/summary form - search results, rollups, my reports, etc - the list of tags should be included unless it is empty.
This applies to the JS HMI, as well as the rollup email content generated on the server side.

**Comment by maradragan** [comment]
Should the tags also be added to the e-mail content of the approval needed e-mail?

**Comment by maradragan** [comment]
I also added the tags to the content of the approval needed e-mail, as this e-mail also contains lots of details about the report.
