### ISSUE TITLE
Dashboard to display the priorities and the associated efforts

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1430]
- [x] Provide kanban-style dashboard that displaying groupings of tasks 
- [x] Add statistics on groupings based on task's status
- [x] Persist dashboard definition in external json files
- [x] Add statistics on reports withing each group's tasks (requires graphql improvements)
- [ ] Add an editor of dashboard definitions
- [ ] Add ability to persist dashboard definitions in database

**Comment by maradragan** [comment]
This issue needs some refinement:
- what do you mean with senior leaders?
- what are priorities (which information do we need to persist abut it?)? Is it something related to a person, or to a position?
- who and how does the selection of the people being able to change the red/amber/green status of an effort?

**Comment by dspCarlson** [comment]
@maradragan Currently three senior leaders want dashboards of their priorities and related efforts.  One senior leader is the commanding general.  The other two senior leaders are directly underneath the commanding general.  The two subordinates are in charge of evaluating the Ministry of Interior and Ministry of Defense respectively.

Each senior leader has their own priorities.  The priorities among the three leaders are not the same.  Each of their priorities is tied to one or more efforts (formerly known as tasks).  I don't know if @VassilIordanov wants to associates priorities with people or positions.  I would guess positions.

One or two staff members for each senior leader will be able to change the color of an effort.  With each change of color, the staff member will have to provide justification for the color change.

**Comment by dspCarlson** [comment]
@midmarch @gjvoosten @cemalettin-simsoft 

I am closing this issue.

The functionality is no longer required.  All of the stake holders are long gone.
