### ISSUE TITLE
Tracking reasons for requesting changes

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1431]
Engagement reports can be returned to the report author for one or more reasons.

Each day the requirements owners count the reasons why reports were returned to the report authors.  

All six report reviewers update a master Excel spreadsheet daily.

The requirements owners want ANET to tabulate why reports are being returned to the report author for changes.

The results for approvers who return reports for changes should also be included.

**Comment by maradragan** [comment]
@dspCarlson Do you mean that ANET should provide an spreadsheet containing the requested changes for all engagement reports within ANET?

- Maybe we should provide a link which downloads the spreadsheet? 
- If so, who should be able to download the spreadsheet and where should we place the link, on the dashboard?
- Which information should we provide? Report link, report id, approver, reason?
- I don't understand what you mean with: "The results for approvers who return reports for changes should also be included."

**Comment by dspCarlson** [comment]
@maradragan When report approvers, including the administrators, request changes, they will be able to choose one or more reasons why the engagement report was returned to the report author.  This one-to-many relationship (one report to one or more reasons for request changes) will require a database change.  This change will require a GUI change for administrators/report approvers.

I don't think we need to worry about outputs (e.g. spreadsheets) yet.

Question:
I don't understand what you mean with: "The results for approvers who return reports for changes should also be included."

Answer:
Currently, only the request for changes are being tabulated by the administrators in Excel spreadsheets.  But the administrators want to also tabulate report approvers and the request for changes they make.  The administrators are going to do analytics on why reports are returned for changes for all ANET report approvers.

**Comment by maradragan** [comment]
It is probably related to the implementation of #1574

**Comment by dspCarlson** [comment]
@maradragan The requirements owners were really hot about this issue a month ago.  Now they haven't asked about the progress of this issue.  There are are about 10 reasons why reports are returned ("request changes") to report authors for edits.  Instead of writing out the reasons each time, the report approvers and administrators reviewing reports should be able to just check reasons.  For example, one reason for returning a report is the principals mentioned in the "Engagement details" are not assigned to the report in the "Attendees" data field.  Report authors can't find the principal engagement attendees in ANET so they will add anyone or the report author is simply lazy and doesn't try to find the principal attendees.

**Comment by dspCarlson** [comment]
This issue is OBE.  The requirements owner is long gone.
