### ISSUE TITLE
Saving a principal position with a duplicate code doesn't allow further saving attempts

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1468]
Condition:
1. Edit an existing principal position
2. Change the code to a code that already exists in the database
3. Click the "Save position" button; Result: Pink error message is displayed and both "Save position" buttons are disabled
4. Change the code to a code that doesn't exist in the database; both "Save position" buttons are still disabled
5. Move the focus to other data fields on the page; both "Save position" buttons are still disabled

There is no way to save a principal position after trying to initially save a position with a duplicate code.

The workaround is to select the "Cancel" button and start over.

**Comment by gjvoosten** [comment]
Seems to be related to https://github.com/jaredpalmer/formik/issues/739
Similar problem happens when e.g. trying to save an organization with itself as a parent: you get an error message and the save button stays disabled. In the form's Javascript code, `isSubmitting` stays `true`.
