### ISSUE TITLE
Advanced Search Displays Principal Organizations When Searching for an Advisor Position

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#148]
When using advanced search to find an advisor position, the "Organization" search box returns principal organizations as well as advisor organizations.
Reference item 84

**Comment by gjvoosten** [comment]
Comments by @dspCarlson from #184:

> The converse for this is also true.  When using advanced search to find a principal position, the organization search box displays advisor organizations.
> 
> The sequence to recreate this is:
> 
> 1. Select advanced search
> 2. Select positions
> 3. Select position type as a filter
> 4. Select principal as the position type 
> 5. Select organization as a filter type
> 6. Type in a generic word for the organization
> 7. Both principal organizations (correct) and advisor organizations (incorrect) are displayed in the list
