### ISSUE TITLE
Review behavior of search text indexing and ordering

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1497]
Can we discuss the following:

Report
- summary *
- UUID
- attendees names
- notes ?

Person
- name *
- UUID
- position name
- position post number
- domain unsername
- email
- phone
- bio
- notes ?

Position
- name
- UUID
- post number
- person's name
- names of previous people in that positions
- the rest of a person's attributes?
- notes ?

Task
- short name
- long name
- UUID
- notes ?

**Comment by VassilIordanov** [comment]
see also #544

**Comment by VassilIordanov** [comment]
@dspCarlson is also reminding that it is not possible to search/autosuggest by position's code (tashkil)

**Comment by dspCarlson** [comment]
When searching by principal position code, entering the UIC, should only return principal positions with that UIC.  

Entering a hyphen and then a paragraph number should only return principal positions with the UIC and paragraph number.

**Comment by maradragan** [comment]
Added to #1969
