### ISSUE TITLE
Users should get an overview of possible tags from which to choose from

### ISSUE THREAD

**Issue by evdhoudt** [NCI-Agency/anet#152]
The overview should show a searchable overview of possible tags from which the user can choose from before adding the tag to a document. 

~~If the preferred tag is not in the list, the user should then be able to add a new tag.~~

==> decoration for tags
*  X for deletion
* maybe drag and drop option

**Comment by VassilIordanov** [comment]
@evdhoudt , we do need a tag selection widget. It should provide:
- a hierarchical way to browse tags
- it should show the description of the tag under selection
- if a tag is not in the list, the user should _not_ be able to add a new tag

**Comment by evdhoudt** [comment]
Comments from ANET advisor training:
* Tags are perceived to be of great value for adding meta data to reports
* Properly tagged reports make them easier to be found and tracked
*

**Comment by VassilIordanov** [comment]
can we use the (further customized new autosuggest) for this?

**Comment by maradragan** [comment]
Added to #17
