### ISSUE TITLE
Assess task when changing its status

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1524]
From @VassilIordanov : 
The concept of task assessments/notes entered every time a status of a task is changed. We discussed this one before a bit. I think a good option may be a mechanism that uses notes to:
·         Force that a note is entered when some event happens – i.e. changing a field
·         Attach a history event to the note – showing that a field changed from state 1 to state 2. I am not sure if the history event should have a life on its own or be a special  kind of note, but that’s probably an implementation detail.

This sounds suspiciously like report approvals/comments/etc. How would we do it if we had to do it again?

**Comment by maradragan** [comment]
Closing this issue, we keep #1574 .
