### ISSUE TITLE
Add time and duration to engagements

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1559]
Add optional field(s) to define when an engagement is starting and how long it is.

if field(s) defined in anet.yml - use it in UI
field should define starting time and duration/end time

**Comment by gjvoosten** [comment]
In the database schema, `reports.engagementDate` already has the possibility to store the (start) time. An additional field is needed, either for the end date/time, or for the duration. Duration is probably easier, so an extra database field `reports.duration` of type `int` (duration in minutes) is needed. If and when the `anet.yml` specifies that engagements need a time, add the ability to pick a time and a duration.
