### ISSUE TITLE
Report showing who is the next person(s) to approve a report

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#156]
Super users have reported that whilst they know that there are reports in their org still pending approval, it is difficult to identify which reports and who the report is waiting for approval from. 
## Essential Features:
* Must show visually to a super user all the reports in their organisation that are pending approval and who they are sat with.

## Example
on request

## Relations to other features
Similar to #39 and #20

**Comment by evdhoudt** [comment]
@VassilIordanov I've pushed my implementation to branch GH-156. Could you please let me know if the implementation at this moment is to your liking? Below I've

* At the moment Super users have an extra button to filter on Pending reports in My organization > reports
* To visualise at which step the report is pending, I've currently used an existing piece of UI, that can be found in a full Report (show.js)
* It is obviously not the same as the example you showed us, however I'm not sure how to elegantly implement the horizontal line and incorporate all the relevant steps and the approvers that are involved with the pending approval step.
* At least now superusers can quickly filter all organisation reports by the ones that are pending and see at which approval step the report is halted.
* Is is ok to create a pull-request, or does the visualisation need to fit the example before we push it to the users?

**Comment by VassilIordanov** [comment]
@evdhoudt 
Cool, I like it :). A few comments:

Maybe we can do some styling to make it look more like a process. Some examples I fiddled with with styling in the browser debugger: 
![image](https://user-images.githubusercontent.com/16674032/30546038-c4ddd468-9c8b-11e7-8872-815c18998d91.png)

**Comment by evdhoudt** [comment]
Agreed, I also like the vertical flow best, seems to fit many different scenario's. I'll start with refactoring the suggestions.

**Comment by VassilIordanov** [comment]
Or we could add another line to make it more clear and compact horizontally:
![image](https://user-images.githubusercontent.com/16674032/30547466-a6a59810-9c8f-11e7-8eb4-f7e1d3692ab7.png)

(it needs to have better vertical spacing)

**Comment by evdhoudt** [comment]
I still believe the vertical flow is superior for the UI, since it allows most room for many approval steps and approvers with long names. 

If most reports only have a max of 3/4 approval steps, then the horizontal flow might work. However when that isn't the case, it could look jumbled.

**Comment by VassilIordanov** [comment]
![image](https://user-images.githubusercontent.com/16674032/30547925-fdff367e-9c90-11e7-898a-efbd9cf528bf.png)

My concern other with a vertical flow is that it takes vertical space if we put it in the header. We want to keep most vertical realestate for the reprot itself.
I suggest we play with the style to make it as compact as possible in both directions. I think if we make small fonts we can get to 5/6 steps. If in the future we have orgs with many steps, we can then show the last 5 of them and provide a "more" button

**Comment by VassilIordanov** [comment]
I would have an even more vertically compressed view, for places like a summary, with only the line of the step/status and the rest of the information available in tooltips

**Comment by evdhoudt** [comment]
@VassilIordanov I've pushed an updated version to the branch. 
* There is a compact view in the Report summaries and a more detailed view in the Report itself
* Instead of a tooltip I've added the approval step details to the pop-up Modal for consistency
* Instead of a line between the processes I've added an Arrow to indicate the direction of the proces :)

If your happy, I'll make a pull request.

**Comment by VassilIordanov** [comment]
@evdhoudt Edwin, I have the following in my dev set-up
![image](https://user-images.githubusercontent.com/16674032/30593589-60fa1b76-9d4b-11e7-9c0f-929f3bca436f.png)
A few notes:
- the color is green for both rejected and approved. I recommend to make the step colorless, and make the green/red/gray background of the APPROVED/REJECTED/PENDING text
- I think the most clear vertical order (to me) is:

APPROVED
    (STEP)       ->
 by reviewer
   on date

- I like the arrow :+1:

**Comment by evdhoudt** [comment]
@VassilIordanov Strange, it should look like this. I'll reformat the approval steps 👍 
![screen shot 2017-09-19 at 15 09 09](https://user-images.githubusercontent.com/4208203/30593933-89f165ec-9d4c-11e7-9ec8-fd3f7f1b57e9.png)

**Comment by VassilIordanov** [comment]
regarding the condensed view in the summary...
![image](https://user-images.githubusercontent.com/16674032/30593828-37e809ea-9d4c-11e7-948c-e38d038f21ff.png)
- We should remove the Approval Status title, it is not needed there
- Also good to remove the Approved And Rejected text
- I suggest to have a single line with the steps and colors combined (the way it is now, assuming the rejected state is red). That line should be as close up to pending approval line

**Comment by VassilIordanov** [comment]
@evdhoudt pending should not be red, rejected should be red. remember, there are 3 states. I suggest gray or blue for pending (for now...)

**Comment by VassilIordanov** [comment]
Also, can you make the buttons rounder to appear as process steps? I suggest rounded corners of 30px

**Comment by evdhoudt** [comment]
@VassilIordanov If we want the approval steps coloured in the summary view, shouldn't we keep the colours the same in the Report view? It could be confusing when the steps suddenly change colour.

**Comment by VassilIordanov** [comment]
@evdhoudt It should be same colors in both - green, gray and red

**Comment by evdhoudt** [comment]
See screenshot :) i've made an example in blue, so the pending state fits the blue report flag. What do you think?

![screen shot 2017-09-19 at 15 09 09](https://user-images.githubusercontent.com/4208203/30596237-d2304c2c-9d53-11e7-9021-abf3025d7d6a.png)
