### ISSUE TITLE
Copying and pasting into three data fields deletes the existing text

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1567]
Yesterday a user notified me that he had lost all the text in the "Engagement details" data field when he pasted from Microsoft Word.

Today, I was able to recreate the bug in the biography, engagement details and sensitive information data fields.

I was not able to recreate the bug in the meeting goal, key outcomes and next steps data fields.

**Comment by dspCarlson** [comment]
I merged this issue with #1114

**Comment by evdhoudt** [comment]
@dspCarlson I do not believe this is the same bug. GH-1114 is confined to IE11, while I have the same issue on my machine with this issue.
