### ISSUE TITLE
Report number of cancelled engagements

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#157]
This is to show how many engagements are cancelled and the reasons why. 
## Essential Features:
* Must have one graph that shows all the engagements cancelled by organisation.
* Must have separate graphs that show the engagements cancelled by reason;
## Important:
* The time frame  should be adjustable; last week, last month etc
## Desired Features:
* Sortable by organisation, author, PoAM, workstrand, principal location.
* Add a feature to the ANET engagement report that gives the time of day an engagement occurred. Then allow the cancelled engagements be able to be sorted by time; AM or PM.
## Example
on request

**Comment by gjvoosten** [comment]
Like https://github.com/NCI-Agency/anet/issues/155, this report is available for super users and administrators.
