### ISSUE TITLE
Super users cannot edit the profile of other super users

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1571]
When a super user tries to edit the advisor position of another super user, the following pink message is displayed:

"Forbidden: Exception while fetching data (/updatePosition): You do not have permissions to do this."

Both super users were assigned to the same advisor organization.

The work around is to select the "ANET User" button for the super user profile being selected.  This makes the edited super user no longer a super user, but at least the position can be edited.

**Comment by maradragan** [comment]
Added to epic #2191

**Comment by maradragan** [comment]
Discussed this with @dspCarlson and he told me that:
- super users need to change the location, position name or billet number of another super user (within their organization or in a subordinate organization).
- but, super users don't change privileges from super user to user when another advisor redeploys.  They just don't do it.  Its not an intuitive action.  Super users are overwhelmed with other duties.

Therefore we need to make sure they are allowed to change a super user position as long as it is within their organization or in a subordinate organization. But super users shouldn't be able to upgrade a user position to a super user position.
