### ISSUE TITLE
Report the number of engagement reports submitted within a given time frame

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#158]
Show how many reports are submitted on what day over a time frame to give an idea of activity patterns.
## Essential:
* Must show on a line graph, broken down by day
* Must be able to edit the time samples.
## Desirable:
* Sortable by organisation, author, PoAM, Workstrand, Principal location.
## Examples
![image](https://user-images.githubusercontent.com/16674032/29820504-f8dd637c-8cc4-11e7-846a-3f895de6f0a3.png)

**Comment by maradragan** [comment]
We aggreed we will make a bar chart instead of a line chart.

**Comment by maradragan** [comment]
Should I use the releasedAt property in order to filter the reports within the period?
And also, should I group on the same releasedAt property in order to split the reports per day of the week?
