### ISSUE TITLE
Reorder Tasks in report summary 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#16]
Insert the report PoAM(s) below the advisor and principal and above the Atmospherics on the summary reports in ANET. 
Reference item 3

**Comment by VassilIordanov** [comment]
I do not think this is still a valid requirement. @dspCarlson  please re-open if it is still valid

**Comment by dspCarlson** [comment]
@VassilIordanov Yes, this issue can stay closed.  Haven't received any feedback on this issue in a long time.
