### ISSUE TITLE
Report engagement reports by PoAM or Workstrand

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#160]
A report that shows what engagement reports have been submitted over a given organised by PoaM or Workstrand. 
## Essential:
* Report that shows this on a graph.
## Important:
* A way to click through to view the reports attributed to each PoaM or Workstrand, much like on the daily roll up graph.
* Needs to be able to be sorted by timeframe.

**Comment by maradragan** [comment]
We need to know which reports to use for the insight.
- Should we use only reports having a certain state?
- Should we also consider a reference date like we do with not approved reports and cancelled reports?

For the insight showing reports per PoAM:
- Is it ok to make a bar chart with PoAM's on the x-axis and number of reports as y-value?
- Should we show all PoAM's on the x-axis or do we first only show the top ones and than on click on a PoAM we get a bar chart with the next level of PoAM's having the clicked one as parent and so further?

What do you mean with "Needs to be able to be sorted by timeframe."?

**Comment by maradragan** [comment]
What does workstrand mean within ANET?

**Comment by maradragan** [comment]
What do we do with reports which don't have any PoAMs? Do we add a bar in the chart  labeled No PoAM?

**Comment by VassilIordanov** [comment]
@maradragan why I have no all answers at this point, I suggest to start with:
- only deal with published reports
- allow to show reports in a time range
- bar chart as suggested is a good start
- yes, we can have a no poam category
