### ISSUE TITLE
Close advanced search overlay on blur

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1636]
When clicking outside the advanced search overlay, close it.

**Comment by VassilIordanov** [comment]
The fix for this issue prevents the date picker from working

**Comment by maradragan** [comment]
This happens because the datepicker we use is creating a div for each date input field _outside the advanced search overlay div_. That way, when we click on the date overlay we are actually clicking outside the advanced search overlay. And by setting rootClose on the advanced search overlay, we actually say close the overlay on any click outside the overlay. The date overlays are outside the search overlay and this is why when we click on them the advanced search overlay gets closed.
