### ISSUE TITLE
nbOfHoursQuarantineApproved inconsistency

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1641]
After setting nbOfHoursQuarantineApproved to 1, and then approving a report, viewing the report states that it will be published in a day. Without having looked into details, I assume this is due to the level of granularity of the remaining time period. We should drop it down to a more specific value as "a day" is misleading when it should be an hour

**Comment by gjvoosten** [comment]
The real issue is that is uses a hard-coded `24` instead of `Settings.reportWorkflow.nbOfHoursQuarantineApproved`. Easy to fix.
