### ISSUE TITLE
Actions tests are sometimes failing

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1642]
I sometimes get the following error while running the actions tests:
 PASS  tests/reducers/pagination.test.js
 FAIL  tests/actions/index.test.js
  ● Test suite failed to run

    TypeError: path must be a string or Buffer

      4 | 
      5 | console.log("Using configuration file " + process.argv[2])
    > 6 | const anetConfig = jsyaml.safeLoad(fs.readFileSync(process.argv[2], "utf8"))
        |                                       ^
      7 | const Settings = anetConfig.dictionary
      8 | const API = BaseAPI
      9 | 

      at Object.readFileSync (platform/node/api.js:6:39)
      at Object.<anonymous> (src/actions/index.js:1:1)

If I run the tests again, they succeed.

**Comment by evdhoudt** [comment]
Do you have this issue when running `yarn test-jest` or with `yarn jest`? With the latter I also get the same issues, however this is not the preferred route to run jest tests. At the moment jest should only be used to test the actions and reducers. `yarn test-jest` configures the runner with the correct settings.

**Comment by maradragan** [comment]
I have it when doing `yarn run test-all`.

**Comment by maradragan** [comment]
From @gjvoosten 
The error goes away after:

```% rm -rf node_modules/ ; touch package.json ; yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
warning " > eslint-config-react-app@3.0.8" has incorrect peer dependency "babel-eslint@9.x".
warning " > eslint-config-react-app@3.0.8" has incorrect peer dependency "eslint-plugin-flowtype@2.x".
[4/4] Building fresh packages...
Done in 180.88s.

% yarn run test-jest
yarn run v1.15.2
$ jest ../anet.yml --testPathPattern='tests/(actions|reducers)'
 PASS  tests/reducers/pagination.test.js
 PASS  tests/actions/index.test.js
  ● Console

    console.log platform/node/api.js:5
      Using configuration file ../anet.yml


Test Suites: 2 passed, 2 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        1.185s
Ran all test suites matching /..\/anet.yml|tests\/(actions|reducers)/i.

Done in 2.34s.```

This leads me to believe it is some kind of caching problem (perhaps something from a previous branch before switching to this one), although which particular cached item is the culprit is a mystery to me. (edited)
