### ISSUE TITLE
Optional chaining not working

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1662]
`@babel/plugin-proposal-optional-chaining` does not seem to be working.
As it is quite handy and would make the code more readable in many places, we should fix it.

**Comment by VassilIordanov** [comment]
Optional chaining is working, but VS Code does not seem to pick it up

**Comment by jose-west** [comment]
This issue arises because VSCode uses Typescript to check JS files by default. If you are using another lint (e.g. I am using Prettier), you can turn off the default lint adding "javascript.validate.enable": false" to settings.json.

**Comment by maradragan** [comment]
From @gjvoosten:

My top-level jsconfig.json reads like this, and with this, VS Code picks up all configuration from package.json etc. No need for extra settings I believe.

```
{
    "compilerOptions": {
        "baseUrl": "client/src/",
        "experimentalDecorators": true
    }
}
```
