### ISSUE TITLE
Provide a sensible default, stable ordering on Search (incl. Saved and Advanced) for all object types

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#171]
When testing #15 , organization names are not returned alphabetically on saved searches.  It forces the user to possibly tab through each page to find the organization they are looking for.  For example, 45 organizations were returned from a saved search.  Alphabetically the organization I was looking for should have been on page 1, but appeared on page 4.

Reference item 89

**Comment by gjvoosten** [comment]
It's not strictly an issue with Saved Searches: the default sort order for Organizations (from a Search and from an Advanced Search, thus also from a Saved Search) is on `createdAt DESC` which may not be ideal.
For the other object types, the (default) sort orders are:

- Reports: `engagementDate DESC`
- People: `name ASC`
- Positions: `name ASC`
- Locations: `name ASC`
- PoAMs: `shortName ASC`

which all seem to be OK. So only the (default) sort order for Organizations from needs to change, to `shortName ASC`.

I will update the issue title accordingly.

**Comment by gjvoosten** [comment]
To make this issue more generic (and include #172), we should provide a sensible default, stable ordering on Search (incl. Saved and Advanced) for all object types.
Note: _stable_ means that we must include a field with guaranteed unique values in the `order by` clauses. In general this means we should add an ordering on the `id` field at the end. Proposed default ordering:

- Reports: `engagementDate DESC, id DESC`
- People: `name ASC, id ASC`
- Organizations: `shortName ASC, longName ASC, id ASC`
- Positions: `name ASC, id ASC`
- Locations: `name ASC, id ASC`
- PoAMs: `shortName ASC, longName ASC, id ASC`
