### ISSUE TITLE
Search for Action and Milestone should sort on shortName, longName

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#172]
When testing #15 , actions and milestones are sorted on the number (shortName), but not on the description (longName).  Theoretically the number should be unique and there should only be a primary sort on the number.  But numbers are not unique.  There are 152 (active) numbers that are duplicated.  The saved search results are not intuitive.

Reference item 172

**Comment by gjvoosten** [comment]
As I wrote in https://github.com/NCI-Agency/anet/issues/171, searches for PoAMs are sorted on `shortName ASC`. As the `shortName` is not unique, at least an additional secondary sorting criterion is needed.
So the sort order should become `shortName ASC, longName ASC`.

**Comment by gjvoosten** [comment]
Covered by the (now) more generic #171.
