### ISSUE TITLE
Domain User Name Not Saved for New Profiles in Staging

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#173]
I set my domain user name to NULL in the staging database and log into the program.  The "Welcome" onboarding page is displayed.  I select the "Create your account" button and the onboarding/edit page is displayed.  I enter all the information to create a new profile.  I select the "Create profile" button.  The onboarding page is displayed again asking me to create a new profile.  In the database my profile is created but without a domain user name.
I have updated the staging database since the last update on 21 September at 1955.

Reference item 91

**Comment by VassilIordanov** [comment]
I confirm that I experience the same. I was sitting next to a new user creating an account on the staging server, and the onboarding page kept coming up.

**Comment by VassilIordanov** [comment]
problem is not related to AD - steps to reproduce in the development environment:
- open a browser in incognito mode and load ANET
- when prompted for username/password enter a username that does not exist, and use the same string as the password - this creates a new account
- fill the onboarding
- onboarding keeps coming up

**Comment by gjvoosten** [comment]
Difficult to find, but should be fixed with PR #182
