### ISSUE TITLE
Epic 1705: Make the daily rollup a regular report search

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1733]
The daily rollup should use a regular report search query. This also means that it can just use the report search filters.
Part of #1705

**Comment by gjvoosten** [comment]
The rollup query currently returns something like:
```
{
	"data": {
		"rollupGraph": [
			{
				"org": {
					"uuid": "8824e2df-e3b4-46a7-ac31-d98bed31ae5c",
					"shortName": "EF 1"
				},
				"published": 2,
				"cancelled": 0
			},
			{
				"org": {
					"uuid": "b24f99af-2827-4c17-a39d-1f150552af72",
					"shortName": "EF 2"
				},
				"published": 10,
				"cancelled": 1
			},
			…etc…
		]
	}
}
```
i.e. aggregated numbers (count). Having the search return aggregated numbers will be difficult.

We might use reports search to return the _list_ of (published or cancelled) reports for _each_ top-level organisation (including children), and that could even use batching, but that would mean the client-side would have to do the aggregation (count). In addition to that, getting this all at once for _all_ top-level organisations is not so simple, either.
