### ISSUE TITLE
Use engagement state colours consistently

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1757]
In different parts of ANET we use colours to represent the state of an engagement: 
- [x] in the summary view of reports, in front of the state name
- [x] in the calendar view of reports
- [x] in the daily rollup
- [x] in the report workflow
~- [ ] in the insights~

Right now the colours are not being used consistently.
We should agree on which colour we should use for which state. The states to be used are:
- DRAFT
- PENDING_APPROVAL
- REJECTED
- APPROVED
- CANCELLED
- PUBLISHED
- FUTURE (not really a state, but dependent on the engagement date)

**Comment by midmarch** [comment]
We decided not to implement the color scheme to the "insights". Therefor this issue is done.
