### ISSUE TITLE
Epic 1704: Detect planning conflicts

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1839]
When rendering a report we can do the following:

- run a query like the one below to determine if the attendees are included in other meetings with potential conflicts
```
{
  report(uuid:...)
  {
    uuid
    attendees {
      attendedReports(query:{engagementDateStart:...., engagementDateEnd:...})
       {
        list
        { 
          uuid
        }
       }
    }
  }
}
``` 
- give a visual queue for the attendees with conflict
- provide a way for the user to discover what is the conflicting engagement(s)

Part of #1704 epic

**Comment by oayvazoglusim** [comment]
Hi @VassilIordanov , 

I need additional information and want to ask some more questions  ; 

1. As far as I understand, this check / warning is not required when creating a new report.
I understand that warnings about conflicts are required to be shown on the "My Reports" page. 
Is it correct ?

2. What exactly does a visual quee mean, can you be a little more descriptive?

         For example, is one of the following examples appropriate for this or something different?

         - For example ; A separate calendar component section can be added to the "My Reports" page, and conflicting meetings of those concerned, if any, can be displayed on this component.

         - Or ; Should a new field showing this conflict be added to the "Meeting participants" section that appears when the "Read report" link is clicked?

**Comment by VassilIordanov** [comment]
I think this is best done on the page of a `Report`.
When Editing/Creating a new report, we could:
- display an explicit warning message next to the date, like: "2 of the attendees are busy at this date/time" or "Mr Jones is busy at the selected time"
When Editing/Creating/Viewing a new report, we could:
- display the attendees that are "busy" - i.e. have another engagement at the same time - differently, with some kind of decorator (icon, different border / backgound) indicating that the person is busy

As a step 2: 
When Viewing a report elsewhere (calendar/map/etc), we could:
- display that the report has a conflict - (icon, different border / backgound) indicating that the report has a conflict
- display the attendees that are "busy" - i.e. have another engagement at the same time - differently, with some kind of decorator (icon, different border / backgound) indicating that the person is busy
