### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [NCI-Agency/anet#1874]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/NCI-Agency/anet/blob/candidate/client/package.json#L65

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by VassilIordanov** [comment]
Good point @DanielRuf , thanks
