### ISSUE TITLE
Error message displayed when saving an advisor organization

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1888]
When clicking the "Save Organization" button for an advisor organization, the following red error message is displayed:

Internal Server Error: Exception while fetching data (/updateOrganization) : failed to load Approvers

This error message is displayed even if there were not any changes made to the advisor organization.

Another error message that is displayed a second time when trying to save the organization is:
Internal Server Error: Exception while fetching data (/updateOrganization) : org.jdbi.v3.core.transaction. Unable ToManipulateTransactionIsolationLevelException [sic]: unable to access current setting

**Comment by maradragan** [comment]
I suppose this was also due to the "connection lost exception" @Vassil mentioned (see #1891).
@dspCarlson can you please confirm it is working now?

**Comment by dspCarlson** [comment]
@maradragan Yes, I can confirm advisor organizations can be successfully saved without error messages.
