### ISSUE TITLE
Report approver receiving an error message when trying to approve reports

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1889]
The message is:

Internal Server Error: Exception while fetching data (/approveReport): failed to load ApprovalStep. 

The report approver's advisor position was added as a report approver today.

**Comment by maradragan** [comment]
I suppose this was also due to All these are related to a connection lost exception. Looking into this (see also #1891).
@dspCarlson can you please confirm it is working now?

**Comment by maradragan** [comment]
The related issue #1891 was also closed, so I guess this one is also not an issue any more. I therefore close it.
