### ISSUE TITLE
Report approval not working

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1891]
A report approver is trying to approve a report.

Every time he clicks the "Approve" button, it records the action in the reportActions table.  However, the approvalStepUuid column in the reports table does not move to the next approval step.

I am guessing this bug probably has something to do with GHs #1886 , #1888 and #1889

**Comment by VassilIordanov** [comment]
All these are related to a connection lost exception. Looking into this

**Comment by maradragan** [comment]
@dspCarlson Can you please confirm it is working again?

**Comment by dspCarlson** [comment]
@maradragan Users have not contacted me about this bug in two weeks.
