### ISSUE TITLE
Report Sort Order Changes between "Summary" and "Table" Views

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#19]
When moving through the pages of reports and clicking between the "Summary" and "Table" views, ANET does not always list the reports in the same sort order.  This makes it difficult for the user to extract anything out of the system in an organized manner.
Reference item 6

**Comment by evdhoudt** [comment]
@VassilIordanov, I cannot reproduce the issue, even with extra reports imported by the data generator.

Thereby, the sql query ReportList in ReportDao.java retrieves a report list that is sorted by 'created_at' and I don't see any evidence of graphql changing the sorting order anywhere else.

Could you provide more details as to when this issue occurs?

**Comment by VassilIordanov** [comment]
@dspCarlson - can you reproduce this in production. If yes, what are the steps?

**Comment by VassilIordanov** [comment]
not reproducible in the latest code

**Comment by dspCarlson** [comment]
@evdhoudt I apologize for not responding for information on this issue.  I am still not very good at GH but recently found the "Mentioned" function where I noticed your request.

**Comment by dspCarlson** [comment]
@evdhoudt I tried to recreate this bug today.  I checked 40 search results (out of 122) of reports.  The reports were in the correct order between "Summary" and "Table" search results.  So this is no longer a bug.

This bug originally came to my attention on 7 April 2017 when a user brought it to my attention.  At the time I was able to recreate the bug.

**Comment by evdhoudt** [comment]
@dspCarlson ok great 👍  apparently the system is self-healing :D
