### ISSUE TITLE
An advisor's assignment history does not update when assigning another advisor to the position

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1917]
When I assign an incoming advisor to an advisor position, the outgoing advisor's position history is not updated.

On the position's page, the position's history will display the end date for the advisor.  But on the outgoing advisor's page, the history will not display an end date for the position.

When I checked the peoplePositions table, a NULL personuuid record is inserted for the position.  But a NULL positionuuid is not inserted for the outgoing advisor.

To recreate the bug:

1. Go to an advisor position that currently has an advisor assigned
2. Select the "Change assigned Partner" button
3. Enter another unassigned advisor in the "Select a person" data field
4. Select the "Save" button

**Comment by VassilIordanov** [comment]
Nothing in the error log?

**Comment by maradragan** [comment]
@dspCarlson I can reproduce it, I will try to fix it.
