### ISSUE TITLE
Validate the Email Domain When Saving a Record in the people Table

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#194]
There are currently 71 unique email domains in the emailAddress field.  However, there are only about 10 legitimate email domains.  When saving a record to the people table, verify the email domain is valid.  If the email domain is incorrect, can a message be displayed with a list of the valid email domains?

One of the complaints I receive is that a report approver is not receiving emails to approve reports.  The problem is always the report approver has entered an incorrect email address.  Usually the report approver has entered an incorrect email domain.

Reference item 97

**Comment by VassilIordanov** [comment]
Create a list of valid email domain names in the dictionary (preferably, if possible with wildcards).
Do not allow users to enter email addresses that do not match a domain from the list.

**Comment by dspCarlson** [comment]
@evdhoudt Emailed @VassilIordanov a list of email domains and the count of each email domain.  Will help identify what is a valid email domain.

**Comment by evdhoudt** [comment]
@dspCarlson thanks, I'll ask @VassilIordanov  for the list of domains :)

**Comment by dspCarlson** [comment]
Please change the message email domain name message displayed to administrators and advisors.

1. When an administrator creates a new advisor and enters the first key in the "Email" data field, an invalid error message is immediately displayed.  This is confusing because only the first letter of the email address has been entered and the administrator is already being told the email address is invalid.

2. When editing existing advisor profiles an additional sentence should be added.  In case an advisor's email domain name is not in the list, the advisor should not notify the support team to have the email domain added.

In both cases above the message displayed could be:

_Only the following email domain names are allowed.  If your email domain name is not in the list, please contact the support team at <email address>._

**Comment by evdhoudt** [comment]
@VassilIordanov @dspCarlson is the support team email address linked to the dictionary variable "emailFromAddr"?

**Comment by VassilIordanov** [comment]
I think we need a new entry in the dictionary, `supportEmailAddr` or something like this. I think it is still good to keep it separate from `emailFromAddr`, as that gives the flexibility to either have both the same, or the latter `donotreply@...`

**Comment by dspCarlson** [comment]
After the latest release on staging (21 November), the email domain is now validated when saving the person.  If the email domain is incorrect, a message quickly flashes and then disappears but the person is successfully saved anyway.

**Comment by dspCarlson** [comment]
@evdhoudt @VassilIordanov The emailFromAddr is a do not reply email address so a supportEmailAddr is required.

**Comment by VassilIordanov** [comment]
@dspCarlson correct, the currently deployed version supports 2 different emails - one for donotreply and one for support.

**Comment by evdhoudt** [comment]
As mentioned by @dspCarlson: A user discovered a bug with the email domain name when saving.  She could not save her legitimate email address.  I was able to recreate the bug in staging and environment.  Upon further investigation, only the top email domain name in the dictionary does not save.  The rest of the email domain names can be saved.
