### ISSUE TITLE
Display Reports for a Given Position

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#195]
When viewing an advisor position, list all reports written from advisors that were holding the position at the time.  Leadership wants to be able to put a link into their website.  The link would display all the reports written from advisors who where in the position at the time.

This has high priority.

Reference item 96

**Comment by VassilIordanov** [comment]
We need a way to associate a report with:
- the position of the advisor who has drafter the report
- the positons of the attendees 
- the position of the principal attendee

Once this association is made, The custom search should allow searching reports by position

**Comment by dspCarlson** [comment]
I have a correction/addition.  Since senior leaders do not draft their own reports, the primary advisor attendee's position (i.e. the senior leader's position) should be included, and not just the position of the person who drafted the report.
