### ISSUE TITLE
Text duplicated in the Engagement Details, Sensitive Information and Biography data fields

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1950]
If any text is entered in these three fields, the text is duplicated when the focus leaves the respective data field.

For example:
1. Create a new report
2. Type or copy text into the "Engagement details" data field
3. Click anywhere else on the report with the mouse

Result: the text entered into the "Engagement details" data field is duplicated in the data field.

However, after clicking the "Preview and submit" button, the duplicated text is no longer displayed.  When editing the report after the initial "Preview and submit," the duplicated text is also no longer displayed.

**Comment by maradragan** [comment]
@dspCarlson I can reproduce the issue, we will have a look at it.
