### ISSUE TITLE
Prevent Advisors From Selecting the Local Country

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#198]
When creating or editing a profile, do not allow advisors to select the country where they are working.  Do not give the advisor an opportunity to choose an incorrect nationality.  Changing the label from "Country" to "Nationality" will help guide advisors.  Maybe when saving an advisor profile, verify the nationality is not the local country. Currently there are 87 advisors who have chosen the advising country as their nationality.

Reference item 73

**Comment by VassilIordanov** [comment]
related to #97

**Comment by gjvoosten** [comment]
See #111 for the label change that should already be available in staging.

**Comment by VassilIordanov** [comment]
In addition to the label change, we propose the following functionality.

When a person is an advisor, use the advisor nationality list from the dictionary (no change here)
When a person is a principal, use a principal nationality list from the dictionary (we need to make such a list). If the list has a single country, make sure this country is selected by default in the UI
