### ISSUE TITLE
Report approval process history 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#20]
Reference item 7, 57

During the pending approval process, the approval process history must be displayed. The approval process history includes all previous steps. For each step the following information is displayed:

Step number
Step name
Approver's name who approved the step
Date/Time the the approver approved the step
After a report is released, the entire report history must be available to include the four data items above for every approval step.

old description:
Part 1: When any report is displayed, display it's status at the top of the report.  The are four statuses: Draft, Pending Approval, Released and Cancelled.  A rejected report returned to the advisor is considered in a Draft status even though there is a reject value in the database.  If the report has a Pending Approval status, add the reports current approval step. It will look like this: "Step 1: <approvalSteps.name>".  When building the approval steps, ANET automatically calls them "Step 1" "Step 2" "Step 3" followed the unique user name that is stored in <approvalSteps.name>

**Comment by gjvoosten** [comment]
From #98:
> Met with the customer today about this issue. They still need to know the report approval history after the report has been released (as per the original description). (by @dspCarlson)

> I believe, pending reports display approval history when viewed. I suggest enable the same for released reports. Will that meet the request? (by @VassilIordanov)

**Comment by gjvoosten** [comment]
@dspCarlson After some discussion, the proposal is to show the approval status in the same way as is currently done for pending reports, for all reports not having state `DRAFT` or `FUTURE`. Do you agree?
