### ISSUE TITLE
Change the Data Requirements for Principal Organizations

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#200]
A principal organization needs an official name, colloquial name, unit identifier, parent organization and description.  Super users can only edit the colloquial name and description.  Administrators edit the official name, unit identifier and parent organization.  This is issue is related to #36, #49, and #103.

Reference item 100

**Comment by maradragan** [comment]
We will first only add the UIC field.
The tasks to implement this are:
- field will be unique, not required
- use different labels per organization type (labels come from dictionary)
- migration
- add field to forms and displays
- write tests

**Comment by dspCarlson** [comment]
Super users should only be able to edit a principal organization's name.

Currently super users can edit the parent organization, organization name and official name of a principal organization, but not the identification code.

Only administrator's should be able to edit the parent organization, official name and identification code.  In general, super users do not have the training to know the parent organizations, official names and identification codes.  Most super users don't even know the system of record for these three fields.  As a result, super users will use colloquial names and make up identification codes.  The organization name is for super users to add the principal organization's colloquial name.

**Comment by dspCarlson** [comment]
@VassilIordanov @gjvoosten Can an identification code filter be added to advanced search for principal organizations?  Currently to search on the identification code, the user has to use the "Search term" data field.  It would be more intuitive for the users to have a unique filter.

**Comment by gjvoosten** [comment]
@dspCarlson Created a new issue for the extra search field: https://github.com/NCI-Agency/anet/issues/467
