### ISSUE TITLE
Standardize Names and Encourage the Use of the Organization's Naming Standard

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#201]
Standardize the way names are stored by validating names when saving:

1. Surname: All letters capitalized
2. Given name(s): First letter capitalized; following letters are lower case
3. Name order: Surname followed by given name(s)
4. Name separation: Surname and given names separated by a comma and a space
5. Single names have all letters capitalized

Reference item 101

**Comment by VassilIordanov** [comment]
Discussed with @dspCarlson, the main goal here is to avoid the mess of all different ways of writing names by either suggesting or enforcing a naming convention.
- As first pass we think the first step should be to have help text in the name field (as @maradragan suggested) "LASTNAME Firstname", defined in the dictionary
- As second pass, we think we should do more research about the nature of names, as suggested by @gjvoosten

**Comment by gjvoosten** [comment]
A good starting read is https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by gjvoosten** [comment]
Some examples of different names around the world are given in https://www.w3.org/International/questions/qa-personal-names

**Comment by evdhoudt** [comment]
Basically what W3 says, the only sensible way to store names is to use two fields:
Fullname and (What should we call you?

**Comment by VassilIordanov** [comment]
Preferred approach updated to the following:
- continue to store the name as a single string in the database. The new convention to adopt is that if the string contains one or more commas, the string to the left of the first comma is the last name, and the remaining on the right are the first name(s). 
- when displaying the name string, capitalize all letters to the left of the first coma (or all letter if no comma).
- when editing the name string:
  - present the user with 2 text boxes
  - first text box shows the last name. When empty, it displays a "LAST NAME" hint
  - last name text box is always capitalized
  - move focus from last name to first name when a tab or a coma is pressed
  - second text box shows the first name in its native case
  - when empty second text box displays a "First name(s)" hint
  - there is a "," label between the 2 boxes

**Comment by dspCarlson** [comment]
Test failed: Verify the focus/cursor moves from the last name field to the first name field when a comma is entered and the focus is in the last name field.

Two distinct bugs:
1. Comma being displayed in the first name field when the focus moves from the last name to the first name
2. The first letter typed in the first name field cannot be removed

Condition: 
1. A profile (advisor or principal) is in edit mode
2. The focus is in the last name field

Action:
1. The user presses the comma key

Actual Result:
1. The focus moves from the last name to the first name
**2. The comma is displayed in the first name field**
**3. The comma cannot be removed using the delete key or the backspace key**

**Comment by dspCarlson** [comment]
Test failed: The last name field displays a hint when the field is blank

Bug: The first letter in the last name field cannot be removed

Condtion:
1. A profile is in edit mode
2. The last name field has a name displayed

Action:
1. The user presses the delete key until the name displayed in the last name field is removed

Actual Result:
**1. The first letter in the last name field cannot be removed by the delete key (or the backspace key)
2. The hint is not displayed in the last name field**

**Comment by VassilIordanov** [comment]
Thanks @dspCarlson great finds

**Comment by dspCarlson** [comment]
Test failed: When saving a principal, the principal profile cannot be saved when the principal only has one name

Many principals only have one name.  The principal's signle name should be saved in the last name field and the first name field should be blank.

**Comment by evdhoudt** [comment]
@dspCarlson thanks for the feedback! The bug was introduced by https://github.com/NCI-Agency/anet/issues/194

Have tested both the original issue 201 and 194 and the bug should be fixed in the next pull request :)
