### ISSUE TITLE
Remove Titles from Names When Saving the Name

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#202]
Automatically remove titles from the name field when saving a name.  I will supply a list of titles.

**Comment by VassilIordanov** [comment]
It seems like there is a list of titles that can't be easily confused with people's names. The suggestion is to add this list to the dictionary and have client-side validation that prevents a user from adding a name containing these. This applies to people creation and onboarding.
The validation error should be something along the lines of:
"You must provide a valid name without ranks, titles, and grades. %offendingValue% is not allowed in name fields"

**Comment by maradragan** [comment]
Added to #1972
