### ISSUE TITLE
Remove Leading Space(s) From Data Fields When Saving a Record

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#203]
Remove leading space(s) from data fields when saving a record.  There are 19 fields where users/super users enter text.  When saving a record remove leading spaces for these 19 fields.  Some fields are more important than others because some fields get sorted and others don't.

Reference item 103

**Comment by gjvoosten** [comment]
Hi @dspCarlson, this could probably be genericized into: trim leading and trailing whitespace from text fields when saving records. Right? Since we're also not really interested in trailing whitespace.

**Comment by dspCarlson** [comment]
@gjvoosten Yes, you are correct.  Trim both the leading and trailing spaces.  It never hurts to trim the trailing spaces either.

**Comment by dspCarlson** [comment]
Test Failed: Remove leading and trailing spaces for a report approval step name

Condition:
1. An advisor organization is in view mode
2. The advisor organization has an approval step
3. The approval step has a name

Action:
1. Select the "Edit" button
2. Scroll down do the "Approval process" section of the advisor organzation
3. In the "Step name" field, enter three leading spaces and three trailing spaces
4. Select the "Save organization" button

Result:
1. Selecting the "Save organization" button displays a pink error message, i.e. "Bad Request: Unable to process JSON"

Any change (add a character, change a character or delete a character) to the "Step name" text generates this error.

**Comment by gjvoosten** [comment]
Not being able to change the approval step name was an old bug (most likely present for quite some time). Fixed now.
After fixing the bug it turned out that for this specific field, whitespace was not yet stripped. Also fixed.
