### ISSUE TITLE
Extend sensitive data to attendees

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2057]
When there is an authorized group for sensitive info defined, can we give an option to make selected attendees also sensitive?

**Comment by maradragan** [comment]
Which means, if a report has an authorization group selected, then add a checkbox (or other UI item) next to each attendee to make this attendee "sensitive". Attendees that are sensitive will be seen only by authorized readers

**Comment by jose-west** [comment]
Remarks bij Gertjan about the current PR (posted on Slack on 11-10):

> Concerning https://github.com/NCI-Agency/anet/issues/2057 : the corresponding PR filters this only on the client side. This means that I can see the sensitive attendees (in the GraphQL response) even when I'm not authorised. Shouldn't these be filtered on the server side? Note that this will certainly lead to complications in the server-side code when someone who is not authorised (via the authorization groups) but still has edit permissions on the report performs an update. Besides that, also the search for attendees becomes a lot more complicated; e.g. right now, I can search for sensitive attendees that I'm not authorised to see, and still get all the reports they appear in! Also, the server-side logic that checks the attendees that are passed in the update (which adds the ones that are passed in but are not yet in the database, and removes the ones that are not passed in yet are in the database) becomes non-trivial. And what do you do when that someone adds an attendee that is already there but which is marked sensitive and thus they cannot see? It would would either lead to an error message ("attendee already present") or would not do anything. In both cases, you leak information that that person is a sensitive attendee! This really needs to be properly decided before merging this PR and putting it out in the field.

**Comment by jose-west** [comment]
After the team meeting on 15-10 we decided to rethink how to implement this issue.

**Comment by gjvoosten** [comment]
Objects can now have customSensitiveInformation.
