### ISSUE TITLE
Engagement report validation for tags

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2183]
The requirements owners want at least one of six tags to be mandatory for all engagement reports.  The six tags will be emailed to @VassilIordanov on the high side.

**Comment by VassilIordanov** [comment]
After talking with the users, the way forward is to infer this information from the selected tasks instead of adding tags. Will keep it open until confirmed

**Comment by dspCarlson** [comment]
@midmarch @gjvoosten @cemalettin-simsoft 

I am closing this issue.

The functionality is no longer needed.  The requestor for this functionality is long gone.
