### ISSUE TITLE
Add a link to external documentation on the front page

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#22]
Reference item 10

**Comment by gjvoosten** [comment]
We need to figure out two things:
1. where to configure this link
1. where to put this link in the client

**Comment by dspCarlson** [comment]
1. The external link should get configured on the admin page under the Site settings.

**Comment by dspCarlson** [comment]
2. The location of the link should be above the "Help" which is located in the left-hand column.  The link should also appear when the "Help" link is visible.

**Comment by VassilIordanov** [comment]
The name "external documentation" is too generic. It should also be an admin-configurable field.
