### ISSUE TITLE
Summary of partner assessment does not display red assessments

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2214]
The summary does not display the color red nor does it display the number of red assessments.

Screenshot of the assessment summary emailed to @VassilIordanov

**Comment by gjvoosten** [comment]
@vassil @dspCarlson After the old-style partner assessments are migrated to periodic assessments (available in the next release), is this issue still relevant?

**Comment by dspCarlson** [comment]
@midmarch @gjvoosten @cemalettin-simsoft 

I am closing this issue.

This issue is OBE (Overcome By Events) and is obsolete.

The requestor is long gone and the functionality is no longer used in ANET.
