### ISSUE TITLE
Position history after merge people is not correct

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#2258]
I am merging a "loser" without position with a "winner" having a position "position X".
After the merge I see in the new person's position history:
- position X     start date - merge date
- position X     merge date -

I would expect it to see 
- position X     start date -
as the position didn't change

**Comment by cemalettin-simsoft** [comment]
We can fix this problem and improve merge people tool by reusing the merge functionality that is implemented in #3147
