### ISSUE TITLE
Copying from Microsoft Word into Engagement Details removes the rich text formatting

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2342]
The rich text formatting (e.g. bold, underline, font size) is lost when copying from Microsoft Word into the Engagement Details data field.  The same is true for the Sensitive Information data field and the Biography data field.

At one point copying rich text from Word was available.

I found other similar rich text issues, but not quite this issue.
#1114 
#1567 
#1729 
#1606 
#1950 
#1955

**Comment by VassilIordanov** [comment]
unfortunately, this is a problem with IE11. It is too difficult to work around it to make it work on IE11, and as we are about to drop support for IE11 we will leave this unresolved
