### ISSUE TITLE
Dashboard of new users is not correct

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#2349]
For new users without position the 3rd and 4th dashboard tiles on the homepage don't have a title and display the total amount of reports. This is because the queries are related to the user's organization and the user doesn't have one.
We should not make these dashboard visible for users without a related organization.

**Comment by dspCarlson** [comment]
@maradragan This is a good idea.  Users not assigned to positions can still create draft reports.  Would it still be possible to leave the draft reports part of the dashboard visible?

**Comment by maradragan** [comment]
> @maradragan This is a good idea. Users not assigned to positions can still create draft reports. Would it still be possible to leave the draft reports part of the dashboard visible?

@dspCarlson Yes, they will only not see the organization related tiles, as they are not assigned to any organization yet.
