### ISSUE TITLE
Error in anet.log when sending email to more than one addressee

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#24]
Every day the anet.log file has multiple error entries when sending emails.  Checked the validity of the email: the email addresses are valid and resolve in Microsoft Outlook.  Have attached four anet.log files.
Reference item 13

**Comment by gjvoosten** [comment]
Is this still relevant after #425 was merged?

**Comment by dspCarlson** [comment]
@gjvoosten This is an issue @VassilIordanov created on my behalf when we were first getting started.  In my opinion this can be closed because of #425.

**Comment by gjvoosten** [comment]
Right! Closing this one.
