### ISSUE TITLE
User cannot send reports using the ANET email function

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2400]
User receives pink error message when trying to email a pending report.

Error message: 
Internal Server Error: Validation error of type SubSelectionNotAllowed: Sub select not allowed on leaf type Int of field emailReport @ 'emailReport'

**Comment by gjvoosten** [comment]
Fixed in candidate.

**Comment by dspCarlson** [comment]
Thank you @gjvoosten
