### ISSUE TITLE
Daily rollup Table and Summary views display "No reports found"

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2443]
A user chose yesterday's date and today's date on the daily rollup.  In the "Reports by organization" section, the "Calendar" button displays data.  But the "Table" and "Summary" buttons display "No reports found."

I was able to recreate the bug.

**Comment by dspCarlson** [comment]
If I use today's date and two days ago, then the "Table" and "Summary" buttons work fine.

**Comment by gjvoosten** [comment]
Fixed in `candidate`.
