### ISSUE TITLE
Increase the Number of Names Returned from 25 to 75 When Searching for a Person in a Search Box

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#245]
When searching for a person in a search box 25 names are returned but not necessarily the name being searched for.  But if the starts with a letter that falls towards the end of the alphabet, the searched for name is not available for select.  That's because there are many common names and the names are returned alphabetically.

The name search function is found in:
Reports
Report approval chain
Assigning personnel to positions

Reference item 49

**Comment by gjvoosten** [comment]
We agreed that increasing the number of results is not the best solution, as there may still be many results earlier in the alphabet. Better would be to order on full-text search rank (if there are no other sorting criteria), i.e. show the most relevant hits at the top.
{Note that there are additional sorting criteria; if the search ranks are equal, the results are sorted as before, so on name ascending.]
