### ISSUE TITLE
Advisor and position show an end date but there is no record of the end date in the peoplePositions table

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2450]
There is an advisor that is currently assigned to a position.  However, both the advisor assignment history and the position assignment history display the same end date for the assignments.

However, there is not an end date in the peoplePositions table for the advisor or the position.

Specific data was sent to @VassilIordanov

**Comment by maradragan** [comment]
@dspCarlson 
- was the advisor previously assigned to a different position?
- do you notice the same behaviour also for other advisors?

**Comment by dspCarlson** [comment]
@maradragan 
Yes, in this instance, the advisor was assigned to a previous position.
I have only seen this bug one other time.

The end date displayed is 18 October 2019.  However, I can't find an 18 October 2019 date in the database associated with the position or the advisor.

**Comment by dspCarlson** [comment]
This can be closed.  The end date is now stored in the endedAt column in the peoplePositions table.
