### ISSUE TITLE
Allow Advisor Organizations to Have More than One Report Approval Chain

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#246]
Only one report approval chain is allowed per advisor organization.  However within an advisor organization, advisors advise different principal organizations or different milestones/tasks.  That means different report approvers within the same advisor organization must approve different reports within the same approval step.  This has resulted in 17 approval steps having five or more approvers in one step.  (Six approval steps have 11 or more approvers per approval step).  For every report needing approval at that step, each report approver must determine if they are the correct report approver to approve the report based on the report's milestones/tasks or the principal organization being advised.

Allow each advisor organization to have more than one approval approval chain.

Reference item 55

**Comment by VassilIordanov** [comment]
Brad, is this requirement still valid?
If there are several approval chains, how do we identify which one should apply to a specific report?
Maybe a solution is:
Each Advisor Org has 1 approval chain
Each Principal Org has 1 approval chain
A report must complete both to be published

**Comment by dspCarlson** [comment]
This is still a valid requirement.  Advisor organizations are forced to use one report approval chain for many different approval areas.  This results in many report approvers for just one approval step.  (For example, one advisor organization has 22 report approvers for one approval step.)  The report approvers must sort through all their report approver emails to determine which report(s) they must approve.

**Comment by VassilIordanov** [comment]
@dspCarlson now we also have approval chains for Location and Tasks. Can this be closed?

**Comment by dspCarlson** [comment]
This is no longer a valid requirement but only because the situation doesn't present itself with the mission drawdown.
