### ISSUE TITLE
Remove the Red Delete Icon on Advanced Search for the "Search term" Field

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#247]
The red delete button on the "Search term" search field is misleading.  The red delete button does not remove the "Search term" search field from the search criteria.  The "Search term" search field is a mandatory parameter for every advanced search.  The red delete button is for other optional search parameters to be removed from the search query.

Reference item 63

**Comment by gjvoosten** [comment]
@dspCarlson The button on the **Search term** field does have a function though: it clears the current input. Removing the button would remove that possibility.

**Comment by dspCarlson** [comment]
This issue is now moot.  The "Search term" data field was removed when "Advanced search" changed to filters.  I am closing this issue and removing it from the Features and Enhancements project.
