### ISSUE TITLE
Organizational Structure is Different than Rollup Structure

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#250]
Four advisor organizations report directly to a parent organization.  However, in the program these four advisor organizations cannot be assigned to the parent organization for two reasons:

1. On the Daily Rollup Report, the reports of the four advisor organizations will appear under the parent organization when they need to appear at the same level of the parent organization.

2. The four advisor organizations will not appear in the "All Advisor Organizations" drop down list in the left hand column.

Can the daily rollup and "All Advisor Organizations" drop down list be made independent of the actual advisor organizational structure in order to display the correct organizational structure?

Reference item 76

**Comment by maradragan** [comment]
Added to #1966
