### ISSUE TITLE
Recent Attendees Do Not Necessarily Include Principals Assigned to the Report Author

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#255]
This is an enhancement/change to #47 

During a recent meeting with 40 advisors, the advisors stated the biggest problem with creating and submitting reports is selecting the principals who attended the engagement.  Part of the problem is the limit of 25 names to select from.  (See #48 )  Selecting the principal attendees.  I mentioned #47 to the 40 advisors, but they countered they really needed to be able to choose principal attendees more so than advisor attendees.  Advisor names are easy to find in the "Recent attendees" search box.  They would also like 12 recent attendees displayed instead of the 6 recent attendees from #22.

The requirements are:

1. Increase the number of recent attendees from 6 to 12 in the right-hand part of the "Meeting attendance" section.
2. Prioritize the recent attendees displayed.  There are three priorities in the following order:
    a. Recent principal attendees
    b. Principals assigned to the primary advisor attendee but who are not recent principal attendees
    c. Recent advisor attendees

Reference item 85

**Comment by evdhoudt** [comment]
When creating a report it is difficult to find all the attendees at an engagement. Especially the Principal counterpart.
- An overview of all possible attendees would be helpful (instead of typing a name).
- Advisors paired with their principles could be a solution to more easily find attendees

**Comment by maradragan** [comment]
Closed by #1602
