### ISSUE TITLE
Cannot Tell When a Report Author Submitted a Report

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#256]
The date and time a report was created by the report author is recorded.  However, the date and time a report author submitted a report for approval is not recorded.  The report submitted date is important because it cannot be determined how long it took from the engagement date to the date/time the report author submitted the report.  There is a time requirement for the report author to submit the report for approval so many days after the engagement.  This cannot currently be measured.  Furthermore, it can't be determined how long it took the report approver in the first approval step to approve the report after the report was submitted.

Because reports can be submitted for approval and then edited and rejected and then re-submitted numerous times.  This sequence of events would also have to be recorded.

The submitted date and time should be displayed on the report approval histories for pending reports, rejected reports, and released reports.

Reference item 88

**Comment by VassilIordanov** [comment]
Worth looking at from a more general point of view: how do we record an track history of all report modifications/events.
