### ISSUE TITLE
Daily Rollup Bar Chart: Clicking on the Orange Part of the Bar Should Display Cancelled Reports

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#258]
On the Daily Rollup bar chart, clicking on the blue or orange section of the bar will only display reports that are released, but not reports that are cancelled.  Clicking on the blue section should display only released reports.  Clicking on the orange section should only display cancelled reports.

Reference item 93

**Comment by dspCarlson** [comment]
@VassilIordanov  Will this still be an Insight as per your project assignment on 30 May 2018?  The requirements owners are expecting this to be implemented on the Daily Rollup bar.

**Comment by maradragan** [comment]
Added to #1966
