### ISSUE TITLE
Display Message When Report Approver Clicks Link in Report Approval Email But the Report is Already Approved

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#259]
When there is more than one report approver in a report approval step, one of the report approvers may approve the report.  When another report approver clicks the link in the email, a blank screen is displayed.  The report approver is left wondering what happened to the report.

After a report is approved, if another report approver clicks on the report link in the email, a message should be displayed notifying the second report approver that the report has been approved.  The message should also display the name of the report approver who approved the report, the date and time the report was approved.

A message should also be displayed if another report approver rejected the report.  The message should state the report was rejected and returned to the report author by <Name of Report Author who rejected the report>, and the date and the time the report was rejected.

Reference item 110

**Comment by evdhoudt** [comment]
https://github.com/NCI-Agency/anet/issues/263 fixes this issue
