### ISSUE TITLE
Insight for Reports Created During a Given Time Period for Report Authors Assigned to an Organization or a Sub-Organization

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#260]
Create a report that identifies reports created during a given time period.  The reports are created by report authors assigned to an organization or a sub-organization.

User must be able to input an advisor organization, a start date and an end date.

Report example (Excel spreadsheet format) and SQL statement emailed to @VassilIordanov on 6 November 2017.

Reference item 111

**Comment by maradragan** [comment]
Added to #1958
