### ISSUE TITLE
Do Not Let a Super User Save an Advisor Organization if a Report Approval Step Does Not Have a Name

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#262]
If a super user tries to save an advisor organization and the advisor organization has a report approval step that doesn't have a name:

1. Display a message that there is an approval step(s) that doesn't have a name
2. Do not let the super user save the advisor organization

Reference item 114

**Comment by evdhoudt** [comment]
@dspCarlson Should the approval step also have a required Approver?

**Comment by dspCarlson** [comment]
@evdhoudt Yes.  Every approval step should have at least one approver.
