### ISSUE TITLE
Advanced Search for an Advisor Position Only Returns the Position Name But Not the Code

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#267]
When search an advisor position in Advanced Search, the results display the position name, the organization the advisor position is currently assigned to, and the advisor who is currently assigned to the position.

However, the advisor code is not displayed in the query results.  The code should have its own column.

The status of the of the advisor position should also be displayed, i.e. active or inactive.

This issue is similar to #253 

Reference item 118

**Comment by dspCarlson** [comment]
Not an issue after all.  The inactive positions are split between the "Supported positions" section and the "Vacant positions" section.

**Comment by dspCarlson** [comment]
Not an issue after all.  The inactive positions are split between the "Supported positions" section and the "Vacant positions" section.

**Comment by dspCarlson** [comment]
Not an issue after all.  The inactive positions are split between the "Supported positions" section and the "Vacant positions" section.

**Comment by dspCarlson** [comment]
Not an issue after all.  The inactive positions are split between the "Supported positions" section and the "Vacant positions" section.

**Comment by dspCarlson** [comment]
Please re-open this issue.  I inadvertently closed it when I was closing #268.

**Comment by gjvoosten** [comment]
Well, actually, since there is only one table showing Positions resulting from an (advanced) search, which could potentially be showing results from either type of position, this issue can be considered a duplicate of #253, and should be solved there (by adding columns to the position results table).

**Comment by dspCarlson** [comment]
#253 has a better description of what needs to be done.
I am closing this issue.
