### ISSUE TITLE
Implement Task assessments

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2681]
- [x]  add an assessmentDefinition field to tasks, to use for filling in the JSON with the assessment fields
- [x] in the report form, add task assessments for the selected tasks
- [x] save the report task assessments as notes
- [x] load assessments when editing an existing Report
- [x] display assessments on the report show page
- [x] make it possible to configure assessment fields validation (just like for custom fields)

Later:
- [x] review Show (read-only) behavior
- [x] render collections of assessments on page of Tasks (with an enhanced LikeredScale)

**Comment by maradragan** [comment]
Moved " custom editor for assessmentDefinitions" to a new issue #3064

**Comment by maradragan** [comment]
Added issue #3065 for "improve rendering of all notes in the side panel (show rich content instead of json)"
