### ISSUE TITLE
remove org.json dependency

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2763]
Update email tests not to rely on org.json

**Comment by jose-west** [comment]
@VassilIordanov Why should we remove the 'org.json' dependency? Do you have an alternative in mind for JSONObject and JSONArray?

**Comment by jose-west** [comment]
After some digging I found these:
- https://wiki.debian.org/qa.debian.org/jsonevil
- https://www.apache.org/legal/resolved.html#json

Apparently the package is licensed under MIT, but has a special clausure considered as non-free non-free by Debian. License: https://www.json.org/license.html

> The Software shall be used for Good, not Evil.

The more you know...

**Comment by VassilIordanov** [comment]
most of the java code is using `com.fasterxml.jackson` for json de/serialization. At the moment `org.json` is only referenced by the email tests
