### ISSUE TITLE
Saved searches "preview" is not functioning

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#277]
- Make an advanced search for reports, just with a text argument
- save the search
- search appears in saved searches
- when selected, list underneath is empty "no reports found"
- when open, search has indeed results with reports

We should either have a preview that shows the first 10 reports, or not display anything

**Comment by gjvoosten** [comment]
It is actually a bug in the rendering (`approvalStatus` can not be rendered because that field is not retrieved in the saved search table) which prevents the results from showing. I will push a fix.
