### ISSUE TITLE
Error message displayed when searching for an organization's reports 

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2778]
To recreate the bug:

1. Select "Add filters"
2. Select the "Reports" button
3. Select "Organizations" as a filter
4. Select any advisor or principal organization
5. Select the "exact match" or "include sub-orgs" or "include parent orgs" button
6. Select the "Search" button

Result: the following error message is displayed:
"There was an error processing this request.  Please contact an administrator."

**Comment by VassilIordanov** [comment]
Brad - can you confirm if still happening?

**Comment by dspCarlson** [comment]
@VassilIordanov Yes, the error message is still displaying when searching for an organization's reports.
