### ISSUE TITLE
Error message displayed when trying to assign a report approver to an approval step

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2779]
Condition:
1. Super user assigns a report approver to a report approval step for an organization
2. Super user selects the "Save Organization" button

Result:
The following error message is displayed:
Internal Server Error: Exception while fetching data (/UpdateOrganization) : org.jdbi.v3.core transaction.  UnableToManipulateTransactionIsolationLevelException: unable to access current setting

**Comment by VassilIordanov** [comment]
@dspCarlson this should be solved, could you please confirm?

**Comment by dspCarlson** [comment]
@VassilIordanov Yes, this bug is fixed.  I made myself a super user for an advisor organization and was able to add report approvers.
