### ISSUE TITLE
Allow effort owners to select other efforts owners for the same effort

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2787]

**Comment by gjvoosten** [comment]
@dspCarlson Should effort owners also be allowed to remove themselves? (they wouldn't be able to make changes after that, obviously, so if they were mistaken, an admin may have to step in and fix things)

**Comment by dspCarlson** [comment]
@gjvoosten Yes, effort owners should be allowed to remove themselves from efforts.  Effort owners change jobs and could no longer be associated with an effort.  If an admin must fix things it probably won't be that often.
