### ISSUE TITLE
Improve the Email Sent to ANET Approvers

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#28]
"The ANET email sent to approvers needs nine changes:
1. Add the report ID on the "Advisor:" field. e.g. "Report number: 12345¨ 
2. Change "Advisor: " to "Advisor organization:"
3. Remove the "-->" in front of "Advisor: "
4. Add the "Advisor attendees: " below "Advisor organization:"
4.1 Add _from_ Org-shortname after each advisor
5. Identify the primary advisor by adding a "(primary)" after his/her name
6. Change "Principal:" to "Principal organization:"
6.1. Add the "Principal attendees: " below "Principal organization:"
6.2 Add _from_ Org-shortname after each principal
6.3. Identify the primary principal by adding a "(primary)" after his/her name
7. Change "Meeting Goal:" to "Meeting purpose:"
8. Change "Time and Place:" to "Engagement date and location:"
9. Signature should be  `ANET Support Team CRLF <support team email address>`

The above changes were modified to be consistent with the writing guidelines https://material.io/guidelines/style/writing.html#

Secondly
 
On the automated emails for approvals, there is an option that says click here to approve.  However it is not clear that clicking that link approves the report without offering the opportunity to review it first.

Reference item 21

**Comment by dspCarlson** [comment]
Remove the "Click Here to Approve this Report" link in the email body.  See update to reference item 21.

**Comment by dspCarlson** [comment]
The report approver email should have only one link in the body that allows the report approver to open the report, and then either approve, reject or edit the report.
