### ISSUE TITLE
Advanced Search Does Not Return Any Results When Search for Reports with a Draft Status

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#283]
Super users are responsible for policing draft reports for their organization.  However, using "Advanced search" to find reports with a "draft" status does not return any results.  As of this moment there are 524 reports with a draft status and the advisorOrganizationId is not NULL and the authorId is not NULL.

A super user would use the following search actions to find reports for his/her organization:
1. Select "Advanced search"
2. Select the "Reports" button
3. Add the "Organization" filter
4. Select an organization that has one or more draft reports
5. Select the "State" filter
6. Select the "Draft" value for the "State" filter
7. Click the blue "Search" button

The leadership would use the following search actions to find all reports with a draft status:
1. Select "Advanced search"
2. Select the "Reports" button
3. Select the "State" filter
4. Select the "Draft" value for the "State" filter
5. Click the blue "Search" button

Reference item 121

**Comment by VassilIordanov** [comment]
@dspCarlson , currently I can search for reports with draft state, but that returns only my draft reports. That kind of makes sense, as reports are only visible to me as long as they are in draft state.
  1. Are we saying that they should also be visible to the super users of my org? I can see a point for that.
  2. We could make admins be able to see everyone's draft reports, regardless of the org. Would that address the second use case?

**Comment by dspCarlson** [comment]
@VassilIordanov Reports left in a draft/rejected status need to be identified and then approved or deleted.  Maybe search filters are not the means to identify and manage draft/rejected reports.

As of 20 August 2018, there are 1,014 reports with a draft or rejected status where the engagement date is more than one week ago.

**Comment by dspCarlson** [comment]
A user can only search for their own draft reports, but not the draft reports of another person or organization.

This ticket should be closed.
