### ISSUE TITLE
Externalize date format spec to dictionary

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#287]
Currently it is 'DD MMM YYYY' in most places. Make that live in the dictionary under a `dateFormat` property

**Comment by dspCarlson** [comment]
Is there anyway to spell out the complete month in all the dates instead of the three-character abbreviation?  Because of the multi-national environment, it would be much clearer for non-native English speakers.  Plus it's also one of the date standards for the leading organization here.

**Comment by VassilIordanov** [comment]
@dspCarlson Once we have the dateFormat specifiable in the dictionary, you will be able to define a format what will work like: https://momentjs.com/
