### ISSUE TITLE
Improve task assessments

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2926]
The current Task assessment view is not very user friendly.

As a user I should only see the latest Task assessment for the specific month in the body of the main Task page, instead of all of the month's assessments

As a task owner/admin, I should see an "Add a ${task label} assessment for the month of" or a "Make a new ${task label} assessment for the month of" depending on is it the first assessment for the month or not.

As a task owner/admin, I should have access to a rich text editor in the example "top 3 issues" assessment field.

**Comment by dspCarlson** [comment]
On the effort assessment pop-up window to enter text:
issues, recommendations, risks bleed into the actual text box.  There's plenty of real estate to avoid the bleeding over.

The word recommendation is misspelled; recomendation vs recommendation

**Comment by VassilIordanov** [comment]
@dspCarlson the text is specific to your `anet.yml` config. You can fix the spelling by modifying that file
