### ISSUE TITLE
Make it possible to have a location with a null geo position

### ISSUE THREAD

**Issue by oayvazoglusim** [NCI-Agency/anet#2934]
I am not able to remove a location's geo coordinates

- [x] When editing a Location, ANET should allow me to also remove the geo coordinates of a Location

It is proposed, to have an editable coordinates field in the Location editor. This field should have a mechanism to remove the location (typically done with a delete.png icon in the test of the UI)

![location_page](https://user-images.githubusercontent.com/61961034/77174656-76fa1a00-6ad2-11ea-98ae-b4e46b86baca.png)

related with the epic issue #244

**Comment by ysf-simsoft** [comment]
@VassilIordanov we added a clear link button next to coordinates, which is visible only when a coordinate is selected. i.e.

![image](https://user-images.githubusercontent.com/62024178/77288625-49d38480-6ce9-11ea-938d-2027e8831d51.png)

becomes 

![image](https://user-images.githubusercontent.com/62024178/77288662-59eb6400-6ce9-11ea-9667-9750cd2b2bf7.png)

In addition to that, is it really necessary to make coordinates editable? Would the user want to enter coordinates manually? If so, some more questions arise.

1. Should we validate manually entered coordinates?
2. Should we impose any limitations on manually entered coordinates such as, limiting coordinates to a specified area only?
3. Should we synchronize map marker with manually entered coordinates such that when user enters a valid coordinate we automatically position the marker on the map?

**Comment by VassilIordanov** [comment]
@ysf-simsoft 
- I think the "clear" action works when it is part of an editor and when it is consistent with the rest of the UI (if we use the same icon as elsewhere - delete.png)
- yes, there is a requirement for the users to enter a location manually (https://github.com/NCI-Agency/anet/issues/244).
- yes, coordinate should be validated depending on type (lat/lon, MGRS, others in the future)
- no limitation to any area is needed
- the location editor will have 2 ways of setting a location - both through the map and through a coordinate editor. They should be integrated and behave in a user friendly manner. As it is both are different visual representations of the same state, it is likely that the more user-friendly behavior is to have them both in sync.
