### ISSUE TITLE
Retire IE11 support

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2955]
**Technical debt description**
It is time to drop IE11 as a fully supported browser.

**Proposed solution**
- introduce a warning message/banner when IE11 is detected alerting users IE11 is not fully supported and they should consider a different browser. We should make sure that no matter what, the banner is supported on IE11 and is visible.
- wait for two months
- address issues that we not possible in the past due to IE11 incompatibilities

**Additional context**
n/a

**Comment by ysf-simsoft** [comment]
Here is my proposal for solution;

1. Use [this library](https://github.com/DamonOehlman/detect-browser) for browser detection (seems mature/old enough and under active development).
2. When IE detected show a warning banner above `SecurityBanner` in `TopBar.js`
3. Implement BrowserStack tests for making sure that no matter what, the banner is supported on IE11 on Windows 7 and is visible.

**Comment by ysf-simsoft** [comment]
for future reference, Microsoft provides VMs for IE and EDGE testing for [several VM platforms here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).
