### ISSUE TITLE
Improve aggregation widgets

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#2971]
**Is your feature request related to a problem? Please describe.**
The current aggregation widgets are really basic, they have been built mostly 

**Describe the solution you'd like**
- [x] The NumberAggWidget aggregation widget is really basic. Instead, we need a different way to display numbers. A most natural one is some kind of IQR box plot. Some of that is already implemented in the LikertScale widget. This should be abstracted

- [x] add aggregations for enum values. Could be rendered with `Pie` - having a segment for each possible enum value

Aggregations should also be used elsewhere:
- [x] everywhere where we have Report Collections, we can also an a "Statistics" tab that displays statistics based on aggregations on the custom field. Possibly also by period (monthly)

**Comment by cemalettin-simsoft** [comment]
Looks like all the check marks have been done and https://github.com/NCI-Agency/anet/pull/3069 merged which should've closed this issue.
