### ISSUE TITLE
Multiple assessment periods

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2977]
Terminology:
- periodic assessments => assessments made periodically on an entity, with a given recurrence, assessing the entity related to a given period
- instant assessments => assessments made once on an object, not related to a period of time; these assessments can assess an entity in the context of a related object (example: assessing tasks or attendees from the context of a report, we will call these assessments engagement assessments) or can assess it on its own, without a relation to another entity

This issue concerns the periodic assessments.

Currently periodic assessments are on a monthly basis. It should be possible to make assessments over different periods of time, with different recurrences.

When defining the assessments, an administrator should be able to define at what recurrence assessments are made. Possible assessment periods are:
- once => instant assessment
- daily
- weekly
- biweekly
- semimonthly
- monthly
- quarterly
- semiannualy

Where the assessments can be defined by the administrator depends on the entity type:
- for tasks the admin can define assessments on a general level, separated per toplevel or sublevel tasks and can also define instance specific assessments by adding an assessments custom field to tasks and filling it in
- for an instance we use the union of the general definition and the instance specific definition in order to determine which assessments are available

Example scenario
task A is assessed monthly and quarterly
task A.1 is a sub-task of A, assessed weekly, but also monthly

When we display the periodic assessments/engagement assessments of task A.1, we display

| week - 2  | week - 1  | current week   |
|---|---|---|
| Weekly Task A.1 engagement assessments  | Weekly Task A.1 engagement assessments | Weekly Task A.1 engagement assessments |
| Weekly Task A.1 assessment  | Weekly Task A.1 assessment |  |

| month - 2 | month - 1 | current month  |
|---|---|---|
| Monthly Task A.1 engagement assessments  | Monthly Task A.1 engagement assessments | Monthly Task A.1 engagement assessments |
| Monthly Task A.1 assessments | Monthly Task A.1 assessments |  

Then, when we display the periodic assessment/engagement assessments of task A, we display

| month - 2 | month - 1 | current month  |
|---|---|---|
| Monthly Task A.1 engagement assessments  | Monthly Task A.1 engagement assessments | Monthly Task A.1 engagement assessments |
|.........|.........|.........|
| Monthly Task A engagement assessments  | Monthly Task A engagement assessments | Monthly Task A engagement assessments |
| Monthly Task A assessment  | Monthly  Task A assessment |  |

| quarter - 2 | quarter - 1 | current quarter  |
|---|---|---|
| Quarterly Task A.1 engagement assessments  | Quarterly Task A.1 engagement assessments | Quarterly Task A.1 engagement assessments |
|.........|.........|.........|
| Quarterly Task A engagement assessments  | Quarterly Task A engagement assessments | Quarterly Task A engagement assessments |
| Quarterly Task A assessment  | Quarterly  Task A assessment |  |

For periodic assessments a user can make per entity only one periodic assessment per  period.

Implementation steps:
- [x] add general task assessments definition: in anet.yml, under task.topLevel.assessments and task.subLevel.assessments
- [x] do union of the general level task assessments with the eventual instance level task assessments (from the task's custom field called assessments)
- [x] retrieve the instant and the periodic assessments definitions from the union
- [x] remove assessmentDefintion from task custom fields

- [x] when making a periodic assessment, save the period details in the assessment text {"__recurrence": "monthly", "__periodStart": date}
- [x] when displaying a periodic assessment (for instance as a note, or in the monthly assessments overview), do not display the __recurrence and __periodStart property from the JSON of the assessment text
- [x] filter the periodic assessments by filtering on the period details from the assessment text

- [x] add the possibility to have more types of periodic assessments
- [x] display one assessments fieldset per periodicity type, when there is a definition for it 
- [x] display add assessment button for all periods, except for the ones which are not closed (endDate > today)

- [x] instead of adding new periodic assessments for a period, edit the existing one, so there should be at most one periodic assessment per period and author
- [x] change the layout of periodic assessments => use panel to make it possible to add info as author and edit/delete icons, and to clearly distinguish between several assessments
- [x] make it possible to delete an own periodic assessment -> not needed for now, maybe later

- [x] when an assessment contains a richtext type of field, and the field is not being filled, the assessment is not considered empty (see isEmptyAssessment), but it should

**Comment by maradragan** [comment]
Added new issue for Group task assessments per tasked organization #3067

**Comment by maradragan** [comment]
Added new issue for Implement assessments period for biweekly #3068
