### ISSUE TITLE
Match report task approvers to tasked orgs

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#2989]
We are evolving towards having tasks across various organizations. There are several scenarios:

* A task has several tasked organization and has approval step with 1-2 approvers, typically from a single organization. The responsible parties take care of report approval. Works well as implemented

* A task has several tasked organization and has an approval step with several approvers (typically at least one for each tasked organization) responsible positions. The intent is that each organization nominates approvers
The current behavior is that all responsible positions can approve reports regardless of their organization

**Solution I'd like**
Be able to have a approval step with several responsible positions for a task that restrict the report approvers to the positions matching the report's organization of report approval. If none of the responsible positions matches, then act as is the approval step is empty.
Be able to also have an approval step with the old behavior

I suggest to have a property of an approval step called _"Restrict to approvers descending from the same tasked organization as the report's primary advisor"_. If the property is checked, then given a report, find the tasked organization that is an ancestor of the report, and filter the list of approvers to ones within that organization (or its children).

**Comment by gjvoosten** [comment]
[issue was closed by mistake]
