### ISSUE TITLE
Improve and extend Merge for Tasks object

### ISSUE THREAD

**Issue by oayvazoglusim** [NCI-Agency/anet#2993]
As a super user / administrator, I want to be able to merge duplicates of Tasks

As a super user / administrator, I want to have more control on which fields are taken from which object, and possibly given the ability to enter a new value of a field while merging.

**Comment by midmarch** [comment]
@dspCarlson believes this not a priority, so we moved it out the sprint for now.

**Comment by cemalettin-simsoft** [comment]
We can reuse the merge functionality that is implemented in #3147

**Comment by gjvoosten** [comment]
Is this feature really necessary?

**Comment by gjvoosten** [comment]
> Is this feature really necessary?

Functionality is not needed by the user.
