### ISSUE TITLE
graphiql not working in IE11

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3]
issue was reproted fixed in newer graphiql releases

**Comment by gjvoosten** [comment]
See https://github.com/graphql/graphiql/issues/136
This was fixed in November 2016 and has since been released I believe, see:
- https://www.npmjs.com/package/graphiql
- https://github.com/graphql/graphiql/releases

**Comment by VassilIordanov** [comment]
now also broken in production for any broswer. UfligyJS issue explained here: https://github.com/webpack/webpack/issues/6760
