### ISSUE TITLE
Cannot create a new principle organization because a parent organization cannot be selected

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3004]
**Describe the Bug**
Cannot create a new principle organization because a parent organization cannot be selected

**To Reproduce**
Create a new principle organization

1. Set your role to "ANET Administrator"
2. Select the blue "Create" button; Result: seven values are displayed in a drop-down list
3. Select the "New Organization" value from the drop-down list; Result: a new organization page is displayed
4. For the "Type" data field, select the "<Principal> Organization" button
5. For the "Parent Organization" data field, enter the UIC (Unit Identification Code) of the principal organization; Result: drop-down message is displayed: "No results found"
6. For the "Parent Organization" data field, enter the principal organization name, i.e. shortName; Result: drop-down message is displayed: "No results found"

**Expected Behavior**
1. If a principle organization's UIC is entered into the "Parent Organization" data field, the parent organization name should be displayed as a drop-down value to be chosen
2. If a principle organization's name is entered into the "Parent Organization" data field, the parent organization name should be displayed as a drop-down value to be chosen

**Screenshots**
N/A

**Environment (please complete the following information):**
Browser: Firefox 68.6.1 ESR 

**Additional Context**
N/A

**Comment by cemalettin-simsoft** [comment]
Can we clarify this issue? Which of the problems below are we trying to get rid of ?

Problem 1- There is a bug with searching organization by shortName.

Problem 2- There is no way to search for an organization by UIC. 

Problem 3-  There is no way to create an organization without specifying a parent organization.

**Comment by dspCarlson** [comment]
@cemalettin-simsoft 

Because a "Parent Organization" cannot be found (and then selected) by shortName (Problem 1) and a "Parent Organization" cannot be found (and then selected) by UIC (Problem 2), a child organization cannot be created (Problem 3).

Do the six steps listed above not reproduce the bug on your side?

**Comment by cemalettin-simsoft** [comment]
@dspCarlson Maybe i should've asked a bit differently, i meant which of them are actually "bug" or "feature request".
- Problem 1 is a bug
- Problem 2 is maybe a design choice, did we had a feature to search by UIC before, is this a new request?
- Problem 3 is again maybe a design choice where we want to force every org created to have a parent org.

**Comment by dspCarlson** [comment]
@cemalettin-simsoft 
The label for this issue is "bug," not "feature" or "enhancement."
Previously, parent principal organizations could be found by both the shortName, longName and UIC.

A good example to look at is the "Reports" filter.  If you want to find engagement reports by a principal organization using a "Reports" filtered search, you can enter the principal organization's shortName, longName or UIC using the "Organization" filter. 
 The principal organization will be displayed in the "Organization" drop-down list when the shortName, longName or UIC is used.

Yet another similar example is creating an advisor organization.  When selecting a parent advisor organization for a new child advisor organization, you can find the parent organization by shortName or longName.  Note: Advisor organizations do not have UICs.

What you are calling Problem 3 is not a problem.  Problem 3 is an effect of Problem 1 and Problem 2.  Problem 3 is not part of the "Expected Behavior" above.

**Comment by dspCarlson** [comment]
@cemalettin-simsoft 
A third criteria should be added to "Expected Behavior":
3.  If a principle organization's "Official Organization Name" (i.e. longName) is entered into the "Parent Organization" data field, the parent organization name should be displayed as a drop-down value to be chosen

**Comment by gjvoosten** [comment]
@dspCarlson You're quite right it is a bug; when you first enter the "New organization" form, the advisor organisation type is selected, and searching for parent organizations restricts this to advisor organizations. However, if you change the type of the new organization to a principal organization, when searching for parent organizations it still looks for advisor organizations. And thus you won't find you parent principal organization, no matter how hard you try.
