### ISSUE TITLE
Inactivated efforts display a blank page when selected from a filtered search

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3009]
**Describe the Bug**
When selecting a recently inactivated effort, the effort's web page is blank.

**To Reproduce**
1. Conduct a filtered search on inactivated efforts. Result: a list of inactivated efforts will be displayed
2. Select an inactivated effort that was created on 25 April 2020. Result: the effort's page will be completely blank

**Expected Behavior**
The effort and its information should be displayed after selecting the effort from the filtered search.

**Screenshots**
N/A

**Environment (please complete the following information):**
Browser Firefox 68.6.1esr and IE 11

**Additional Context**
This bug is only happening to efforts that were uploaded on 25 April 2020 and have since been inactivated. 

From the IE 11 debugger the error message is:
Invalid character
setTimeout((function(){throw e}))
File: vendors.9821f26c.chunk.js, Line: 330, Column: 31863

**Comment by VassilIordanov** [comment]
unable to reproduce
