### ISSUE TITLE
Add notification banner message when there is a new version of ANET

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3020]
When a new version of ANET is published, it is problematic for users that leave their browsers open overnight, they end up with a version out of sync.
Have ANET check for new versions, and when the case, automatically reload the client if the page contains no unsaved data. 
Add notification banner message when not possible

related to #3019 and #1164

**Comment by ysf-simsoft** [comment]
The primary challenge on this issue is to detect when a new version is published. Version number must, somehow, come from server. There are two possibilities here;

1. Server pushes version number to client whenever a new version is deployed. Can be implemented in several ways:
    1. Websockets
        - Advantages:
            1. Clients gets notified about new versions immediately.
            1. Easy to implement on client-side with small overhead.
            1. Can also be used for offline detection (#1164)
        - Disadvantages:
            1. Requires dedicated changes on server-side.
            1. Might be overkill (unnecessarily resource intensive) just for version updates.
    1. Web Push API
        - Advantages:
            1. Standard, well recognized API
            1. Clients gets notified about new versions immediately.
            1. Easy to implement on client-side with medium overhead.
            1. Once implemented can be used for other use cases (such as notifying user for new published reports)
        - Disadvantages:
            1. Requires permission from user on user agent. If user declines, whole thing falls down.
            1. Requires dedicated changes on server-side, probably with medium/large overhead.
1. Client asks/fetches/pulls current version number from server and compares it to the last version it knows to detect if there is an update.
    1. Adding a dedicated GraphQL API for client version.
        - Advantages:
            1. Clients gets notified about new versions **almost** immediately.
            1. Can be implemented side-by-side with #3019 
            1. If version field can be added to all server graphql responses whole thing can be implemented with minimal overhead. (TODO: clarify)
        - Disadvantages:
            1. If version is not send with every response then we need to poll it. Polling has a major trade off: 
                - Short polling intervals results in more immediate new version detection while consuming more resources (i.e. unnecessary requests) 
                - Long polling intervals results in delayed new version detection while consuming less resources.
    2. Utilize Service Workers for update management. [example](https://deanhume.com/displaying-a-new-version-available-progressive-web-app/)
        - Advantages:
            1. Standard API, widely used for SPA version updates.
            2. Whole thing can be implemented client side. (TODO: make sure about this)
        - Disadvantages:
            2. A bit difficult to implement.

**NOTE: This proposal is not finalized, it is still in progress.**

**Comment by VassilIordanov** [comment]
As we are using mainly graphql, I suggest graphql subscriptions.
