### ISSUE TITLE
copy-webpack-plugin 6.0.1 update breaks project build

### ISSUE THREAD

**Issue by ysf-simsoft** [NCI-Agency/anet#3029]
There are [breaking changes](https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/CHANGELOG.md#600-2020-05-15) in copy-webpack-plugin 5.1.1 -> 6.0.1 update which also break ANET build.

**To Reproduce**
1. Update package.json, set `"copy-webpack-plugin": "6.0.1"`
2. Run `yarn install` in **anet/client** directory
3. Run `./gradlew jar` in **anet** directory.

**Environment**
 - Ubuntu 18.04 LTS
 - node v10.20.1
 - yarn v1.22.4

**Comment by VassilIordanov** [comment]
This is not a bug
