### ISSUE TITLE
Cannot save the profile of an existing advisor without entering spaces or text in the "Text Field"

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3031]
**Describe the bug**
An advisor's existing ANET profile will not save unless there are spaces or text in the "Text Field" data field.

**To Reproduce**
1. Go to an existing advisor's profile
2. Select the blue "Edit" button in the top-right corner of the page
3. Select the blue "Save Person" button'
4. The "Text Field" data field displays a message: "You must provide the text field"

Although the error message is displayed, it's displayed at the bottom of the page and is not readily visible.

**Expected behavior**
When selecting the "Save Person" button, the "Text Field" data field should not be a mandatory requirement in order to save the profile.

**Screenshots**
N/A

**Environment (please complete the following information):**
Firefox

**Additional context**
Receiving complaints from users that they can't update their end of tour dates.  They can't see the error message.  But when they see the error message, they don't know what data to enter into the "Text Field" data field.

**Comment by VassilIordanov** [comment]
Behavoir is as intended per `anet.yml`. You need to modify `anet.yml` to exclude the following lines for the appropriate field:
```
-          validations:
-            - type: required
-              params: [You must provide the text field]
```

**Comment by dspCarlson** [comment]
Successfully made the change above in the anet.yml file this evening.
