### ISSUE TITLE
Improve rendering of notes in the side panel

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#3065]
The notes in the side panel sometimes just display HTML (for instance assessment notes, related to a richTextEditor type of field).
Improve rendering of all notes in the side panel to show rich content instead of json.

**Comment by gjvoosten** [comment]
I suggest to filter out assessments from the RelatedObjectNotes, as the assessments are already shown (properly) on the page of the relevant objects.

**Comment by gjvoosten** [comment]
Assessments are no longer shown in the side panel.
