### ISSUE TITLE
Implement assessments period for biweekly

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#3068]
First agree on what it means

**Comment by cemalettin-simsoft** [comment]
We need to pick a specific Monday which is an origin to calculate biweekly period. Example:
- If Monday January 1st is the origin, periods go like this (1st - 14th) -> (15th - 28th)  ... 
- If Monday January 8th origin => (8th Jan- 21th Jan) -> (22th Jan - 4th Feb) ... another cycle.

Admins can define in the anet-dictionary.yml file as the origin maybe?
