### ISSUE TITLE
Customize fileds and email templates from dictionary

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#311]
When a field, such as ADVISOR_ORG_LABEL_IDENTIFICATIONCODE, is undefined or null in the dictionary, do not display the field in the GUI.

**Comment by evdhoudt** [comment]
@VassilIordanov Should this be implemented for all LABEL fields in the dictionary?

**Comment by VassilIordanov** [comment]
@evdhoudt correct, having that option would be great for any field. Might as well, at the same time include @gjvoosten 's suggestion to group them under a common parent in the dictionary

**Comment by maradragan** [comment]
We've found an issue with the DictionaryField fields, after you type a character in the field the field loses focus, we are busy fixing it right now.

**Comment by maradragan** [comment]
On the task show page we get the warning:
"Warning: Unknown prop `enum` on <div> tag. Remove this prop from the element.
