### ISSUE TITLE
Default global filter for status in search

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3124]
When users type a search text to search for something, the search finds both active and inactive items. The default path should be to see only active items, unless explicitly specified.

It would be more intuitive to have a default search filter present, which is for `status=active`. If the user wants to see anything beyond that, they can either explicitly remove the filter, or specify a different value for status.

The issue is that not all search types have an status attribute, and one of them (People) has 3 different values:
Report - no status attribute
People - status is one of ACTIVE, INACTIVE, NEW_USER
all others - status is one of ACTIVE, INACTIVE

One solution is to make:
Report - no status attribute
all others, including people - status is one of ACTIVE, INACTIVE
People - use pendingVerification instead for deriving NEW_USER state

Subsequently, we can add a global filter for status (with a UI default of ACTIVE), and (for now) with no effect on reports. Alternatively, we could make it equivalent to state=PUBLISHED for reports

**Comment by dspCarlson** [comment]
Implemented in release 2.1.27-285 on 11 August 2020.  Closing the ticket.
