### ISSUE TITLE
Numerous instances of personal data leak via logs

### ISSUE THREAD

**Issue by prabhu** [NCI-Agency/anet#3140]
**Describe the bug**
Thank you for using ShiftLeft Scan. As you might know, scan uses open-source scanners under-the-hood and has limitations. I scanned this repo, using the Next Gen analysis tool from ShiftLeft and found numerous instances where personal data such as email, phone number are being sent to the logs as warning and errors without any obfuscation.

A sample screenshot is below:

![data-leaks](https://user-images.githubusercontent.com/7842/89904700-29955b00-dbe1-11ea-9529-62dcb9717c96.png)

Eg: https://github.com/NCI-Agency/anet/blob/candidate/src/main/java/mil/dds/anet/database/ReportSensitiveInformationDao.java#L107-L107

Notice how the Person class is sent to logs as info.

**To Reproduce**
1. Manual review of all invocation of logging methods (or)
2. Connect this repo with ShiftLeft [NG SAST](https://www.shiftleft.io/register) if possible since there are numerous occurrence of this issue (optional)

**Expected behavior**
Log messages should be sanitized and free of personal data for compliance

**Screenshots**

**Environment (please complete the following information):**
 - Browser [e.g. IE11, Edge, Safari...]

**Additional context**

cc: @conikeec

**Comment by conikeec** [comment]
@gjvoosten we are happy to offer security scan on this OSS repo at no cost to stay on top of vulnerabilities, data leaks, open source composition analysis, business logic flaws, etc.
Let us know if you are interested and @prabhu can help integrate our solution.
