### ISSUE TITLE
Issue with changing position type from principal to advisor

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#318]
Let's say that I am editing a principal position.
Right now, if I want to change the type of the position to an advisor position without selecting a permission, when I save the position will still be of type principal.
This happens because when changing the type to advisor the permissions field is not changed (and therefore remains principal).

**Comment by evdhoudt** [comment]
The issue can be fixed by simply changing the if statement (if (position.type !== Position.TYPE.PRINCIPAL) )  in the onSubmit method of the positions form to:

`	@autobind
	onSubmit(event) {
		let {position, edit} = this.props
		position = Object.assign({}, position)

		if (position.type !== Position.TYPE.PRINCIPAL) {
			const permissions = position.permissions !== Position.TYPE.PRINCIPAL ? position.permissions : null
			position.type = permissions || Position.TYPE.ADVISOR
		}`
