### ISSUE TITLE
Cannot remove advisor-principal relationships

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3188]
**Describe the bug**
Cannot remove / delete existing advisor-principal relationships.
At an advisor's page or an advisor position's page, principals cannot be removed as a partner.
At a principal's page or a principal's position page, advisors cannot be removed as a partner.

**To Reproduce**
1. Go to advisor's page; the advisor must have one or more principals assigned
2. Click on the white "Change assigned principal partner" button.  Result: a pop-up window will be displayed with a list of assigned principal partners
3. Select a red x next to a principal's name to remove / delete the relationship.  Result: the principal partner is not removed from the list of principal partners in the pop-up window

**Expected behavior**
The principal partner should be removed from the principal partner list in the pop-up window

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Browser: Firefox

**Additional context**
N/A

**Comment by gjvoosten** [comment]
Silly mistake, my bad…
