### ISSUE TITLE
New Role-account Users Are Not Asked to Create a Profile

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#32]
This problem only affects ANET users that have role based user domain names.  
 
When there is a HOTO, the incoming advisor is not asked to create an ANET profile when they log in for the first time.  That is because the (role-base) user domain name is stored in the outgoing advisor's record in the ""people"" table."
Reference item 29

**Comment by dspCarlson** [comment]
@VassilIordanov @gjvoosten I believe #65, #125 and this issue (#32) are all addressing the same problem.

**Comment by dspCarlson** [comment]
Completed in the 26 November 2017 release.
