### ISSUE TITLE
Pending assessments email notification

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3231]
The users that have new pending assessments should receive:
- an email as soon as the assessments are available to be made
- a reminder email:
  - for daily recurrence, never
  - for weekly recurrence, 3 days after notification
  - for biweekly recurrence, 5 days after notification
  - for semimonthly recurrence, 5 days after notification
  - for monthly recurrence, 1 week after notification
  - for quarterly recurrence, 4 weeks after notification
  - for semiannually recurrence, 1 month after notification
  - for annually recurrence, 1 month after notification

**Comment by cemalettin-simsoft** [comment]
This is related to the issue #3208  and to the PR #3212 . We should think about this when solving previous ones.

**Comment by cemalettin-simsoft** [comment]
This shouldn't have been closed automatically
