### ISSUE TITLE
Add a new engagement cancellation reason

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3238]
**Is your feature request related to a problem? Please describe.**
Virtual engagements are being cancelled because of network / connectivity issues.  Report authors cannot select a relevant cancellation reason.

**Describe the solution you'd like**
Add a cancellation reason.  For example "Cancelled due to Network / Connectivity Issues"

**Describe alternatives you've considered**
N/A

**Additional context**
This additional cancelled reason was requested by a user.
The request was approved by the requirements owner.

**Comment by VassilIordanov** [comment]
Indeed. We should externalize these reasons in `anet-dictionary.yml`
