### ISSUE TITLE
Location for effort / assessment owners is always "Unspecified" even if the effort / assessment owner's position has a location assigned

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3288]
**Describe the bug**

In the "Responsible positions" section of an effort / assessment, each position has the following five pieces of information:
Name (of the position)
Location
Organization
Current Occupant
Status (of Current Occupant)

The "Location" value is always "Unspecified" even if the advisor position has a location assigned.

**To Reproduce**
1. Go to an advisor position
2. Verify the advisor position has a location assigned 
3. Go to an effort / assessment
4. Select the blue "Edit" button at the top-right of the page
5. Scroll down to the "Responsible positions" data field
6. In the "Responsible positions" data field, enter the advisor position name.  Result: the advisor position will be displayed in a drop-down list
7. Select the advisor position name from the drop-down list.  Result: the (advisor position) Name, Location, Organization, Current Occupant and Status will be added to the list of advisor positions immediately below the "Responsible positions" data field
8. See the error: the "Location" value is "Unspecified"

**Expected behavior**
1. If the advisor position has a location assigned, the location name should be displayed in the "Responsible positions" section
2. If the advisor position does not have a location assigned, the location value should be "Unspecified" in the "Responsible positions" section

**Screenshots**
Unavailable

**Environment (please complete the following information):**
 - Firefox 78.2.0esr (64-bit)

**Additional context**
None

**Comment by gjvoosten** [comment]
Was already fixed in NCI-Agency/anet#3269 (which _just_ didn't make it into the latest release but will be in the next).

**Comment by cemalettin-simsoft** [comment]
Reopened so that new fix will close this.
