### ISSUE TITLE
Meeting duration is missing from the e-mail report

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3335]
**Describe the bug**
The meeting duration (_"Duration (minutes)"_ field), which is filled in the engagement report, appears empty in the e-mailed report.

User expects this field present in the report, with value as filled in the engagement report.

**Comment by cemalettin-simsoft** [comment]
Can this be because of the dictionary field `engagementsIncludeTimeAndDuration` in `anet-dictionary.yml`?

**Comment by midmarch** [comment]
> Can this be because of the dictionary field engagementsIncludeTimeAndDuration in anet-dictionary.yml?

Thank you for quick reply @cemalettin-simsoft!

The `anet-dictionary.yml` contains the following:
```yml
engagementsIncludeTimeAndDuration: true
```
Does this answer your question?

**Comment by cemalettin-simsoft** [comment]
> > Can this be because of the dictionary field engagementsIncludeTimeAndDuration in anet-dictionary.yml?
> 
> Thank you for quick reply @cemalettin-simsoft!
> 
> The `anet-dictionary.yml` contains the following:
> 
> ```yaml
> engagementsIncludeTimeAndDuration: true
> ```
> 
> Does this answer your question?

Yes it does, just wanted to cover the base case.
