### ISSUE TITLE
Access control for certain custom fields

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3342]
Certain custom fields should only be visible to people in an authorizationGroup and counterparts (in case of People) and to people in an authorizationGroup and authors (in the case of Reports).

We could add an optional `authorizationGroups` parameter under `customField`, that specifies the list of uuids of authorization groups.

We will also need some visual indicator on these fields to convey that they are not visible to everyone.

Maybe, it is wiser to store the uuid of the autorization group in the json of the value itself to ensure future access control.

Steps to resolve this issue:

- [ ] Define User Stories.
- [ ] Write all requirements and clarify unclear requirements.
- [x] Write up the architecture of the data and the security rules that apply to it according to the requirements.
- [x] Create the data model (server-side)
- [x] Implement the security rules (server-side)
- [x] Add the sensitive custom fields to the objects that need them (server-side)
- [x] Add some sensitive custom fields to the demo data (server-side) and add tests (server-side)
- [ ] Mock-up of how the sensitive custom fields would work on the client-side.
- [ ] Retrieve sensitive custom fields with an object from the server (report is the most likely target) and show them on the client-side.
- [ ] Edit sensitive custom fields with an object on the client-side and update them on the server.
- [ ] Add client-side tests.

**Comment by cemalettin-simsoft** [comment]
Depends on #3235 for person fields, in that PR i have changed field logic which can easily be used to implement access control for client side.

**Comment by midmarch** [comment]
Sensitivity of fields must be dealt with on the server side. This means, for this story it requires a change in the back-end to ensure no data is exposed without required access. This part need some thoughts.
