### ISSUE TITLE
Edit existing periodic assessments

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3352]
Currently, to make periodic assessments, we display a button that says `Make an assessment for period $%#...`.
The behavior should be:
- if there is already an assessment for that period, the button should say `Update the assessment for period $%#...`.
- in that case, the assessment editor should be populated with the values of the existing assessment
- when submitted, we should update that assessment instead of making a new one.

That was at least at some point the intended behavior. Not sure if the current behavior is a bug or if we never got to implement it as such.

**Comment by cemalettin-simsoft** [comment]
Can you give details about who should have access to editing existing assessments?

**Comment by cemalettin-simsoft** [comment]
Author of the assessment can already edit their own assessments, i will also give access to admins as well, which was implemented server side but forgotten in client side.

**Comment by gjvoosten** [comment]
> Authors of the assessments can already edit their own assessments, i will also give access to admins as well, which was implemented server side but forgotten in client side.

Well, originally that was so the admin can edit _regular_ (text) notes made by anyone (that client-side bit of functionality _is_ there already); the question remains who exactly can edit assessments. The admin should most likely be one of them, but who else? @VassilIordanov

**Comment by VassilIordanov** [comment]
I suggest anybody who can create an assessment can also edit it
