### ISSUE TITLE
HTML containing text in assessment fields is not rendered properly in notes panel

### ISSUE THREAD

**Issue by ysf-simsoft** [NCI-Agency/anet#3355]
**Describe the bug**
For the `RelatedObjectNotes` with type `NOTE_TYPE.ASSESSMENT`, `jsonFields` object may contain fields with html content in it; particularly for assessment questions with `"type":"special_field"` and `"widget":"richTextEditor"`. Such fields are not properly displayed in notes panel.

**To Reproduce**
1. Open create report form.
1. Pick a past engagement date.
1. Select effort 1.2.B
1. Fill out Detail levels under Efforts engagement assessments
1. Submit report
1. Open Notes side panel on the right of the Report show page.

**Expected behavior**
Assessments text in notes panel should be rendered as html.

**Screenshots**
![image](https://user-images.githubusercontent.com/62024178/101896968-df39e000-3bba-11eb-96e3-c5332050f0dd.png)

**Environment (please complete the following information):**
 - Browser Chrome, Firefox

**Additional context**
 -

**Comment by cemalettin-simsoft** [comment]
There is already an open issue for this , see https://github.com/NCI-Agency/anet/issues/3065. Unless this is about something different, i suggest we close this issue.

**Comment by gjvoosten** [comment]
Closing as duplicate.
