### ISSUE TITLE
Be able to unpublish report

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3459]
**Description**
It happens that a report gets approved, for one reason still need to changed afterwards. Exceptional maybe, but it happens from time to time. At this point level 3 support receives a request to manually change the report to draft in the database.

**Proposed solution**
An ANET administrator has an "Back to draft" button. This gives the ANET administrator the means to execute this administration himself.

Probably good to protect this action with additional warning / confirmation, e.g. "Are you sure you want to put this report back to draft. Be aware this report will be no longer accessible for other users."

**Alternatives I've considered**
Put the report back in draft via SQL command, yet this also imposes risks damaging the database.

**Additional context**
The current "contract" with external systems using ANET published reports, is that published report in [immutable](https://en.wikipedia.org/wiki/Immutable_object).   

That means we should not make any changes to a report which have been published. We could consider releasing an updated report as new release. Currently the uid between engagement & report is shared, so that would require to have different uid for the report and change to 1-to-[0..1] relation ship in 1-to-[0..n].

**Stories:**
- [x] #3480: Add a back "Back to draft" button 
- [x] #3754: Split engagement and report unique-identifier, and release a report being re-published as a new report, replacing the previous release

**Comment by dspCarlson** [comment]
@midmarch This will be an excellent feature.  This is actually a fairly common request but can only be accomplished using queries.

**Comment by VassilIordanov** [comment]
Current implementation meets the proposed behavior as defined in #3754
