### ISSUE TITLE
Users listed as 'active' due to background process

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#3462]
**Describe the bug**
The background process that checks whether ANET is still alive and/or has a newer version (NCI-Agency/anet#3020) makes users show up as 'active' in the admin interface (NCI-Agency/anet#3019), even though they're not really using ANET.

**To Reproduce**
1. Log in to ANET as a regular user
2. Keep the browser/tab open, but don't use ANET any further
3. In another browser, log in to ANET as admin
4. Check the Recent users & activities; every minute the regular user will have a new activity

**Expected behavior**
The background process should not make the user 'active'.

Related to
- #3880

**Comment by cemalettin-simsoft** [comment]
I think this would be best resolved in the server-side, make the polling mechanism implemented in https://github.com/NCI-Agency/anet/pull/3381 a non-activity, filter unwanted background processes. The client-side solution would be check "mousemove", "scroll", "keypress" events and see if the user is active, when he is, poll the server. ( Which to me looks uglier as a solution)
