### ISSUE TITLE
Time between between submission of information from the unclassified application (MART), to the creation of draft report in ANET (high side) should be less than one minute.

### ISSUE THREAD

**Issue by ATILLAM67** [NCI-Agency/anet#3476]
### **The duration measured cover **

- From submission of a report from MART
- To availability of report on ANET database as a Draft'

### **The duration might exclude **

- Exchange Server(High Side) processing @Yakup.Yildirim please check
- Diode processing (High and Low Side)
- 
Associated to [GitLab MART](https://gitlab.dev.nato.int/anet/mart/-/issues/24)

**Comment by midmarch** [comment]
@ATILLAM67 this is non-functional requirements which does not belong here.
