### ISSUE TITLE
Add a back to draft capability for published reports

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3480]
User story part of Epic #3459.

**Description**
It happens that a report gets approved, for one reason still need to changed afterwards. Exceptional maybe, but it happens from time to time. At this point level 3 support receives a request to manually change the report to draft in the database.

**Additional requirements **
- We can remove this functionality via the `anet.yml` file, which is enforced by the server side as well to prevent possible abuse
- Only ANET administrators shall be able to use this function

**Proposed solution**
An ANET administrator has an "Back to draft" button. This gives the ANET administrator the means to execute this administration himself. 

Note that this function should not be used in a scenario in which ANET reports are shared with external systems. This will lead to inconsistency of the published report.

Open questions:

- Should administrators be able to _unpublish_ a future engagement report? Administrators can't manually _publish_ a future engagement report, but the `ReportPublicationWorker` does automatically publish future engagement reports. So these two are conflicting a little. Either an admin should also be able to publish (and unpublish) future engagement reports, or the publication worker should not publish future engagement reports. Which of the two should it be?
- Do we need a reason supplied with an unpublish action (like with rejectReport)?
- Do we need to send email when unpublishing a report, and if so, to whom (e.g. the authors)?

Initial implementation will take the answer to the first question to be Yes and to the last two questions to be No.

**Comment by cemalettin-simsoft** [comment]
We shouldn't forget to reset report's workflow to what it should look like in a draft version.
