### ISSUE TITLE
Conditions Where Report Authors Should Not Be Able to Create Reports

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#350]
Report authors should not be able to create engagement reports when:
1. The report author is not assigned to a position
2. The report author's profile has an "Inactive" status
3. The report author's end of tour date has already passed
4. The report author is assigned to a position, but the position has an "Inactive" status
5. The report author is assigned to a position, but the position is not assigned to an advisor organization
6. The report author is assigned to a position, the position is assigned to an advisor organization, but the advisor organization does not have a report approval chain

In each case, the "Create report" button should be available to the report author.  However when the report author clicks the "Create report" button, the appropriate error message(s) should be displayed.

Reference item 127

**Comment by VassilIordanov** [comment]
At least for the time being, we will attempt not to restrict anybody's ability to create reports.

Upon closing this ticket:
- #351 is updated to include some of the above conditions 
- #355 is created to improve assignment of advisors to organizations
- #356 is created to help direct users wanting to experiment / train to a non-production environment
