### ISSUE TITLE
Conditions Where Report Authors Should Not Be Able to Submit Reports for Approval

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#351]
Report authors should not be able to submit reports for approval when:

Primary Advisor Attendee:
1. The primary advisor attendee is not assigned to a position
2. The primary advisor attendee's profile has an "Inactive" status
3. The primary advisor attendee's end of tour date has already passed
4. The primary advisor attendee is assigned to a position, but the position has an "Inactive" status
5. The primary advisor attendee is assigned to a position, but the position is not assigned to an advisor organization
6. The primary advisor attendee is assigned to a position, the position is assigned to an advisor organization, but the advisor organization does not have a report approval chain

Primary Principal Attendee:
1. The primary principal attendee is not assigned to a position
2. The primary principal attendee's profile has an "Inactive" status
3. The primary principal attendee's end of tour date has already passed (if the primary principal attendee has an end of tour date)
4. The primary principal attendee is assigned to a position, but the position has an "Inactive" status
5. The primary principal attendee is assigned to a position, but the position is not assigned to a principal organization

In each case, the report author is able to create a report.  The report author can also click the "Preview and submit" button.  However when the report author clicks the "Submit report" button, the appropriate error message(s) should be displayed.

Reference item 128

**Comment by VassilIordanov** [comment]
partially addressed in #264

**Comment by VassilIordanov** [comment]
to be consolidated with clapmp-down requirements

**Comment by VassilIordanov** [comment]
Seems mostly done. We need to confirm if something is or is not done
