### ISSUE TITLE
Automatically purge stale pending emails

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#353]
A new property should be defined in the anet.yml, named something like purgeStalePendingEmailsOlderThan, with a time period parameter.

The email worker should check if that property is defined and then it should purge all emails that are older than that period.

**Comment by dspCarlson** [comment]
Looking through the logs, the users are inputting incorrect email addresses when sharing a report with someone else.  A lot of the invalid email addresses appear to be a poor job of cut and paste.
