### ISSUE TITLE
Reminder emails for monthly leadership assessments are being sent to positions that don't have an advisor assigned

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3543]
**Describe the bug**
An advisor has redeployed.  The outgoing advisor's profile becomes inactive and the advisor's former position is vacant.  However, because the Active Directory accounts are role-based (and not name-based), an incoming advisor assumes the outgoing advisor's AD account and email address.  The incoming advisor does not create an ANET profile and the outgoing advisor's position stays vacant.  However, at the first of the month, the incoming advisor receives reminder emails to assess his/her principal counterpart.

**To Reproduce**
Condition 1: An (outgoing) advisor has redeployed.
Condition 2: The outgoing advisor's profile is set to inactive.
Condition 3: The outgoing advisor's position is vacant, i.e. another advisor is not assigned to the outgoing advisor's former position.
Condition 4: The outgoing advisor's position had one or more principal's assigned.
Condition 5: The outgoing advisor's AD account is role-based.
Condition 6: An incoming advisor is assigned to the outgoing advisor's AD account and assumes the outgoing advisor's email address.
Condition 7: The incoming advisor does not create an ANET profile.
Condition 8: It is the first of the month.

Result/Bug: The incoming advisor receives a reminder email to assess their principal counterpart.  However the incoming advisor does not have an ANET profile and as such is not assigned to an advisor position.

**Expected behavior**
Incoming advisors that have not created an ANET profile, should not receive ANET leadership assessment reminder emails 

**Screenshots**
None

**Environment (please complete the following information):**
Unknown

**Additional context**
This happened to two advisors.  Both of their predecessors had ANET profiles and were assigned to advisor positions.  For some reason, the incoming advisors did not create ANET profiles.

Good thing the ANET support email is displayed at the bottom of the reminder email.

**Comment by gjvoosten** [comment]
It was a timing issue. At the moment the PendingAssessmentsNotificationWorker ran, the outgoing advisor was still assigned, so the email was sent to that email address. The incoming advisor, when opening that email account, saw that message in their INBOX.

**Comment by dspCarlson** [comment]
This was not a bug.

The reminder email was sent 1 April.

The outgoing advisor's ANET profile was inactivated on 3 April.

The incoming advisor had already assumed the outgoing advisor's email account.
