### ISSUE TITLE
Update the ability of super users to modify principal organizations

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#36]
Currently, a principal organization needs an official name, colloquial name, unit identifier, and parent organization. #200 is working to add a description. 

We should change the edit permissions to:
Super users can only edit the colloquial name and (once avaialble) description. 
Administrators edit the organization type, official name, unit identifier and parent organization in the addition to the above. 

This is issue is related to #36, #49, and #103.

**Comment by VassilIordanov** [comment]
@dspCarlson, I've changed the description om the top to summarize the behavior, please validate

**Comment by dspCarlson** [comment]
@VassilIordanov I agree with your description with one addendum.  To summarize principal organization responsibilities:

Administrator responsibilities:
1. Create principal organizations
2. Edit official name, unit identifier code and parent organization

Super user responsibilities:
1. Edit colloquial name and description (once the description field is created).

Addendum:
The official name should now be returned in searches and should be the primary principal organization name viewed.
