### ISSUE TITLE
Remove Advisor Position from Report Approval Chain Step(s) if a User is not Assigned to the Advisor Position

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#362]
If an advisor is not assigned to an advisor position, remove the advisor position from any approval steps.  An example would be if an advisor's profile status is set to "Inactive," remove the advisor's position from all report approval steps.

Having an advisor position in the report approval chain without a name confuses the super users.  Advisor positions are also left unassigned for months.  Furthermore, advisor positions are not indicative of being assigned to an approval step.  This is especially true if the person assigned to a position does not have good English skills (for approving reports).

Reference item 130

**Comment by dspCarlson** [comment]
As of 19 August 2018, there are 51 distinct advisor positions without a current person assigned that are assigned in 67 approval steps

**Comment by jose-west** [comment]
After consulting with @VassilIordanov decided to mark vacant positions in approval steps as 'Unfilled' (just like the section with vacant positions), instead of automatically removing these steps when deactivating a user.
