### ISSUE TITLE
Implement a better "rank" dropdown menu

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#37]
I suggest a interactive hierarchical menu
Reference item 36

**Comment by dspCarlson** [comment]
@VassilIordanov  How about enhancing the drop-down menu with more data?

For example:
OF-2 (Captain, (Navy) Lieutenant
OF-3 (Major, Lieutenant Commander)

However, once a value is chosen from the drop-down menu, only the rank nomenclature is displayed.
