### ISSUE TITLE
Define "unpublish report" process

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#3754]
Part of Epic #3459: Split engagement and report unique-identifier, and release a report being re-published as a new report, replacing the previous release.

We should define what happens when a report is unpublished, e.g.:

1. Does the unpublished report get a new state ("ARCHIVED")? This goes against the immutability of published reports. Yet somehow we have to indicate that this published report is going to be replaced…
2. Does the new draft report initially get all the contents of the unpublished report?
3. How do we relate this new draft report to the unpublished report? E.g. without changing the data model, we can define custom fields that contain a link to another ANET report ("this report is replaced by: <uuid of draft report>" on the unpublished report, and "this report replaces: <uuid of unpublished report>" on the new draft report), but again: this would change the published report.
4. What happens when the author deletes this new draft report? Does the unpublished report become published again?

But maybe we should first answer the question: must published reports really be immutable? Wouldn't it simplify things if we would just drop that limitation?

**Comment by VassilIordanov** [comment]
As discussed, the proposed way ahead is:
- Published reports are no longer immutable, their state can be flipped back to draft
- That history is captured in the workflow history of the report
- If/when needed to guarantee uniqueness, an alternative mechanism will be elaborated to identify a version of a published report - possibly UUID of the report + the UUID of the latest workflow entry
