### ISSUE TITLE
Ensure location types fits all missions

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3782]
1. Make sure there is no dependency on distiction of advisor & principle (their counter parts) locations. Assume the same locations can be the shared amongst them.
1. Automatically migrate positions to virtual & pinpoint locations

Related: 
- #3834

**Comment by HK-Simsoft** [comment]
Automatically migrating location types is discussed at DSU. It is decided not to make any change at database migration file. Deployed application admins should correct their locations's type manually via sql statements if the current migration policy is not suitable for their application.
