### ISSUE TITLE
Support different question sets in assessment

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3849]
Support diffferent question sets in the assesment.

Let's say the first question is: "_Please provide the role of interpreter?_"
- A: Translating
- B: Advising

Depending on the role picked, A or B, a different question set me be provided.

Ensure that:
- The question which determines which question set is also part of the assesment 
- The same question may still exist both in A and B. So they presented as one result. 

Related to:
- #3802
- #3848
- #3850

**Comment by anilsonmez-simsoft** [comment]
I think this can be set through the dictionary.
