### ISSUE TITLE
Prevent users from renaming people to another person

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#385]
Phase I:

Prevent anyone besides Admins of changing an advisor name. When editing a Person, the name field for adivisors should apprear as an editable widget only to admins

Phase II:
Implement the following:
- Next to the non-editable name field, display a "This is not me" (when user is editing him/herself) or "This is not {user.name}" (when a superuser is editing an advisor) button. 

In the case of  "This is not me", when clicked on that button, the user should be presented with the following message and choices:
  - "It is possible that the information of user {user.name} is out of date. Please help us identify if any of the following is the case: "
    1. "User {user.name} has left this position and is replaced by me. I need to set up a new account"
    2. "User {user.name} has left this position and is replaced by me. I already have an account"
    3. "User {user.name} is still active, but this should be my account"
    4. "I am {user.name}, by my name is misspelled"
    5. "Something else is wrong"

When the user clicks on i, and after another confirmation, the current user's domain name should get reset, he should be removed from that position, and the user should be directed towards onboarding (and possibly associated with the position). In all other cases, an admin should be emailed.

In the case of  "This is not  {user.name}", when clicked on that button, the superuser should be presented with the following message and choices:
  - "It is possible that the information of user {user.name} is out of date. Please help us identify if any of the following is the case: "
    1. "User {user.name} has left this position and the position is vacant"
    2. "User {user.name} has left this position and he has a replacement"
    3. "I am {user.name}, by my name is misspelled"
    4. "Something else is wrong"

When the superuser clicks on i or ii, and after another confirmation, the user's domain name should get reset. In all other cases, an admin should be emailed.

**Comment by dspCarlson** [comment]
I think the possibilities are covered.

Referring to a position when the user is at the person's page might be confusing.  The position information is below the person information and is not necessarily visible.  Users also transfer positions frequently.  For example "User {user.name} has left this position and is replaced by me."  How about "User {user.name} has left and is replaced by me"

**Comment by gjvoosten** [comment]
@dspCarlson For the two different cases, would the following interactions work, i.e. are the options phrased clearly enough?

1. "this is not me"
![screenshot - 150218 - 17 06 28](https://user-images.githubusercontent.com/445238/36266926-03362c3a-1273-11e8-8a70-1804627cdbd7.png)

2. "this is not {LASTNAME, Firstname}"
![screenshot - 150218 - 17 07 15](https://user-images.githubusercontent.com/445238/36266941-07739bd4-1273-11e8-9d0a-7bd066664257.png)

**Comment by dspCarlson** [comment]
@gjvoosten I have a question on the line below:
iii. "User {user.name} is still active, but this should be my account"

What does "still active" mean?  Does that mean the person is still working in theater, but has another job/position in theater?  If so, I would say:
"User {user.name} is still in theater but no longer uses this Windows logon.  I have assumed the Windows logon."

Role-based domain users refer to having taken over their predecessors Windows login.  The message will also work with name-based domain users too.  It should be clear to name-based domain users that they haven't assumed the other persons logon.

**Comment by dspCarlson** [comment]
@gjvoosten 
i. "User {user.name} has left and is replaced by me.  I need to set up a new account"

I would suggest:
i. "User {user.name} has left theater, is no longer advising and is replaced by me. I need to set up a new account"

There are different interpretations of what "left" means.  Has the person left their former advisor position and assumed another advisor position?  Has the person left that location and gone to another location.  Has the person left the theater.  (Actually I believe it is spelled theatre.)

**Comment by dspCarlson** [comment]
@gjvoosten 
ii. "User {user.name} has left and is replaced by me. I already have an account."

I would suggest:
i. "User {user.name} has left theater, is no longer advising and is replaced by me. I already have an account."

**Comment by VassilIordanov** [comment]
Implemented, email actions to be added in #367
