### ISSUE TITLE
Ability to monitor number of users

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3880]
I need the ability to be able to see:

To have a solid understanding by how many users ANET is used, and if the number of users are changing over time, I need to know the following information:
- How many (unique) users did we have per day, per week, per month, including history. 
  
It would also be good to be able to devide the users per organizational unit, so we understand usage per organizational unit.

Related (although, different meaning of active user):
- #3462

**Comment by HK-Simsoft** [comment]
@midmarch Will these numbers refer to active users or new users or total users?
How will numbers be calculated? (For example per week active users means the number of users that are active at least once in a week.)

**Comment by midmarch** [comment]
What we count as an "active user", is any user who authenticated with success and accessed the ANET application (so any authenticated requests to the server counts as being active).

Only important aspect is not to count the same user twice.
