### ISSUE TITLE
Automate windows service deployment

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#390]
- [ ] bundle ANET with https://nssm.cc/ and evaluate how that goes
- [ ] create an upgrade powershell scripts that does (possibly remotely)
    - upload `anet.X.X.XXX` distribution to remote server
    - stop ANET service with `net stop anet`
    - backup ANET database
    - move `{$ANET_DIST)/bin`, `{$ANET_DIST)/doc` and `{$ANET_DIST)/lib` to `c:\ANET\nackups\Upgrade_to_X.X.XXX` backup directory
    - unzip distribution into {$ANET_DIST)
    - execute `bin/anet check` and `bin/anet db migrate' 
    - start ANET service with `net start anet`
- [ ] update installation documentation

**Comment by maradragan** [comment]
Added to #1971
