### ISSUE TITLE
JDBI inTransaction usage breaks SQLite (also postgresql)

### ISSUE THREAD

**Issue by benwarfield-usds** [NCI-Agency/anet#391]
The current JDBI inTransaction usage breaks SQLite and Postgresql in a couple of different ways:

* for both databases, launching an `inTransaction` call when already inside a transaction causes an error: in SQLite it is an immediate `org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)`, in Postgresql it is a "can't commit when session is in autocommit" error when the outer transaction closes
* for SQLite only, the construction pattern of AnetEmailWorker causes a similar breakage: because the email worker has a different handle than the DAOs, when we attempt to send an email from inside a transaction (for example in `ReportResource.rejectReport` or `ReportResource.approveReport`), we end up with the SQLITE_BUSY error again, because one handle is holding an exclusive lock on the file and the other wants to do a read, and they're going to deadlock.

I'm currently working on a fix for the first issue (refactoring to avoid nested inTransaction calls), which appears effective. The second issue needs a little more care, but there are two obvious solutions:

1. move all "send${SOME}Email" calls outside of transactions. This seems easy at first, but there are actually some calls fairly far inside of `approveReport` that would need to be extracted, so it's not trivial, though perfectly doable
2. make AnetEmailWorker share the same DB handle as everybody else, possibly by extracting the JDBI calls into an EmailDao that is constructed as part of the object engine.  This seems totally reasonable and easy, which makes me worry that there's a side effect that I haven't considered.

In the absence of feedback, I'm going to work on solution 2 above, because it seems less disruptive and relies less on a convention that people would have to remember. If that's the wrong idea, somebody please let me know. 😸

**Comment by gjvoosten** [comment]
@benwarfield-usds Option 2 seems like the most sensible solution. Maybe change the `FutureEngagementWorker` as well, since that also uses another separate handle (so currently there are three separate calls to `jdbi.open()`). So in short, the attached change.
[dbhandle.txt](https://github.com/NCI-Agency/anet/files/1642116/dbhandle.txt)

**Comment by benwarfield-usds** [comment]
Oh, good call.  That one's even easier—I have them both working locally now, I'll push them up for a separate PR once I disentangle some branches.

**Comment by benwarfield-usds** [comment]
Opened the PR against the branch in #374.
