### ISSUE TITLE
Inconsistency in advisor-organization assignment/error messaging

### ISSUE THREAD

**Issue by benwarfield-usds** [NCI-Agency/anet#392]
This is probably an issue with an error message, but it may reflect a logical error in report management.  Short version: we have an error message in `ReportResource.submitReport` (generated by the utility method `throwExceptionNoApprovalSteps`) that refers to the Advisor Organization for a particular report, but the logic that drives the error actually checks the organization of the the author of the report, not the org in the advisorOrg field.

Long version:

In `ReportResource.createNewReport`, we set the advisorOrg field as follows:
* if the advisorOrg field is be sent in the request, use that org
* if it is not, find the primary advisor in the attendee list (if present) and use that person's organization

In `editReport`, the following can happen:
* if the primary advisor has changed from the original report, then set the advisor organization to the new primary advisor's organization

In `submitReport`, however, we check the approval steps as follows:
* find the organization for the report _author_, and use that organization's steps
* if the organization has no approval steps, raise an error saying: "Advisor organization is missing a report approval chain. In order to have an approval chain created for the primary advisor attendee's advisor organization, please contact the ANET support team".

**Comment by benwarfield-usds** [comment]
Possible fixes:
* change the error message to say "your organization" instead of "Advisor organization"
* change the logic to set the advisor org to the author's organization if it isn't otherwise set, but then check the advisorOrg field rather than going directly to the author's org.

**Comment by VassilIordanov** [comment]
@dspCarlson what do you think of this one? I think we should be basing this on the Author's org and rename the error message to reflect as Ben suggests

**Comment by dspCarlson** [comment]
In submitReport, the report author's advisor organization should not be checked.  The primary advisor attendee's advisor organization (i.e. reports.advisorOrganizationId) should be checked.

It is the primary advisor attendee who determines the report approval chain, not the report author.  Nine times out of ten, the report author is also going to be the primary advisor attendee.

If the primary advisor attendee's advisor organization does not have a report approval chain, the report is sent to the default approvers.  The ultimate goal is to prevent engagement reports being sent to the default approvers.

Also, the last part of the message should be changed.

Currently:
_In order to have an approval chain created for the primary advisor attendee's advisor organization, please contact the ANET support team._

Proposed:
_Contact the super users of <advisor organization name> to have a report approval chain created._

If possible, maybe list the super user names.

Creating report approval chains is a super user responsibility.
