### ISSUE TITLE
Duplicate Advisor Organizations Created

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#405]
I created an advisor organization at 05:01:50:258 (per the auditLogger log file date/time stamp).  A duplicate advisor organization was created at 05:01:50.664 (per the auditLogger log file date/time stamp).  That's .406 second of a difference.

I was NOT able to recreate the bug in Staging.

Reference item 135

**Comment by VassilIordanov** [comment]
unable to reproduce at this point
