### ISSUE TITLE
Error when creating a task without status

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#428]
When creating a task and not filling in the status you get an error like: 

Internal Server Error: There was an error processing your request. It has been logged (ID fa135e4fcfce761e).

**Comment by gjvoosten** [comment]
Error is:
> Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert the value NULL into column 'status', table 'tasks'; column does not allow nulls. INSERT fails.
