### ISSUE TITLE
Console error on advanced search

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#429]
When using advanced search on tasks, in the following context:
    - I do a search on search term xxx
    - I now do a new search on search term yyy
At this moment I see the following error in the console "You must not store functions in location state"

**Comment by maradragan** [comment]
This only happens when: 
- doing this via the advanced search on the top of the page

**Comment by maradragan** [comment]
This doesn't happen: when doing the same actions in the search form on the page.

**Comment by maradragan** [comment]
It also happens on the people search tab, actually it happens on all search tabs which have more than the search term as filter. On the reports tab it doesn't happen and if we remove all filters eacht time we search it also doesn't happen on other tabs.

**Comment by gjvoosten** [comment]
No longer happens on current `candidate`; most likely it was fixed by commits 7111d52, 8f14421, 8390a86.
