### ISSUE TITLE
Improve the Hop Scotch Messages

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#431]
1. Make existing data items more descriptive.  Describe the data items, but also how to use them.  For example, rank should include instructions for civilians not using equivalent military rank.

2. Add hop scotch messages for new data items like key word tags and sensitive information.

3. Ensure all pages have hop scotch messages to include differentiating messages for advisor organizations vs. principal organizations, advisor positions vs. principal positions, advisor profiles vs principal profiles.

Specific hop scotch messages to follow....

Reference item 136

**Comment by maradragan** [comment]
Added to #1595
