### ISSUE TITLE
Dashboard for New Users Displays the Number of All Released Engagement Reports

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#440]
When onboarding in production or staging, the new user's dashboard displays all ANET released (?) reports.  The number is listed twice in the two right quadrants.

I have emailed Vassil a screen shot on the high side.

**Comment by gjvoosten** [comment]
Reproducible in the development environment. After filling in the profile, the user is taken to the front page (with the hopscotch tour) where this is indeed the case, see screenshot.
![screenshot - 060218 - 13 36 42](https://user-images.githubusercontent.com/445238/35860066-d5c5a190-0b42-11e8-9c5f-5a5384e70dd1.png)

**Comment by gjvoosten** [comment]
Found & solved in development:
![screenshot - 060218 - 13 48 30](https://user-images.githubusercontent.com/445238/35860471-74f6ff74-0b44-11e8-9356-a3632ba62702.png)
