### ISSUE TITLE
Change Message When User Submits Report without Being Assigned to an Advisor Position

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#443]
When a report author tries to submit a report, but they are not assigned to an advisor position, the following message is displayed:

_You cannot submit a report.  Your assigned position has an inactive status.  Please contact your organization's super users and request them to assign you to a position.  If you are unsure, you can also contact the support team (<email address>)_

The message displayed should read as follows:
_You cannot submit a report.  You are not assigned to an advisor position.  Please contact your organization's super user(s) and request to be assigned to an advisor position.  If you are unsure, you can also contact the ANET support team (<email address>)._

I have sent two graphics to @VassilIordanov 's email account.

**Comment by gjvoosten** [comment]
There are now two possible conditions:

1. the report author is not assigned to a position
2. the report author is assigned to an inactive position

In case 1 we show:

> You cannot submit a report: you are not assigned to an advisor position.
> Please contact your organization's super user(s) and request to be assigned to an advisor position.
> If you are unsure, you can also contact the support team at support@example.com.

and in case 2 we show:

> You cannot submit a report: your assigned advisor position has an inactive status.
> Please contact your organization's super users and request them to assign you to an active advisor position.
> If you are unsure, you can also contact the support team at support@example.com.
