### ISSUE TITLE
Principal Organization Information is Displayed Incorrectly

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#448]
When viewing a principal organization on the organization's page, the following is displayed incorrectly:
1.  The "Type" displayed is "Advisor Organization" instead of principal organization
2.  UIC is displayed in the "Official Organization Name" field
3.  The official name is displayed in the "UIC" field
4.  Nothing is displayed in the "Name" field 

However, when the principal organization is edited all data are in the correct fields.

This bug applies to all principal organizations.

**Comment by VassilIordanov** [comment]
1,2,3 are fixed
Unable to reproduce 4
