### ISSUE TITLE
Ability to inactivate Organizations and Locations

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#451]
Both advisor organizations and principal organizations have been restructured or are currently being restructured.

Many organizations are no longer viable and obsolete.  ANET administrators must have a way to make organizations inactive.

The closest way to make organizations inactive is to remove the parent organization.  The organizations are then more difficult to find.

**Comment by VassilIordanov** [comment]
Is there anything else that needs an inactivate feature added?

**Comment by dspCarlson** [comment]
Maybe locations should also be inactivated.  Locations do become obsolete. @VassilIordanov  What do you think?

The following ANET objects can already be inactivated:
Advisor
Advisor position
Principal
Principal position
Tasks

The following ANET objects do not need to inactivated:
Reports
Report approval chain

The following ANET objects will be inactivated in a future release:
Advisor organization
Principal organization

This accounts for the 10 ANET objects.

**Comment by VassilIordanov** [comment]
I suggest that: Both Locations and Organizations are given an inactive status.
As elsewhere in the UI, when users attempt to access these through autosuggest, only active results should be returned
