### ISSUE TITLE
Cannot Submit Report Because Message States Advisor Position is Inactive

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#453]
Trained a new user today.
1. The user created a profile
2. The super user assigned the new user to an advisor position
3. The new user tried to submit a report
4. A message was displayed saying the advisor position was inactive
5. The new user could not submit a report.

The advisor position was not inactive; the advisor position was active.

Screenshot emailed to @VassilIordanov

**Comment by VassilIordanov** [comment]
I suggest we close it as it is no longer manifesting itself
