### ISSUE TITLE
Wrong Filler for the "Meeting goal (purpose)" Field on a New Report

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#454]
The filler text for the "Meeting goal (purpose)" field on a new report is "What happened?"  The words are past tense and should be future tense.

The filler text should be "What is the engagement supposed to achieve?"

**Comment by VassilIordanov** [comment]
Shouldn't it be in past tense for a past engagement and in future tense for a future engagement?
And aren't most engagement reports about past engagements?
