### ISSUE TITLE
Add an identification code filter to advanced search for principal organizations

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#467]
Currently to search on the identification code, the user has to use the "Search term" data field. It would be more intuitive for the users to have a unique filter.

(from https://github.com/NCI-Agency/anet/issues/200#issuecomment-345459168 )

**Comment by VassilIordanov** [comment]
@dspCarlson can you please confirm if still valid?

**Comment by midmarch** [comment]
Currently not required, and already works with PostgreSQL.
