### ISSUE TITLE
Error Message Incorrectly Displayed

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#468]
Was working with a super user this morning.  He was trying to remove the relationship between an inactive advisor position with a principal position.  When he clicked the "Save" button, he received an error message that he didn't have permissions to do the action.  But yet the relationship between the advisor position and principal position was removed.

The advisor position was indeed assigned to the super user's advisor organization.  Will send @VassilIordanov an email of the screenshot of the error.

**Comment by gjvoosten** [comment]
@dspCarlson The relationship was not actually deleted (pressing F5 _Refresh_ will show the original link again). It looks like a display error (inconsistent data on the client-side) that should be corrected.
