### ISSUE TITLE
Client-side error - 'focus' 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#469]
Error captured in client log for 2.0.13
main.1f692e8d.js 16:29335 Object does not support property or method 'focus' 
it happens about 30 times per day

**Comment by gjvoosten** [comment]
@vassil Do you have the statement (preferably unobfuscated) in the JavaScript where this happens?

**Comment by VassilIordanov** [comment]
@gjvoosten no, it is not possible to have this in the raw logs. but the obfuscated info should be enough for us to track this down. 
#401 changes how the code is chunked and how source maps are done. Once we transition to it, I'll look at how to automate so that we can do (`chunk`+`line:colon`+releaseTag)=>source code pointer. Until then, we have to do it manually

**Comment by VassilIordanov** [comment]
on wait until #501 further explored

**Comment by gjvoosten** [comment]
Does this still happen since 2.0.18(.1) i.e. with Recat 16 merged?

**Comment by VassilIordanov** [comment]
closed due to lack of new reports
