### ISSUE TITLE
Client-side error - 'id' 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#470]
Captured by server-side logging in 2.0.13

main.1f692e8d.js 47:4418 Unable to get property 'id' of undefined or null reference

happens about 5 times / day

**Comment by gjvoosten** [comment]
@vassil Do you have the statement (preferably unobfuscated) in the JavaScript where this happens?

**Comment by gjvoosten** [comment]
Does this still happen since 2.0.18(.1) i.e. with the React 16 upgrade merged?
