### ISSUE TITLE
Cannot Assign Principals to Advisors

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#479]
Cannot assign a principle to an advisor from the advisor's page or the advisor's position page.  An error message is displayed.

However, you can assign an advisor to a principal  from the principal's page and the principal's position page.

**Comment by gjvoosten** [comment]
@dspCarlson Preconditions for being allowed to do this are:

- if the position permissions are Admin or Super User, the user must be an Admin
- position must have an organization
- user must be Super User (or Admin) for the organization of the position

One of these would most likely be the case. That you then _are_ allowed to do it the other way around is indeed a bit odd; it seems like an oversight in the permissions checks.

Question is: what is the behaviour you would expect/want in this case?

**Comment by dspCarlson** [comment]
@gjvoosten This is how I think it should be done.

Condition 1: Assign a principal to an advisor
1. Super users can assign any principal to an advisor but only if the advisor is assigned to the super user's organization or a subordinate organization
2. Admins can assign any principal to any advisor
3. Assigning the principal to the advisor takes place at the advisor's profile page or the advisor's position page. 

Condition 2: Assign an advisor to a principal
1. Super users can assign an advisor to any principal but only if the advisor is assigned to the super user's organization or a subordinate organization
2. Admins can assign any advisor to any principal
3. Assigning the advisor to the principal takes place at the principle's profile page or the principal's position page.
4. Only advisors assigned to the super users organization or subordinate organizations should be displayed as possible selections. (I think this is already being done.)

**Comment by dspCarlson** [comment]
@gjvoosten Being able to assign an advisor to a principal and assign a principal to an advisor is very useful.  We also teach this flexibility when we train super users.

**Comment by dspCarlson** [comment]
Bug is fixed.  Thank you.
