### ISSUE TITLE
the "Attendees" list only returns about 25 names, but not necessarily the principal name required

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#48]
When searching for an principal to add as an attendee to a report, about 25 names are returned for selection.  But if the name starts with a letter that falls towards the end of the alphabet, the required name is not available for selection.  The "Attendees" search box appears to return records based on relevance and then in alphabetical order.
Same with "Select a person"
Reference item 48

**Comment by dspCarlson** [comment]
This item also applies when trying to assign a principal to a position.

**Comment by gjvoosten** [comment]
This is most likely already covered by the solution for #245 to sort the autosuggest list for people on search rank (most relevant hits first).

**Comment by gjvoosten** [comment]
See #255 .
