### ISSUE TITLE
Cannot Edit and Save Existing Advisor Position Information

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#480]
Today a super user received an error message when trying to save the information from an advisor position.  The error message said the super user didn't have the permissions to perform the action (or something like that).

I am pretty sure we did not change the advisor organization assigned to the advisor position.

**Comment by gjvoosten** [comment]
@dspCarlson Preconditions for being allowed to update a position are:

- if the position type is Admin or Super User, the user must be an Admin
- position must have an organization
- user must be Super User (or Admin) for the organization of the position

If the message was _"You do not have permissions to do this"_, the third condition was the case.

**Comment by dspCarlson** [comment]
@gjvoosten Both positions were in the same advisor organization.  One position was inactive.  I will try to recreate the bug in staging.  I will have to work with the super user.

**Comment by dspCarlson** [comment]
@gjvoosten This issue has happened five times since we last chatted about it.

**Comment by gjvoosten** [comment]
@dspCarlson Anything that could help in reproducing this? Note that if the position is an Admin or a Super User and the person editing it is Super User, they cannot actually see the permissions of the position (only **Permissions** _NATO Billet_ is shown; the other buttons are hidden).
They _will_ however get an error when trying to save the position.

**Comment by dspCarlson** [comment]
This bug has not presented itself since February 2018.  I was conducting desk-side training with the super user when the bug occurred.  However, since I was at another location, I was not able to fully investigate the bug in a timely manner.

I am closing this issue and removing it from the Bugs project.
