### ISSUE TITLE
Advanced search: Cannot find advisor position if "Position type" is used as a filter

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#484]
Success: Use Advanced search to find an advisor position without any filters.  Enter the advisor position code in the "Search term" field.  The advisor position is found.

Failure: Use Advanced search to find an advisor position and use the "Position type" filter.  Enter the advisor position code in the "Search term" field.  The advisor position is not found.

**Comment by gjvoosten** [comment]
Reproducible.

**Comment by gjvoosten** [comment]
@dspCarlson It probably means that the advisor position is a _Super User_ or an _Administrator_. The search does an exact match. Question is: what should happen in this case? Should searching for _NATO Billet_ also imply searching for _Super User_ and _Administrator_?

**Comment by dspCarlson** [comment]
@gjvoosten Just re-tested based on your comments.

I tested a super user's billet position for both conditions.  Indeed super users and administrators are not found when selecting "Advisor Billet" as a "Position type" filter.

Super users and administrators should be included in search results when the "Position type" filter is set to "Advisor Billet."
