### ISSUE TITLE
add a column for UICs in the organizations table 

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#49]
Reference item 51

**Comment by dspCarlson** [comment]
Add an "UIC" parameter in the "Advanced Search" function when searching on principal organizations.  UICs only pertain to principal organizations, not to advisor organizations.

**Comment by dspCarlson** [comment]
Completed in the 26 November 2017 release.

**Comment by gjvoosten** [comment]
Search filter is in #467 .
