### ISSUE TITLE
Client side error - reactInternalInstance

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#493]
ANET 2.0.13 gets `Unable to get property '__reactInternalInstance$8wgv8puabvai' of undefined or null reference` error in main.1f692e8d.js 17:30920

**Comment by VassilIordanov** [comment]
I'm pretty sure I copied the line wrongly

**Comment by gjvoosten** [comment]
Does this still happen since 2.0.18(.1) i.e. with the React 16 upgrade merged?
