### ISSUE TITLE
Client-side error - type

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#494]
ANET 2.0.14 gets `Unable to get property 'type' of undefined or null reference` error in main.a0e188fb.js 47:5764

**Comment by VassilIordanov** [comment]
verify line #

**Comment by VassilIordanov** [comment]
updated

**Comment by gjvoosten** [comment]
Does this still happen since 2.0.18(.1) i.e. with the React 16 upgrade merged?
