### ISSUE TITLE
Client-side error - emailAddress

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#496]
ANET 2.0.13 gets `Unable to get property 'emailAddress' of undefined or null reference` error in main.1f692e8d.js 47:5855

**Comment by VassilIordanov** [comment]
Happens in Help.js and possilbly fixed by #470, @gjvoosten can you confirm?

**Comment by gjvoosten** [comment]
Does this still happen since 2.0.18(.1) i.e. with the React 16 upgrade merged?
