### ISSUE TITLE
Client-side error - cleanWord

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#497]
ANET 2.0.13 gets `object does not support property or method 'cleanWord'` error in main.1f692e8d.js 35:21222

**Comment by VassilIordanov** [comment]
it seems like 'client/public/alloy-editor/plugins/pastefromword/filter/default.js' is not loaded
I assume this happens when pasting a document from MS Word, I do not know if this happens every time or just in some cases.

**Comment by VassilIordanov** [comment]
on wait until #501 further explored

**Comment by gjvoosten** [comment]
Does this still happen since 2.0.18(.1) i.e. with the React 16 upgrade merged?
