### ISSUE TITLE
Photos for people

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#498]
Add the ability to upload a photo for a person:
- [x] find an avatar react library
- [x] make it possible to upload a photo
- [x] change Person model (server & client side)
- [x] save the photo in the db
- [ ] display the photo in person lists

**Comment by maradragan** [comment]
We should refine this issue a bit:
- how should we persist the image: on the filesystem or in the database?
- should we do automatic scaling down of image size when saving it?
- are there any special requirements for the upload widget (github for instance, has a crop picture functionality)? 
- do we have restrictions in terms of how many MB's allowed?
- other thoughts?

**Comment by VassilIordanov** [comment]
I think that image should be persisted in DB, as png
I suggest to have it as a square aspect ratio, and downsize it to a uniform dimension (something like 200x200 or 177x177)
Crop functionality would be a plus, like in https://github.com/DropsOfSerenity/react-avatar-cropper or https://github.com/mosch/react-avatar-editor 
I suggest to convert images to 200x200 pngs, so the size should remain less than a few dozen KBs

**Comment by evdhoudt** [comment]
Reference item [27](https://github.com/NCI-Agency/anet/issues/23)
