### ISSUE TITLE
Print Advisor Engagement Report

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#50]
Advisors must sometimes have a paper copy of their engagement reports for meetings or discussions.  The favored solution would be to make an engagement report into a PDF file and then print the PDF file.  Another solution would be to have a print function to simply print out the report.
Reference item 51

**Comment by dspCarlson** [comment]
The user must be able to print the report at all six states of the report to include draft.

**Comment by gjvoosten** [comment]
@VassilIordanov @VassilIordanov Is the print style (Ctrl-P or _Print Preview…_ when viewing a report) adequate for this purpose?

**Comment by VassilIordanov** [comment]
@dspCarlson does printing reports work well enough?

**Comment by dspCarlson** [comment]
@VassilIordanov The only way I know how to print reports is to send them by email and then print the email.  The email version looks very good.
