### ISSUE TITLE
wdio tests hang

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#505]
The wdio tests hang on the printRollup test.
This happens because when clicking the print button a print dialog is also opened and that one is not being closed.

Selenium, WebdriverIO have no way of closing these dialogs (see e.g. https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/1815 ), I read about trying to override the print function to not open the print dialog.

**Comment by gjvoosten** [comment]
Yes, it's an unfortunate side-effect of my change to make printing more convenient for the user:
https://github.com/NCI-Agency/anet/blob/98ae2e9daa36a40101df376d897f427c249cc741/client/src/pages/rollup/Show.js#L406-L408

**Comment by gjvoosten** [comment]
Actually, upon further investigation, the problem is that the last line below hangs when in headless mode:
```
                        browser.switchTab(switchHandle)

                        const rollupClassification = 'p:nth-of-type(1) i'
                        browser.waitForText(rollupClassification, 3000)
```
The `switchTab` returns OK but for some reason in headless mode `waitForText` doesn't return (and the timeout isn't working). In non-headless mode it is working fine.

**Comment by gjvoosten** [comment]
And sure enough: with the latest version of Google Chrome (72.something) installed and a recent version of Chromedriver, the test passes.
