### ISSUE TITLE
graphql returned field order not the same as query request field order

### ISSUE THREAD

**Issue by jan-willemgoossens** [NCI-Agency/anet#507]
The field order in the result of a graphql query should be the same order as used in the query request (see graphql specs). 

However, the order is different:
First query:   http://anet..../graphql?...{list{id,releasedAt,intent, ….}}
My result may be:  list { releasedAt, intent, id, …………. }

After I add an extra field, for ex. http://anet..../graphql?...{list{id,releasedAt,intent,engagementDate ….}    
My result may also change the whole order as: list { id, engagementDate, intent, releasedAt, …………. }

So there is no relation between the query request order and the result order.

**Comment by gjvoosten** [comment]
For an interesting discussion, see https://github.com/facebook/graphql/issues/168

**Comment by gjvoosten** [comment]
The PR switches to a different XML marshaller. Previously we used `org.json.JSONObject` that has in the source code the following comment:
```
        // HashMap is used on purpose to ensure that elements are unordered by 
        // the specification.
        // JSON tends to be a portable transfer format to allows the container 
        // implementations to rearrange their items for a faster element 
        // retrieval based on associative access.
        // Therefore, an implementation mustn't rely on the order of the item.
```
which is unhelpful in our case. ☺
A side effect of the switch is that the top-level element of the XML changes; before you would get:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<result>
  <data>
    …
  </data>
</result>
```
After the change this becomes:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<data>
  …
</data>
```
i.e. the synthetic top-level element `result` is no longer inserted.
