### ISSUE TITLE
Could not create a new person after selecting "<Outgoing person's name>has left and is replaced by me.  I need to set up a new account."

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#515]
A outgoing user asked how to switch profiles with the incoming user.  I tested the procedure in the staging environment.  In the staging database I set myself to a user (and was no longer an administrator).

Here's the steps:
1. At the user's ANET profile page, select the blue "Edit" button at the top-right corner of the page.
2. Select the white "This is not me" button to the right of the outgoing user's name; a pop up window will be displayed.
3. Select the top choice, i.e. "<Outgoing person's name> has left and is replaced by me. I need to set up a new account."
4. Select the blue "Save" button at the bottom-right of the pop up window.  The outgoing user's status is set to inactive in the staging database.  The outgoing user's domain user name is set to NULL.  The outgoing user is no longer assigned to a position.
5. The incoming user is immediately asked to create a new ANET profile.
6. The incoming user enters their information into the profile page.
7. The incoming user selects the blue "Create profile" button at the top-right of the page.

Result:
1.  A pink message is displayed "Forbidden: You do not have the permissions to edit this person"
2. The last name and first name data fields become undeditable
3. The Email, Phone, Rank, Gender, Nationality, End of tour, and Biography data fields are still editable.

Will the incoming user be assigned to the same position as the outgoing user?

**Comment by maradragan** [comment]
I can reproduce this except point 2 from the Result part.

**Comment by maradragan** [comment]
And than, when trying again I can't reproduce it any more.

**Comment by dspCarlson** [comment]
@maradragan Two days ago a new user successfully used the sequence/scenario above.  Result 1 and 2 were not present.
