### ISSUE TITLE
Do not allow super users to add an approval step if one blank approval step is already present

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#531]
When a super user selects the "Add an approval step" button, a step is added below that cannot be seen.  Because the newly added approval step cannot be seen, the super user keeps clicking the "Add an approval step" button.  The super user ends up with two or three extra approval steps.

When the super user clicks the "Add an approval step" button, can the page automatically scroll down to where the new approval step is displayed?  This will make it obvious to the super user that a new approval step was indeed created.

Also, if an approval step has a blank step name and no report approvers are assigned to the step, do not create additional approval steps when the "Add an approval step" button is clicked.

When training super users, they constantly create extra steps.

**Comment by dspCarlson** [comment]
@VassilIordanov Can this be integrated into #528?

**Comment by gjvoosten** [comment]
@dspCarlson I will move the *Add an Approval Step* button to the bottom of the _Approval process_ section; this has the desired effect of showing the just-added empty step on-screen.
