### ISSUE TITLE
Engagement Report Cannot be Approved

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#535]
Report author submitted a report but when the report approver went to the report, the report had a draft status.  The approval step ID in the reports table record is NULL in the database.

Report number 73127
Report author 1755

2027 (15:57:49 Z)
Source: auditLogger file from 2018-03-13
Report author has submitted report 73127

2028
Source: ANET email
Email sent to report author stating report is ready to be approved

2029
Source: email from report author to ANET administrator
Report author has submitted report

**Comment by dspCarlson** [comment]
@VassilIordanov I emailed a supporting screenshot to you.

In the screenshot, the approval chain is in edit mode.  The super user added himself to two approval steps with differing results.

The super user added himself to Step 1.  The super user's name is the last name displayed in Step 1.  The super user's name in Step 1 is rank and then name.  In the position column, the super user's billet number is displayed.  

The super user added himself to Step 2.  The super user's name is the first name displayed in Step 2.  The super user's name is just the name without a rank.  In the position column, the super user's position title is displayed.

**Comment by maradragan** [comment]
This is what I think has happened:
- the report author has submitted the report
- the report approver has received an e-mail about the report ready to be approved
- the report author has edited the report and saved it (at this point the report becomes draft again
- the report approver went to the report to be approved but meanwhile this one is draft again

**Comment by dspCarlson** [comment]
@gjvoosten I agree with creating a second issue.

**Comment by dspCarlson** [comment]
@maradragan Per your comments above, the log file reflects that the report author retrieved the report immediately after submitting the report.  However, the time difference between submitting the report and then retrieving the report was .285 of a second.

The report author submitted the report at 15:57:49.704; this is a "report" log entry
The report author retrieved the report at 15:57:49.985; this is a "ReportSensitiveInformation" log entry
The report author updated the report at 15:58:25.423; this is a "ReportSensitiveInformation" log entry

I also emailed the report author.  He doesn't remember editing the report again.  And this wasn't the first time this has happened to this report author.  On 12 March, the report approver also could not approve the same report.  I found the log entries.

The report author submitted the report at 16:49:27.446; this is a "report" log entry
The report author retrieved the report at 16:49:27.555; this is a "ReportSensitiveInformation" log entry
The report author updated the report at 16:49:43.071; this is a "ReportSensitiveInformation" log entry
This is followed by about 100 update "ReportSensitiveInformation" log entries.  And per @gjvoosten 's suggestion, the updated log entries are approximately 30 seconds apart.

**Comment by gjvoosten** [comment]
@dspCarlson One hypothesis of what could have happened is this:

- the author saved the report
- the author submitted the report
- the author clicked on _Edit_ of that report, did not actually change anything, but might have clicked or tabbed into the **Report text** or **Report sensitive information text** fields
- this could have made the page autosave the report, at which point it gets reset to _Draft_ state

At least with release `2.0.15` (which presumably is what was running at the time of reporting this issue), I can reproduce that behaviour. With the latest release (where autosave is slightly smarter) I am no longer able to reproduce this. So it would appear to be fixed, at least for this hypothetical scenario.

If you agree with the above you may close this issue.

**Comment by dspCarlson** [comment]
@gjvoosten I believe this is the behavior too.  The report author clicks the "Edit" button after submitting the report.  Believe it or not, yesterday the same super user contacted me again about the same problem.  I emailed the report author directly and asked them if they had clicked the "Edit" button after submitting.  I have not heard back (so that means that was the problem).
