### ISSUE TITLE
One Report has 438 "updated by" Records in an auditLogger File

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#536]
Report 73127 has 438 "updated by" records in the 2018-03-13 auditLogger file.

Report 72877 has 1,020 "updated by" records in the same auditLogger file.

Is this by design?

**Comment by gjvoosten** [comment]
@dspCarlson Perhaps repeated autosaves while someone was typing a (long) report text?

**Comment by dspCarlson** [comment]
@gjvoosten No doubt!

**Comment by dspCarlson** [comment]
@gjvoosten These hundreds of updates are coming from the "ReportSensitiveInformation" type log entries as compared to the "Report" type log entries.

**Comment by dspCarlson** [comment]
@VassilIordanov Should we close this issue?  It's not a bug per se, but all the log entries make it difficult to read the log files.  Plus, the log files are huge as a result.

**Comment by dspCarlson** [comment]
Closing this issue as it really doesn't affect anything other than creating larger log files.
