### ISSUE TITLE
implement GraphQL GET requests (2sp)

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#55]
Currently, ANET only implements [POST](http://graphql.org/learn/serving-over-http/#post-request) requests. In order to integrate with other systems, it is required to also implement [GET](http://graphql.org/learn/serving-over-http/#get-request) requests.

**Comment by VassilIordanov** [comment]
Currently, ANET only implements [POST](http://graphql.org/learn/serving-over-http/#post-request) requests. In order to integrate with other systems, it is required to also implement [GET](http://graphql.org/learn/serving-over-http/#get-request) requests.
Additionally, the GET request should have an optional query field **output**. 
`http://myapi/graphql?query={me{name}}&output=xml`
When **output** equals to _json_ or undefined, the default behavior should be preserved and json returned.
When **output** equals to _xml_ the query result should be converted to xml with a canonical conversion and returned,

**Comment by gjvoosten** [comment]
We should be aware that GET requests impose a limitation that POST requests do not have: a maximum length. The exact maximum depends on both the client (browser) and the server, but practically it is in the order of a few KBytes. As long as our queries are relatively short & simple, GET is fine, but keep in mind that for longer queries (like in the future searching for a lot of tags perhaps) it may become necessary to use POST.
