### ISSUE TITLE
Show inactive positions button on organization page doesn't work intuitively

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#553]
- I go to an organization's page which has a few supported positions
- I inactivate one of the positions
- I get to see now a button "show 1 inactive position"
- when I click the button the label toggles to "hide 1 inactive position" but the list of positions remains the same, it does not show the inactive positions

**Comment by maradragan** [comment]
Well, I just noticed that it works. But, the show inactive positions button is on the supported positions section, and on click the inactive positions are displayed under vacant positions. You can only see the contents of that one changing if the vacant positions is also on the visible area. So, that is why I didn't see it changing. Shouldn't the button be on the vacant positions section (all inactive positions are also vacant because when inactivating a position it becomes vacant)?

**Comment by dspCarlson** [comment]
@maradragan I agree it would be more appropriate to have the "Show/Hide" button down by the vacant positions.

In addition there are instances where the super user sets the position to inactive but there is still someone assigned.  In those cases the inactive position shows in the "Supported positions" section and not the "Vacant positions" section.  Maybe we should remove the person from the position when setting the position to inactive.
