### ISSUE TITLE
Report is Blank

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#554]
Condition:
1. Report author created and saved a report.
2. The report did not have a principal assigned
3. The report had a primary advisor attendee (who was not the report author) who was not assigned a position when the report was created and saved
4. After the fact the primary advisor attendee was assigned to a position
5. The report still had a draft status

Result:
1. When the report author came back to the report, the entire report was blank
2. Only the "Email report" button was visible
3. In the database, the following three fields were NULL: advisor organization ID, principal organization ID and nextStepId

Workaround:
1. In the database I inserted the primary attendee's organization ID in the reports.advisorOrganizationID field
2. I opened the report again and the display was normal to include the "Edit" button

I was able to re-create this bug by simply going to the report.

**Comment by maradragan** [comment]
I can reproduce it.
