### ISSUE TITLE
History of Advisor's or Principal's Position Assignment(s) is Not Available

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#568]
When a new advisor/principal needs to be assigned to a position, the common response is "They [the incoming person] is taking so-and-so's position."  The problem is, if the outgoing advisor/principal is no longer assigned to the position, then the previous position can't be found unless each vacant position in the organization is clicked on and the "Previous position holders" is reviewed.

This problem is more prevalent when the outgoing advisor leaves.  Their profile is set to inactive.  Then the incoming advisor arrives but the previous person's position is unknown.

Just like the position page has the "Previous position holders" section, could the person page have a history of the positions assigned to?  This would also be useful for tracking principals.  Because the principals names are so similar (and even the same), it would be easier to distinguish the principals by their work history.

**Comment by VassilIordanov** [comment]
Related to the sticky layout work @maradragan has been doing. We need to dig a bit more how to do that well in IE11, we will then address this issue
