### ISSUE TITLE
Banner does not change color when the "General banner level" parameter is changed

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#585]
When an existing banner is displayed, the color does not change when changing the "General banner level" parameter.

The work around to change the banner color is to:
1. Change the "General banner level" value
2. Select the "Save settings" button
3. Change the "General banner visibility" value to "1"
4. Select the "Save settings" button
5. Change the "General banner visibility" value again
6. Select the "Save settings" button again

**Comment by gjvoosten** [comment]
Happens only under IE11 (both Firefox and Chrome update the colour correctly).

**Comment by VassilIordanov** [comment]
@dspCarlson @gjvoosten is this still a problem?

**Comment by maradragan** [comment]
Added to #1965
