### ISSUE TITLE
Change the banner "General banner level" input from text to a drop down menu

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#586]
The "General banner level" has four parameters that change the color of the banner.  The four parameters must be typed in.  Instead of typing the values into a text box, the four values should be displayed in a drop down menu.

Instead of displaying the four parameter values of "Error," "Notice" etc, just display the banner color (i.e. red, blue, green and yellow) as drop down values.

The "General banner level" only affects the banner color.  It does not change the banner's default wording.  The banner's default wording is "Announcement:"

**Comment by maradragan** [comment]
Added to #1965
