### ISSUE TITLE
Change the banner "General banner visibility" input from text to a drop down menu

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#587]
The "General banner visibility" parameter accepts three numerical values that must be typed in.  Change the inputted value to a drop down menu.

The three values are:

1 - Users only
2 - Super users and administrators only
3 - Users, super users and administrators

**Comment by VassilIordanov** [comment]
Unfortunately, due to how settings are designed to be stored in the database, we may need to rework some things before that, so this (as well as dropdowns for other settings) will not happen before we do so

**Comment by dspCarlson** [comment]
Understand.  It's not a high priority, just a "nice-to-have."

**Comment by maradragan** [comment]
Added to #1965
