### ISSUE TITLE
Report 37585 does not display in the browser

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#588]
Tried to view report 37585.  The browser responds like it is going to display the report.  But the browser becomes blank.

I asked two other ANET users to try and display the report.  Both of their browsers were also blank.

I checked the report in the database.  I didn't see anything wrong with the report data.  I did notice one of the attendees didn't have an end of tour date.  However, when I checked other reports where an advisor attendee didn't have an end of tour date, the browser displayed the reports.

**Comment by dspCarlson** [comment]
Ran the F12 debugger when loading report 37585.

The error is: Unable to get property 'className' of undefined or null reference; File: vendors.be2848b7.js, Line: 34, Column: 3852

**Comment by maradragan** [comment]
Agreed with Vassil to first remove the current progress bar functionality in order to fix this issue. Afterwards we will replace it with a different progress bar as part of #593 .
