### ISSUE TITLE
Review and upgrade npm dependencies

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#59]

**Comment by gjvoosten** [comment]
Now that React v16 is out, we should look into at least upgrading this. At least two packages have no support for React v16:
- https://www.npmjs.com/package/react-injectables - project is effectively dead
- https://www.npmjs.com/package/react-tag-input - project is looking for new maintainers

**Comment by gjvoosten** [comment]
Also see #375 .

**Comment by VassilIordanov** [comment]
replaced by dependabot
