### ISSUE TITLE
Improve LinkTo

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#598]
I suggest to make:

- [ ] rename LinkTo to something more appropriate
- [ ] evaluate the default behavior for `whenUnspecified`, and where it is appropriate throughout ANET
- [ ] make LinkTo to be able to render content based on some hints. output types should be:
  - [x] interactive output. When rendering a person for example, provide background/rounded box, possibly an icon (the picture), and a preview on mouse hover
  - [x] minimal output. Same as above minus links, preview and with more sober styling
  - [ ] svg output. provide SVG nodes to be used by d3
- [ ] Add a preview ability for LinkTo

**Comment by midmarch** [comment]
Needs to be reviewed. If need,  split in smaller issues or update a clear list of things which are left to do.
