### ISSUE TITLE
Blank Reports Displayed

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#603]
Today a user stated he could not view a report.  However, the report had been released.

The bug is in the approvalActions table.  If the approvalStepId is NULL for the last step in the approval chain, the report will not display.

I ran a query.  There are 3,546 reports where the approvalStepId column is NULL for the last step in a report's approval chain.  The newest of these reports was created on 11 April 2018.  The oldest of these reports were migrated from SharePoint on 5 March 2017.

I will write a query to update the records with the last approval step id.

**Comment by VassilIordanov** [comment]
For now I will place a fix that will allow rendering on pending reports with an approvalStepId null. I will keep digging what are all the possible paths for reports to get in that state.

**Comment by dspCarlson** [comment]
There are 3,721 records in the approvalActions table where the approvalStepId value is NULL.  What is interesting is that those 3,721 records are limited to only 69 approvers (i.e. approvalActions.personId).

**Comment by dspCarlson** [comment]
I used the "Reports Where Last ApprovalStepId is NULL in the approvalActions Table" query (in the "Reports" folder) to troubleshoot this issue.  I tested several reports where the last approval step ID is NULL.  All the reports successfully displayed.

I am closing this issue since the bug can no longer be replicated.
