### ISSUE TITLE
Ensure there's at most one Person per domain username

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#65]
Some of the user accounts in the production environment are based on position instead of the person.
As a result,following a HOTO, a new system user is being authenticated and associated with an old account when a new user (albeight probably in the same position) should have been created.
ANET should be modified to allow associating several Persons to the same domain username. At any given time, at most one Person should be active per domain username, the remaining ones being there for archiving reasons.
When there are no active Persons associated with a username, ANET should prompt for new account creation upon user access. The resulting Person should become the new active Person for that username.

Superusers and administrators should be able to:
- deactivate active Persons
- activate Persons when there are no other active Persons
- switch the active Person when a Person needs to be activated and there is another active Person with the same username

**Comment by gjvoosten** [comment]
The current authentication filter strategy is (both in `AnetDevAuthenticator` and `AnetAuthenticationFilter`):

1. get the list of Persons with the domainUsername used to authenticate
1. if the list is empty, create a new Person for that domainUsername
1. otherwise get the first Person from the list
1. if the Person is _inactive_, activate that Person
1. use this Person as the Principal for this session

This strategy clearly needs to change. We need to agree what it should be.
Simply changing the first step to:

1. get the list of *active* Persons with the domainUsername used to authenticate

means that step 4 is no longer possible. It could result in creating a *new* Person which in real life should be a reactivation of an existing *inactive* Person, leading to an admin having to merge these two Persons later on.
It rather depends on how common this case is. If the case is very rare compared to a new Person joining, the overhead of the merge action is negligible.
Perhaps @dspCarlson can add some insights from the field?

**Comment by gjvoosten** [comment]
> Superusers and administrators should be able to:
> - deactivate active Persons

This is already possible, and requires no change.

> - activate Persons when there are no other active Persons
> - switch the active Person when a Person needs to be activated and there is another active Person with the same username

Activating a Person should check whether there's already another Person with the same domainUsername that is active. Could possibly ask the admin:

"WARNING: activating this Person will *deactivate* Person _JohnDoe_, do you want to continue?"

and if _yes_, deactivate the other Person and activate the current Person.

**Comment by dspCarlson** [comment]
When an outgoing person is inactivated (people.status = 1) by a super user, the domain user name for the outgoing person must be set to NULL.  This will allow the incoming person to logon and create a new profile/account.  However, a warning message must be displayed so the super user knows the consequences of inactivating the outgoing person.  Message: "Inactivating JohnDoe means the next person to logon with <user name> will have to create a new profile.  Do you want the next person to login with this user name to create a new profile?"  Does this help?

**Comment by dspCarlson** [comment]
Message: "Inactivating JohnDoe means the next person to logon with the <domain user name> user name will have to create a new profile. Do you want the next person to login with this user name to create a new profile?"

**Comment by dspCarlson** [comment]
Along with deactivating the person, when the end of tour date is expired, the super user must be forced to decide to deactivate the person or change the end of tour date to a future date.  There are too many persons with an expired end of tour date but their status is still active.

**Comment by gjvoosten** [comment]
@dspCarlson Thanks for the insights. Should we define a (one-time or scheduled) cleanup action as well, e.g. to deactivate all persons whose end of tour date is in the past?

**Comment by dspCarlson** [comment]
Super users must be forced to acknowledge (maybe with a display message when they login) they have people who are active and yet their end of tour date is expired.  Can we force super users to inactivate people before they can use other functions?  As for a one-time clean up, I can do that from here.  But I want to give super users a chance to clean up their data first.  After a few weeks of letting the super user users clean up their data, I will run an update query.  There will be users/stragglers who are no longer assigned to a position and therefore won't be under a super users purview.

**Comment by gjvoosten** [comment]
@dspCarlson In general (from a usability standpoint) it is not wise to force users to do something before they can continue their work. They may not be able to decide on the spot what to do about it, and the reason they logged in in the first place is because they want to accomplish something else. 😉
So adding a warning banner seems like a more user-friendly approach.

As for the cleanup action: so yes, we have indeed defined one (just now, ad hoc), which you will be able to perform whenever you feel it's time. 👍 

We could even decide on a deadline for the cleanup action, and put that date in the warning banner.

**Comment by dspCarlson** [comment]
I agree 100% with your last comments.  If we could have a warning banner that would be appropriate.  I believe super users will do their job if the program is able to "coach"/show them issues with their data.

There is another item that refers to having a warning banner for planned outages (like last night).  With a warning banner, the business owner wouldn't have to notify super users and users ahead of time.

**Comment by gjvoosten** [comment]
FYI: the (generic) banner issue is tracked here: #27

**Comment by gjvoosten** [comment]
I will refine this story.

**Comment by gjvoosten** [comment]
From querying the database, we see that the problematic duplicate users account for only about 1-2% of the active users. We should fix those by hand, i.e. set the status of the spurious duplicates to 1 (inactive).
Then we should manually set the domainUsername to NULL for all inactive accounts.

This keeps the proposed implementation simple:

- when a super-user inactivates an account, a warning is shown:
  > Setting this person to inactive means the next person to logon with the user name <strong>{person.domainUsername}</strong> will have to create a new profile. Do you want the next person to login with this user name to create a new profile?
- when an account is inactivated, also the domainUsername field is cleared
- when a user authenticates, there should be an active account with that domainUsername, which will then be associated with that user for the duration of the session
- if a user authenticates and there is no active account with that domainUsername, a new account is created and the user should fill out the profile

For new profiles, a super-user needs to assign a position. This also gives the super-user the ability to merge the new profile with an old existing profile in the rare case that one should be re-used/re-activated.

**Comment by dspCarlson** [comment]
One more thought on this issue.  When a user is made inactive, the adviser's position should have an unassigned status.  The position should not have anybody assigned to it.  This affects positions.currentPersonId and peoplePositions.  The super user should also be notified of this via the displayed message.

**Comment by gjvoosten** [comment]
@dspCarlson: Re: unassigning position:
Code was already in place to clear the position if a person was set to inactive. Nothing needed to change there.

**Comment by gjvoosten** [comment]
@dspCarlson: Re: people coming back after a while:
When someone authenticates sucessfully, the only thing we get is the domainUsername. We can look up if there's a person linked to it, but if not, we create a new profile (there's no other choice). But as stated in https://github.com/NCI-Agency/anet/issues/65#issuecomment-317777315 :

> For new profiles, a super-user needs to assign a position. This also gives the super-user the ability to merge the new profile with an old existing profile in the rare case that one should be re-used/re-activated.

**Comment by VassilIordanov** [comment]
I suggest that when a person fills their details for a new acount, the system finds inactive users with similar data and suggests to reactive these accounts. The same kind of feature could apply to creating new people and places

**Comment by gjvoosten** [comment]
@vassil That should be a new story. "Similarity" should be defined etc.

**Comment by dspCarlson** [comment]
Reconciled 30 domainUserNames that were duplicated.  There are no more records with duplicate domainUserNames.

**Comment by gjvoosten** [comment]
Excellent!

**Comment by VassilIordanov** [comment]
Following test case fails:
- Log in as admin, 
- find one active user with a domain name.
- edit, switch status to inactive
   -> ANET displays warning that user will not be able to logon anymore using its domain name
- save user
- inspect domainUsername field in MS SQL
   -> domainUsername is not NULL

**Comment by VassilIordanov** [comment]
@gjvoosten - looks like PersonDao.update does not handle domainUsername, hence the change never makes it to the db

**Comment by gjvoosten** [comment]
Pfrt...
