### ISSUE TITLE
add optional format parameter to GraphQL GET requests

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#67]
the GET request should have an optional query field **output**. 
`http://myapi/graphql?query={me{name}}&output=xml`
When **output** equals to _json_ or undefined, the default behavior should be preserved and json returned.
When **output** equals to _xml_ the query result should be converted to xml with through a canonical conversion and returned.

**Comment by gjvoosten** [comment]
Is there a preferred way of converting the JSON to XML? Or will something like https://stackoverflow.com/a/19978281 be sufficient? Should we use a specific XML root node? How can we check that the XML we produce is acceptable by the client?

**Comment by gjvoosten** [comment]
JAX-RS marshalling was too difficult to get working in the timebox I allocated for it, so I abandoned that and focused on using JSON-java: https://github.com/stleary/JSON-java
That took me 15 minutes to get working. Attached two examples of GET'ing the list of recent persons for erin, one as JSON [json-example.txt](https://github.com/NCI-Agency/anet/files/1162423/json-example.txt) and one as XML [xml-example.txt](https://github.com/NCI-Agency/anet/files/1162425/xml-example.txt).

Question still remains: how can we check that the XML we produce is acceptable by the client?

**Comment by gjvoosten** [comment]
The XML returned, pretty-printed and with an XML declaration header:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<result>
  <data>
    <personList>
      <list>
        <role>ADVISOR</role>
        <name>Erin Erinson</name>
        <rank>Civ</rank>
        <id>191</id>
        <position>
          <organization>
            <id>1142</id>
            <shortName>EF 2.2</shortName>
          </organization>
          <name>EF 2.2 Advisor D</name>
          <id>1269</id>
        </position>
      </list>
      <list>
        <role>PRINCIPAL</role>
        <name>Christopf Topferness</name>
        <rank>CIV</rank>
        <id>196</id>
        <position>
          <organization>
            <id>1166</id>
            <shortName>MoD</shortName>
          </organization>
          <name>Planning Captain</name>
          <id>1284</id>
        </position>
      </list>
    </personList>
  </data>
</result>
```

Who can tell if this is OK?

**Comment by VassilIordanov** [comment]
@gjvoosten This XML looks good
To add automated tests, I suggest the following:
Once the integration is done, we can add a graphql test based on the exact query the consumer is using and then assert theresulting  XML

**Comment by gjvoosten** [comment]
For now I'm just adding a test (to GraphQLResourceTest) that GETs it over XML and does some basic checks.
Two questions that I need answered before committing & pushing:
1. Do we want the output to be pretty-printed?
1. Do we want the XML declaration at the top?

**Comment by gjvoosten** [comment]
If you're using Eclipse, remember to run `./gradlew eclipse` to update your `.classpath` when pulling this in.
