### ISSUE TITLE
Weekly Summary Reports

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#675]
Take into account that some advisors have so many engagements every day that they write weekly summaries.  However, weekly summaries do not capture how many engagements that are actually taking place.

Is there a way to allow report authors to acknowledge individual engagements while only writing a weekly summary?

**Comment by VassilIordanov** [comment]
Not really. I believe the following should happen:
- we need to understand why it is cumbersome for some users to create several engagement reports as opposed to a weekly summary. We have obviously room for improvement if that is happening.
- understand if weekly reports have another benefit to these users besides simple convenience: i.e. do they use them as a place to enter information that ties across several engagements and that they have no designated place for at the moment.
- convey to the users that, at least currently, if they do not enter individual reports, their information is basically lost. Ask them again, what would they like to see to make that process easier
- convey and educate report approvers to encourage users to enter individual reports and reject summaries.

**Comment by dspCarlson** [comment]
@VassilIordanov In the outlying advisor organizations, an advisor will work with up to seven principal organizations.  If those principal organizations are located at one location, the advisor can have up to seven 30-minute engagements in one day.  The advisors will have multiple engagements several times a week.

The two most cumbersome factors of creating an engagement report are:
1. Selecting the principal attendee(s)
2. Selecting the correct task(s)

#255 would assist the advisors in being able to select principals as meeting attendees more easily.  The real trick to finding principal meeting attendees is to select their principal position using the position code.  Unfortunately, a lot of principal positions do not have the position code assigned AND advisors are unfamiliar with their principals' assigned codes in order to select them as an engagement attendee.

I have sent an email to the two part-time ANET trainers to be on the lookout of how creating engagement reports can be made less cumbersome.

In the meantime, this issue can be closed.
