### ISSUE TITLE
Existing user being asked to create a new profile

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#771]
An existing user is being asked to create a new profile.

The user sent me a screenshot of his domain user name (after using the whoami command).  The domain user name matches the one in the people table.

I checked all the log files.  The anet, anet-error and clientLog files all contain the same error for this user:
js/vendors.c6e589dc.chunk.js 54:101757 Unable to get property 'parentNode' of undefined or null reference

I checked his records in the people, positions, and peoplePositions table.  I could not find any undefined data or NULL values.

Any immediate feedback would be nice.

**Comment by dspCarlson** [comment]
This is no longer a priority.  I am waiting for feedback from the user.  Today the user complained about the same problem again, i.e. being asked to create a profile.  However, this time in the logs, I noticed he was performing super user duties.  This tells me he is using a link to open ANET and the link points to the onboarding page.

**Comment by dspCarlson** [comment]
The user provided feedback that indeed his saved link was pointing to onboarding

**Comment by VassilIordanov** [comment]
I suggest to make the onboarding page redirect to home if the user exists already. It is likely that others will bookmark the onboarding page as it is one of the first ones they see.
