### ISSUE TITLE
Only display advisor locations when selecting a location for an advisor position

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#786]
Epic #3547: **Ability to differentiate on location types**

When super users select a location for an advisor position, only allow them to select locations where the advisors are actually assigned.

For advisor position locations, do not make the data field a search field for the super users, rather a drop-down of only advisor position locations.  There are less than 25 advisor position locations.  Super users have different ideas of what a location should be called.  When they can't find the name of the location as they think it should be called, they will create a new location. Don't give super users the option for searching for a location that doesn't exist.

Super users assign incorrect locations to advisor positions, e.g. cities, principal locations.

An advisor position location is defined by the location where the advisor has their office/computer.  An advisor position location is not where the advisors advise their principals or the location where they sleep at night.  Although most advisors offices and sleep locations are the same place.

There are three types of position locations:
1. Locations where principals work
2. Locations where advisors work
3. Locations where advisors and principals work together; only three of these

Is related to #785 and in a way also to #3509.

**Comment by VassilIordanov** [comment]
@dspCarlson lets revise this requirement once you try the new autosuggest in 2.1

**Comment by dspCarlson** [comment]
@VassilIordanov Okay I will wait for the new autosuggest in 2.1.

Super users still like to select the advisor position location as the place where the advisor trains/advises instead of the place where the advisor works (and can be supported with individual deskside ANET training, emails, phone calls).

**Comment by dspCarlson** [comment]
@midmarch @gjvoosten @cemalettin-simsoft 

This is still a valid requirement.

When running reports where advisors are located / assigned, some advisors positions are still being assigned to the principal's bases, police HQs.
