### ISSUE TITLE
Cannot select any of the six values from the "State" drop down menu for the "Reports" filter

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#798]
Recreate the bug:

1. Select "Add filters"
2. Select the "Reports" tab
3. Select the "State" filter
4. Try to select any of the six values in the "State" drop-down menu

Result: Cannot select single values or multiple values.

**Comment by gjvoosten** [comment]
Since the report state filter is now a multi-select, the cancellation reasons drop-down is only shown if `Cancelled` is the *only* state selected in the multi-select. Do you perhaps have other states selected besides `Cancelled`?

**Comment by dspCarlson** [comment]
@gjvoosten Whoops!  Actually the bigger problem is you can't select any of the six values from the "State" drop-down menu.  I also tried to select multiple values by using the SHIFT and CNTL keys.

**Comment by gjvoosten** [comment]
That seems to be a problem specific to IE11 (it works correctly under e.g. Firefox and Chrome). We'll look into it.
