### ISSUE TITLE
Selecting the "Enter" key does not execute a search when the search has filters

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#799]
Selecting the "Enter" key executes a search when there are not any filters selected.

**Comment by gjvoosten** [comment]
This currently _by design_ to avoid the situation where the Enter key would submit the 'simple' search form (without the advanced filters). In a future release this is going to be resolved by refactoring the search forms. For the time being you'll have to live with it, I'm afraid.

**Comment by dspCarlson** [comment]
@gjvoosten Thanks.  I'll close the ticket.
