### ISSUE TITLE
"Report Problem" mechanism for users

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#81]
When users are experiencing a problem, they should be given a quick mean to report it. A problem report should be sent to the administrators with the following content:

- user-provided problem description
- automatically generated:
    - copy of the DOM, or other mean to recreate what the users are seeing
    - client-side logs, exceptions or capturing window.onerror
    - context information (anet version, date, time, username, client hostname, etc.)

**Comment by gjvoosten** [comment]
Client-side logs are implemented in #419 .

**Comment by maradragan** [comment]
Added to #1595
