### ISSUE TITLE
Missing/blank location for an engagement report does not display an error message

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#819]
Steps to recreate the bug:

1. Create a new report
2. Fill in data for the following required fields: Meeting goal, Engagement date, Atmospherics (button), Atmospherics (text), Attendee (at least one principal), Key outcomes and Next steps
3. Do not enter a value for the location
4. Select the "Preview and submit" button

Result:
1. The report stays in edit mode; the report does not go to preview mode
2. The page jumps to the top
3. No error message is displayed that indicates why the report did not go to preview mode

**Comment by maradragan** [comment]
I did see this happening locally under Firefox in the begining of the week, a few times, but couldn't find the reason and afterwards it was not happening any more.

**Comment by dspCarlson** [comment]
@gjvoosten @maradragan I can still reproduce this error.
