### ISSUE TITLE
GraphQL admin interface

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#824]
Enhance the current graphiql interface to permit saving/loading queries
Ideally, admins should be allowed to save/share queries, and eventually compile a toolbox of queries/mutations for data maintenance that is not possible yet through the UI
see discussion here: https://github.com/apollographql/apollo-client-devtools/issues/16

**Comment by VassilIordanov** [comment]
Enhance the current graphiql interface to permit saving/loading queries
Ideally, admins should be allowed to save/share queries
see discussion here: https://github.com/apollographql/apollo-client-devtools/issues/16

**Comment by maradragan** [comment]
Added to #1965
