### ISSUE TITLE
Banner for general purpose notifications

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#84]
Banner with announcements to all users. To support color and font customizations

**Comment by dspCarlson** [comment]
Can the banner be configured to be visible to:
1. Only users
2. Only super users
3. Users and super users

**Comment by dspCarlson** [comment]
@evdhoudt The banner no longer displays any colors.  The banner color is beige for all four general banner levels.  The colors were functioning before the 16 November release.
