### ISSUE TITLE
positions advanced search: organization dependency on position type is not working well

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#886]
When doing an advanced search on positions the organization filter should depend on the selected position type (when both these filters are being used).
This is not always the case right now.

**Comment by dspCarlson** [comment]
Tests were successful

Test 1: Success
Selected "Positions" parameter in the advanced search
Selected the "Position Type" filter
Selected "Principal Position" for the "Position Type" filter
Selected the "Organization" filter
Starting typing; only principal organizations were displayed in the drop-down list

Test 2: Success
Selected "Positions" parameter in the advanced search
Selected the "Organization" filter
Selected a principal organization
Selected the "Position Type" filter
Selected "Advisor Billet" for the "Position Type" filter
Clicked the "Search" button; no records were displayed

Test 3: Success (continued from the end of Test 2)
Changed "Advisor Billet" value to "Principal Position" value for the "Position Type" filter
Clicked the "Search" button; records were displayed
