### ISSUE TITLE
Add location to meeting attendees

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#889]
Include the position's location in the "Meeting attendance" section of reports.

Report approvers still approve reports when there are incorrect meeting attendees.  Report authors choose principal names that look similar.  Make it painfully clear that the wrong principal is being select based on the assigned position's location.

**Comment by VassilIordanov** [comment]
Also, I am including the location in the people lookup dropdown: 
![image](https://user-images.githubusercontent.com/16674032/45680399-200d3080-bb3b-11e8-9d17-9374bc1710f1.png)
