### ISSUE TITLE
Show warning to super-users about people that need to be inactivated

### ISSUE THREAD

**Issue by gjvoosten** [NCI-Agency/anet#89]
(split off from https://github.com/NCI-Agency/anet/issues/65 )
There should be a warning message/banner that informs super users that they have people who are active and yet their end of tour date is expired. These people need to be inactivated.

@dspCarlson can do a one-time clean up, but he wants to give super users a chance to clean up their data first. After a few weeks of letting the super user users clean up their data, he will run an update query. There will be users/stragglers who are no longer assigned to a position and therefore won't be under a super users purview.

**Comment by VassilIordanov** [comment]
related to #27

**Comment by VassilIordanov** [comment]
I suggest to do that as a saved search once we redesing saved searches. It could be a default saved search for all super users that returns users in their orgs with end of tour about to expire.

**Comment by gjvoosten** [comment]
Addressed by #530
