### ISSUE TITLE
Change suggestion for first name

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#903]
Currently the suggestion for the first name data field is "First name(s)" when the data field does not contain any data.

The suggestion should indicated that first names are lower-case except for the first letter of each name.

Example:

First name(s) - First names are lower-case except for the first letter of each name.

**Comment by gjvoosten** [comment]
@dspCarlson Your suggested help text of _First name(s) - First names are lower-case except for the first letter of each name_ is slightly too long to fit in the input box; would _First name(s) - Lower-case except for the first letter of each name_ also be acceptable?
