### ISSUE TITLE
error in create person form

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#910]
As an admin I click on the create person button.
I get to the create person form.
I click on the domainname field but do not fill anything in it.
I click on the inactive status button and than I get an error.

**Comment by dspCarlson** [comment]
Tested for version 2.0.38.  I repeated the four steps above.  When I clicked the "Inactive" button, the browser goes completely gray.  The browser stays completely gray even when using the back button.

**Comment by gjvoosten** [comment]
@dspCarlson Are you sure? With `2.0.37` I can reproduce the bug, but `2.0.38` has a fix and there I can indeed no longer reproduce the bug.

**Comment by dspCarlson** [comment]
@gjvoosten You are right.  Now I can't reproduce the bug.  I suspect I didn't have a fresh browser when I tested it.  I had several ANET browsers open.  Could that have been the problem with my testing?
