### ISSUE TITLE
Use the national HR system to identify principals

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#911]
This GH issue is for a future enhancement.  If advisors can get the national ID number of the principal, the principal's name could be automatically populated and populated correctly.

Will the owner of the HR system let ANET use a periodic copy of the HR data?

**Comment by VassilIordanov** [comment]
@dspCarlson any news from the owner of this system?

**Comment by dspCarlson** [comment]
@VassilIordanov I haven't followed up with the advisor who is responsible for the HR system.

**Comment by dspCarlson** [comment]
@VassilIordanov  Getting access to the data is going to require support from the requirements owners.  I will contact the requirements owners today.

**Comment by maradragan** [comment]
Added to #1972
