### ISSUE TITLE
Extend the GraphQL GET to support CSV output

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#93]
the GET request has an optional query field output.
```
http://myapi/graphql?query={me{name}}&output=csv
```
When the specified output is 'csv', the first list in the GraphQL results should be returned in a CSV format. The rows represent items in the list and the colums attributes

**Comment by dspCarlson** [comment]
For CSV files are the commas and semicolons being removed from the five text fields in reports?  Or returning the five fields as enclosed text fields?

**Comment by VassilIordanov** [comment]
all special characters are to be escaped according to the W3C's [recommendation](http://www.w3.org/TR/tabular-data-model/) on tabular data

**Comment by gjvoosten** [comment]
@vassil Do we still need this now that we have XLSX export?

**Comment by dspCarlson** [comment]
@gjvoosten In my opinion CSV file format is no longer needed.  The XLSX meets the original download requirements.  The users are pleased to have the XLSX file format.

**Comment by gjvoosten** [comment]
OK, closing this one then!

**Comment by VassilIordanov** [comment]
I feel like as it reduces complexity (I assume it will, as it is not handled by apache poi), and as it is hard to make CSV bullet-proof, we can get rid of it.
