### ISSUE TITLE
Remove the ability of super users to edit the colloquial name for principal organizations

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#940]
Currently super users can only edit the colloquial name (dbo.organizations.shortName) for principal organizations.

However this privilege must also be removed as super users are changing the colloquial name to names that don't reflect the official organization name (dbo.organizaions.longName).

**Comment by gjvoosten** [comment]
@dspCarlson The current logic for the `longName` field of an organization is that is disabled (read-only) if and only if: it is a principal organization and the user is not an admin.
Should the same logic apply to the `shortName` field?

**Comment by dspCarlson** [comment]
@gjvoosten Yes, the same logic should now apply to the shortname field.  Super users should not be able to create or edit a principal organization.

**Comment by gjvoosten** [comment]
@dspCarlson Do you mean to say that super users should not be able to edit principal organizations at all? (note: they would still be able to edit several aspects of advisor organizations)
Right now a super user can only change two fields of an advisor organization: the `shortName` and the `status` (active/inactive). So in addition to making the `shortName` field read-only (when super users try to edit an advisor organization), should the `status` also be made read-only?

**Comment by dspCarlson** [comment]
@gjvoosten Yes, super users should no longer be able to edit the colloquial name or status (as you have pointed out) for principal organizations.  Super users are still making mistakes with the colloquial names for principal organizations.  Despite our training efforts, super users change data for their own convenience and the data loses integrity.

This will not cause much of a work load for administrators.  There are now three administrators (that are also trainers) that know ANET very well and are already performing these administrative tasks.
