### ISSUE TITLE
Super user created the same principal nine times in 39.914 seconds

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#941]
On 26 September 2018, a super user created the same principal nine times in 39.914 seconds. The first eight records were created in less than 18 seconds.  Five of the records were created in .047 of a second.

I will update this issue as I get feedback from the super user and his actions to create these records so quickly.  But right now I need a GH number for an email to @VassilIordanov.  

The email to @VassilIordanov contains an Excel spreadsheet with the raw and calculated data.

**Comment by VassilIordanov** [comment]
not reproduced since
