### ISSUE TITLE
Administrators cannot edit the status of a person

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#969]
When a person (advisor or principal) is set to "Inactive," an ANET administrator cannot edit the profile and set the person's profile back to "Active."

When an administrator edits a person's profile, the administrator should be able to set the person's profile back to active.  With advisor profiles, the administrator can add the domain user name after a profile is set to inactive.

Currently the person's status can only be changed by the DBA.

**Comment by gjvoosten** [comment]
@dspCarlson As per https://github.com/NCI-Agency/anet/issues/65#issuecomment-317777315 :
> • the status of an inactive person cannot be changed

This was implemented in July 2017; should this be revised?

**Comment by dspCarlson** [comment]
@gjvoosten Yes, this should be revised.  Restoring an ANET profile involves (1) updating the domain user name, (2) setting the profile status to active and (3) updating the end of tour date.  The ANET trainers are already able to update the domain user name, but the ANET trainers should also be able to update the status as well.  The ANET trainers should not have to contact me to set the status to active.

Note: The super user or the user can update the end of tour date themselves.

**Comment by dspCarlson** [comment]
@gjvoosten Activating a user only applies to administrators, not super users.
