### ISSUE TITLE
On a person's work assignment history, a record is showing an "Unspecified" line

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#998]
An "Unspecified" record is displayed as an assignment when the peoplePositions table has the following record:
positionID = NULL
personID has a value

The "Unspecified" assignment is only displayed on the person's page.

**Comment by gjvoosten** [comment]
@dspCarlson When showing the people history of a position, the records where `personId = NULL` are filtered out. We could do a similar thing for showing the position history of a person: filter out the records where `positionId = NULL`. Would that sufficiently address this issue?

**Comment by dspCarlson** [comment]
@gjvoosten Yes, that would do the trick.

**Comment by dspCarlson** [comment]
Tested in production.  The unspecified lines/records are no longer displayed.
